modeling:
  NET_NAME: 'GRU-32H1-32H2'
paths:
  # PATH HAS TO END WITH A SOLIDUS ("/") CHARACTER
  path_to_experiment: 'Pretrained-RNN-1/'
  PATH_TO_EXPERIMENT_FOLDERS: './SI_Toolkit_ApplicationSpecificFiles/Experiments/'  # Path where the experiments data is stored

training_default:
  # For training closed loop dynamics model:
  control_inputs: ['Q']
  state_inputs: ['angle_sin', 'angle_cos', 'angleD', 'position', 'positionD']
  setpoint_inputs: []  # Can be only 'target_position' or empty for CartPole
  outputs: ['angle_sin', 'angle_cos', 'angleD', 'position', 'positionD']
  # For training open loop dynamics model:
  # inputs = ['position', 'positionD', 'angle_sin', 'angle_cos', 'angleD']
  # outputs = inputs_list
  # For training of RNN imitating MPC:
  # inputs = ['position', 'positionD', 'angle', 'angleD', 'target_position']
  # outputs = ['Q']
  EPOCHS: 5
  BATCH_SIZE: 16
  SEED: 1873
  LR: 1.0e-2
  WASH_OUT_LEN: 10
  POST_WASH_OUT_LEN: 20
  ON_FLY_DATA_GENERATION: False
  NORMALIZE: True

