modeling:
  NET_NAME: 'GRU-6IN-32H1-32H2-5OUT-0'
  RNN_PATH: './save_tf/'
  PREDICTION_FEATURES_NAMES: ['angle_cos', 'angle_sin', 'angleD', 'position', 'positionD']

paths:
  # PATH HAS TO END WITH A SOLIDUS ("/") CHARACTER
  path_to_experiment: 'Pretrained-RNN-1/'
  PATH_TO_EXPERIMENT_FOLDERS: './SI_Toolkit_ApplicationSpecificFiles/Experiments/'  # Path where the experiments data is stored

training_default:
  # For training closed loop dynamics model:
  control_inputs: ['Q']
  state_inputs: ['angle_sin', 'angle_cos', 'angleD', 'position', 'positionD']
  setpoint_inputs: []  # Can be only 'target_position' or empty for CartPole
  outputs: ['angle_sin', 'angle_cos', 'angleD', 'position', 'positionD']
  # For training open loop dynamics model:
  # inputs = ['position', 'positionD', 'angle_sin', 'angle_cos', 'angleD']
  # outputs = inputs_list
  # For training of RNN imitating MPC:
  # inputs = ['position', 'positionD', 'angle', 'angleD', 'target_position']
  # outputs = ['Q']

testing:
  tests: ['Euler']#, 'GRU-6IN-32H1-32H2-5OUT-0']  # May be 'Euler', name of network or None
  TEST_FILE: '/Volumes/GoogleDrive/My Drive/LTC Semester Project/physical-cartpole/Driver/ExperimentRecordings/cartpole-2021-11-16-00-21-24 measurement short.csv'