modeling:
  NET_NAME: 'GRU-6IN-32H1-32H2-5OUT-0'
  RNN_PATH: './save_tf/'
  PREDICTION_FEATURES_NAMES: ['angle_cos', 'angle_sin', 'angleD', 'position', 'positionD']

paths:
  # PATH HAS TO END WITH A SOLIDUS ("/") CHARACTER
  path_to_experiment: 'Pretrained-RNN-1/'
  PATH_TO_EXPERIMENT_FOLDERS: './SI_Toolkit_ApplicationSpecificFiles/Experiments/'  # Path where the experiments data is stored

training_default:
  # For training closed loop dynamics model:
  control_inputs: ['Q']
  state_inputs: ['angle_sin', 'angle_cos', 'angleD', 'position', 'positionD']
  setpoint_inputs: []  # Can be only 'target_position' or empty for CartPole
  outputs: ['angle_sin', 'angle_cos', 'angleD', 'position', 'positionD']
  # For training open loop dynamics model:
  # inputs = ['position', 'positionD', 'angle_sin', 'angle_cos', 'angleD']
  # outputs = inputs_list
  # For training of RNN imitating MPC:
  # inputs = ['position', 'positionD', 'angle', 'angleD', 'target_position']
  # outputs = ['Q']

testing:
  tests: ['Euler', 'EulerTF', 'GRU-6IN-32H1-32H2-5OUT-0'] #, 'GRU-6IN-32H1-32H2-5OUT-0']#, 'GRU-6IN-32H1-32H2-5OUT-0']  # May be 'Euler', name of network or None

  #TEST_FILE: '/home/jeanninj/Dropbox/physical-cartpole/Driver/ExperimentRecordings/CP_mppi_2021-11-29_15-19-18 measurement.csv'

  #TEST_FILE 'ExperimentRecordings/CP_PID_2022-01-22_01-34-16 20ms swinging.csv'
  #TEST_FILE: 'ExperimentRecordings/CP_PID_2022-01-22_01-34-16 20ms swinging short.csv'
  #TEST_FILE: 'ExperimentRecordings/CP_PID_2022-01-21_18-56-13 20ms measurement.csv'
  TEST_FILE: 'ExperimentRecordings/CP_PID_2022-01-21_18-56-13 20ms measurement short.csv' # train Friction on this!
  #TEST_FILE: 'ExperimentRecordings/CP_mppi-tf_2022-01-24_18-22-03.csv'

  #TEST_FILE: 'ExperimentRecordings/CP_PID_2022-01-20_21-17-04 5ms swinging.csv'
  #TEST_FILE: 'ExperimentRecordings/CP_PID_2022-01-20_21-17-04 5ms swinging medium.csv'
  #TEST_FILE: 'ExperimentRecordings/CP_PID_2022-01-20_21-17-04 5ms swinging short.csv'
  #TEST_FILE: 'ExperimentRecordings/CP_PID_2022-01-20_21-44-38 5ms measurement.csv'
  #TEST_FILE: 'ExperimentRecordings/CP_PID_2022-01-20_21-44-38 5ms measurement short.csv'




