set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_Enablepin]
set_property PACKAGE_PIN AA11 [get_ports Pmod_out_Enablepin]
set_property PACKAGE_PIN Y11 [get_ports Pmod_out_Directionpin]
set_property PACKAGE_PIN AA9 [get_ports Pmod_in_Sensefeedback_B]
set_property PACKAGE_PIN Y10 [get_ports Pmod_in_Sensefeedback_A]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_in_Sensefeedback_A]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_in_Sensefeedback_B]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod_out_Directionpin]
#set_property PACKAGE_PIN M12 [get_ports Vp_Vn_0_v_n]
#set_property PACKAGE_PIN L11 [get_ports Vp_Vn_0_v_p]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux0_0_v_n]
set_property PACKAGE_PIN E16 [get_ports Vaux0_0_v_n]
set_property IOSTANDARD LVCMOS33 [get_ports Vaux0_0_v_p]
set_property PACKAGE_PIN P16 [get_ports Vaux0_0_v_p]

set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws_8bits_tri_i[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
