library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.controller_io_parameters.all;

-- Adapter between controller_axi core_* interface
-- and an hls4ml core with:
--   ap_ctrl_hs
--   input_1_V / input_1_V_ap_vld
--   layer9_out_0_V / layer9_out_0_V_ap_vld
--
-- Adjust only this file if the HLS entity name or ports change.

entity controller_adapter_cp is
  port(
    -- From controller_axi
    core_clk       : in  std_logic;
    core_rst       : in  std_logic;  -- active-high
    core_start     : in  std_logic;  -- 1-cycle (or level) start as driven by shell FSM
    core_ready     : out std_logic;  -- shell waits here before dropping start
    core_done      : out std_logic;  -- shell uses this (or out_valid) to PACK_OUTPUTS
    core_in        : in  std_logic_vector(CONTROLLER_INPUTS*BITS_PER_CONTROLLER_INPUT-1 downto 0);
    core_in_valid  : in  std_logic;
    core_out       : out std_logic_vector(CONTROLLER_OUTPUTS*BITS_PER_CONTROLLER_OUTPUT-1 downto 0);
    core_out_valid : out std_logic
  );
end entity;

architecture RTL of controller_adapter_cp is

  signal ap_done_s    : std_logic;
  signal ap_idle_s    : std_logic;
  signal ap_ready_s   : std_logic;
  signal out_v_s      : std_logic_vector(CONTROLLER_OUTPUTS*BITS_PER_CONTROLLER_OUTPUT-1 downto 0);
  signal out_vld_s    : std_logic;

begin

  -- HLS core instance (adjust name/port names if your generated core differs)
  u_controller : entity work.myproject
    port map(
      ap_clk                => core_clk,
      ap_rst                => core_rst,
      ap_start              => core_start,
      ap_done               => ap_done_s,
      ap_idle               => ap_idle_s,
      ap_ready              => ap_ready_s,
      input_1_V             => core_in,
      input_1_V_ap_vld      => core_in_valid,
      layer9_out_0_V        => out_v_s,
      layer9_out_0_V_ap_vld => out_vld_s
    );

  -- Handshake mapping:
  --  core_start/core_in_valid are generated by the shell exactly like ap_ctrl_hs expects.
  --  core_ready is directly ap_ready.
  --  core_done/valid reflect ap_done and output valid.
  core_ready     <= ap_ready_s;
  core_out       <= out_v_s;
  core_out_valid <= out_vld_s;
  core_done      <= ap_done_s;

end RTL;

