-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity median_filter is
generic (
    C_S_AXI_MEDIAN_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_MEDIAN_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    xadc_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    xadc_stream_TVALID : IN STD_LOGIC;
    xadc_stream_TREADY : OUT STD_LOGIC;
    xadc_stream_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    xadc_stream_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    xadc_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    xadc_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    xadc_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    xadc_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axi_MEDIAN_AWVALID : IN STD_LOGIC;
    s_axi_MEDIAN_AWREADY : OUT STD_LOGIC;
    s_axi_MEDIAN_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_MEDIAN_ADDR_WIDTH-1 downto 0);
    s_axi_MEDIAN_WVALID : IN STD_LOGIC;
    s_axi_MEDIAN_WREADY : OUT STD_LOGIC;
    s_axi_MEDIAN_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_MEDIAN_DATA_WIDTH-1 downto 0);
    s_axi_MEDIAN_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_MEDIAN_DATA_WIDTH/8-1 downto 0);
    s_axi_MEDIAN_ARVALID : IN STD_LOGIC;
    s_axi_MEDIAN_ARREADY : OUT STD_LOGIC;
    s_axi_MEDIAN_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_MEDIAN_ADDR_WIDTH-1 downto 0);
    s_axi_MEDIAN_RVALID : OUT STD_LOGIC;
    s_axi_MEDIAN_RREADY : IN STD_LOGIC;
    s_axi_MEDIAN_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_MEDIAN_DATA_WIDTH-1 downto 0);
    s_axi_MEDIAN_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_MEDIAN_BVALID : OUT STD_LOGIC;
    s_axi_MEDIAN_BREADY : IN STD_LOGIC;
    s_axi_MEDIAN_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of median_filter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "median_filter_median_filter,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.657750,HLS_SYN_LAT=60,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=2170,HLS_SYN_LUT=3351,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal filtered_i : STD_LOGIC_VECTOR (31 downto 0);
    signal filtered_o : STD_LOGIC_VECTOR (31 downto 0);
    signal filtered_o_ap_vld : STD_LOGIC;
    signal raw_i : STD_LOGIC_VECTOR (31 downto 0);
    signal raw_o : STD_LOGIC_VECTOR (31 downto 0);
    signal raw_o_ap_vld : STD_LOGIC;
    signal window_size : STD_LOGIC_VECTOR (31 downto 0);
    signal trim_count : STD_LOGIC_VECTOR (31 downto 0);
    signal filter_mode : STD_LOGIC_VECTOR (31 downto 0);
    signal rail_low : STD_LOGIC_VECTOR (31 downto 0);
    signal rail_high : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_status_i : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_status_o : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_status_o_ap_vld : STD_LOGIC;
    signal dz_window_i : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_window_o : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_window_o_ap_vld : STD_LOGIC;
    signal dz_age_i : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_age_o : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_age_o_ap_vld : STD_LOGIC;
    signal dz_low_count_ap_vld : STD_LOGIC;
    signal dz_high_count_ap_vld : STD_LOGIC;
    signal rail_low_input : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rail_high_input : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    signal dz_low_count_value : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal dz_high_count_value : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal dz_age_value : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    signal raw_value : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal window_size_input : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    signal trim_count_input : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal filter_mode_input : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    signal filtered_value : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal dz_window_value : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal dz_status_value : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal xadc_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_nbreadreq_fu_182_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_700 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal rail_low_input_load_reg_704 : STD_LOGIC_VECTOR (15 downto 0);
    signal rail_high_input_load_reg_709 : STD_LOGIC_VECTOR (15 downto 0);
    signal dz_low_count_value_load_reg_714 : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_high_count_value_load_reg_721 : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_age_value_load_reg_730 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_V_reg_738 : STD_LOGIC_VECTOR (15 downto 0);
    signal window_size_input_load_reg_743 : STD_LOGIC_VECTOR (15 downto 0);
    signal trim_count_input_load_reg_748 : STD_LOGIC_VECTOR (15 downto 0);
    signal filter_mode_input_load_reg_753 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln70_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln70_reg_758 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_fu_493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_reg_762 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln75_fu_539_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_get_filtered_value_fu_363_ap_ready : STD_LOGIC;
    signal grp_get_filtered_value_fu_363_ap_done : STD_LOGIC;
    signal grp_get_filtered_value_fu_363_ap_start : STD_LOGIC;
    signal grp_get_filtered_value_fu_363_ap_idle : STD_LOGIC;
    signal grp_get_filtered_value_fu_363_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_get_filtered_value_fu_363_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal dz_low_count_value_loc_0_reg_299 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln78_fu_550_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_phi_mux_dz_low_count_value_loc_1_phi_fu_320_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_low_count_value_loc_1_reg_317 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln82_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_dz_high_count_value_loc_1_phi_fu_337_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal dz_high_count_value_loc_1_reg_334 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_dz_age_value_loc_0_phi_fu_352_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal dz_age_value_loc_0_reg_349 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln83_fu_573_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_get_filtered_value_fu_363_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call6 : BOOLEAN;
    signal empty_32_fu_395_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_33_fu_399_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_383_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_30_fu_387_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_31_fu_391_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_fu_505_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal at_high_rail_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal at_low_rail_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_589_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_612_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_639_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln94_fu_635_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_662_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_fu_681_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_xadc_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal xadc_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal xadc_stream_TVALID_int_regslice : STD_LOGIC;
    signal xadc_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_xadc_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_xadc_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal xadc_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_xadc_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_xadc_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_xadc_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal xadc_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_xadc_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_xadc_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_xadc_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal xadc_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_xadc_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_xadc_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_xadc_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal xadc_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_xadc_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_xadc_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_xadc_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal xadc_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_xadc_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_xadc_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_xadc_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal xadc_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_xadc_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_xadc_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_condition_187 : BOOLEAN;
    signal ap_condition_193 : BOOLEAN;
    signal ap_condition_197 : BOOLEAN;

    component median_filter_get_filtered_value IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        newValue : IN STD_LOGIC_VECTOR (15 downto 0);
        window_size : IN STD_LOGIC_VECTOR (15 downto 0);
        trim_count : IN STD_LOGIC_VECTOR (15 downto 0);
        filter_mode : IN STD_LOGIC_VECTOR (15 downto 0);
        rail_low : IN STD_LOGIC_VECTOR (15 downto 0);
        rail_high : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component median_filter_MEDIAN_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        filtered_o : IN STD_LOGIC_VECTOR (31 downto 0);
        filtered_o_ap_vld : IN STD_LOGIC;
        filtered_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        raw_o : IN STD_LOGIC_VECTOR (31 downto 0);
        raw_o_ap_vld : IN STD_LOGIC;
        raw_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        window_size : OUT STD_LOGIC_VECTOR (31 downto 0);
        trim_count : OUT STD_LOGIC_VECTOR (31 downto 0);
        filter_mode : OUT STD_LOGIC_VECTOR (31 downto 0);
        rail_low : OUT STD_LOGIC_VECTOR (31 downto 0);
        rail_high : OUT STD_LOGIC_VECTOR (31 downto 0);
        dz_status_o : IN STD_LOGIC_VECTOR (31 downto 0);
        dz_status_o_ap_vld : IN STD_LOGIC;
        dz_status_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        dz_window_o : IN STD_LOGIC_VECTOR (31 downto 0);
        dz_window_o_ap_vld : IN STD_LOGIC;
        dz_window_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        dz_age_o : IN STD_LOGIC_VECTOR (31 downto 0);
        dz_age_o_ap_vld : IN STD_LOGIC;
        dz_age_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        dz_low_count : IN STD_LOGIC_VECTOR (31 downto 0);
        dz_low_count_ap_vld : IN STD_LOGIC;
        dz_high_count : IN STD_LOGIC_VECTOR (31 downto 0);
        dz_high_count_ap_vld : IN STD_LOGIC );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    MEDIAN_s_axi_U : component median_filter_MEDIAN_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_MEDIAN_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_MEDIAN_DATA_WIDTH)
    port map (
        AWVALID => s_axi_MEDIAN_AWVALID,
        AWREADY => s_axi_MEDIAN_AWREADY,
        AWADDR => s_axi_MEDIAN_AWADDR,
        WVALID => s_axi_MEDIAN_WVALID,
        WREADY => s_axi_MEDIAN_WREADY,
        WDATA => s_axi_MEDIAN_WDATA,
        WSTRB => s_axi_MEDIAN_WSTRB,
        ARVALID => s_axi_MEDIAN_ARVALID,
        ARREADY => s_axi_MEDIAN_ARREADY,
        ARADDR => s_axi_MEDIAN_ARADDR,
        RVALID => s_axi_MEDIAN_RVALID,
        RREADY => s_axi_MEDIAN_RREADY,
        RDATA => s_axi_MEDIAN_RDATA,
        RRESP => s_axi_MEDIAN_RRESP,
        BVALID => s_axi_MEDIAN_BVALID,
        BREADY => s_axi_MEDIAN_BREADY,
        BRESP => s_axi_MEDIAN_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        filtered_o => filtered_o,
        filtered_o_ap_vld => filtered_o_ap_vld,
        filtered_i => filtered_i,
        raw_o => raw_o,
        raw_o_ap_vld => raw_o_ap_vld,
        raw_i => raw_i,
        window_size => window_size,
        trim_count => trim_count,
        filter_mode => filter_mode,
        rail_low => rail_low,
        rail_high => rail_high,
        dz_status_o => dz_status_o,
        dz_status_o_ap_vld => dz_status_o_ap_vld,
        dz_status_i => dz_status_i,
        dz_window_o => dz_window_o,
        dz_window_o_ap_vld => dz_window_o_ap_vld,
        dz_window_i => dz_window_i,
        dz_age_o => dz_age_o,
        dz_age_o_ap_vld => dz_age_o_ap_vld,
        dz_age_i => dz_age_i,
        dz_low_count => ap_phi_mux_dz_low_count_value_loc_1_phi_fu_320_p8,
        dz_low_count_ap_vld => dz_low_count_ap_vld,
        dz_high_count => ap_phi_mux_dz_high_count_value_loc_1_phi_fu_337_p8,
        dz_high_count_ap_vld => dz_high_count_ap_vld);

    grp_get_filtered_value_fu_363 : component median_filter_get_filtered_value
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_get_filtered_value_fu_363_ap_start,
        ap_done => grp_get_filtered_value_fu_363_ap_done,
        ap_idle => grp_get_filtered_value_fu_363_ap_idle,
        ap_ready => grp_get_filtered_value_fu_363_ap_ready,
        newValue => tmp_data_V_reg_738,
        window_size => window_size_input_load_reg_743,
        trim_count => trim_count_input_load_reg_748,
        filter_mode => filter_mode_input_load_reg_753,
        rail_low => rail_low_input_load_reg_704,
        rail_high => rail_high_input_load_reg_709,
        ap_return_0 => grp_get_filtered_value_fu_363_ap_return_0,
        ap_return_1 => grp_get_filtered_value_fu_363_ap_return_1);

    regslice_both_xadc_stream_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => xadc_stream_TDATA,
        vld_in => xadc_stream_TVALID,
        ack_in => regslice_both_xadc_stream_V_data_V_U_ack_in,
        data_out => xadc_stream_TDATA_int_regslice,
        vld_out => xadc_stream_TVALID_int_regslice,
        ack_out => xadc_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_xadc_stream_V_data_V_U_apdone_blk);

    regslice_both_xadc_stream_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => xadc_stream_TKEEP,
        vld_in => xadc_stream_TVALID,
        ack_in => regslice_both_xadc_stream_V_keep_V_U_ack_in,
        data_out => xadc_stream_TKEEP_int_regslice,
        vld_out => regslice_both_xadc_stream_V_keep_V_U_vld_out,
        ack_out => xadc_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_xadc_stream_V_keep_V_U_apdone_blk);

    regslice_both_xadc_stream_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => xadc_stream_TSTRB,
        vld_in => xadc_stream_TVALID,
        ack_in => regslice_both_xadc_stream_V_strb_V_U_ack_in,
        data_out => xadc_stream_TSTRB_int_regslice,
        vld_out => regslice_both_xadc_stream_V_strb_V_U_vld_out,
        ack_out => xadc_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_xadc_stream_V_strb_V_U_apdone_blk);

    regslice_both_xadc_stream_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => xadc_stream_TUSER,
        vld_in => xadc_stream_TVALID,
        ack_in => regslice_both_xadc_stream_V_user_V_U_ack_in,
        data_out => xadc_stream_TUSER_int_regslice,
        vld_out => regslice_both_xadc_stream_V_user_V_U_vld_out,
        ack_out => xadc_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_xadc_stream_V_user_V_U_apdone_blk);

    regslice_both_xadc_stream_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => xadc_stream_TLAST,
        vld_in => xadc_stream_TVALID,
        ack_in => regslice_both_xadc_stream_V_last_V_U_ack_in,
        data_out => xadc_stream_TLAST_int_regslice,
        vld_out => regslice_both_xadc_stream_V_last_V_U_vld_out,
        ack_out => xadc_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_xadc_stream_V_last_V_U_apdone_blk);

    regslice_both_xadc_stream_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => xadc_stream_TID,
        vld_in => xadc_stream_TVALID,
        ack_in => regslice_both_xadc_stream_V_id_V_U_ack_in,
        data_out => xadc_stream_TID_int_regslice,
        vld_out => regslice_both_xadc_stream_V_id_V_U_vld_out,
        ack_out => xadc_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_xadc_stream_V_id_V_U_apdone_blk);

    regslice_both_xadc_stream_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => xadc_stream_TDEST,
        vld_in => xadc_stream_TVALID,
        ack_in => regslice_both_xadc_stream_V_dest_V_U_ack_in,
        data_out => xadc_stream_TDEST_int_regslice,
        vld_out => regslice_both_xadc_stream_V_dest_V_U_vld_out,
        ack_out => xadc_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_xadc_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_get_filtered_value_fu_363_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_get_filtered_value_fu_363_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_get_filtered_value_fu_363_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_get_filtered_value_fu_363_ap_ready = ap_const_logic_1)) then 
                    grp_get_filtered_value_fu_363_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    dz_age_value_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((ap_const_boolean_1 = ap_condition_197)) then 
                    dz_age_value <= add_ln83_fu_573_p2;
                elsif ((ap_const_boolean_1 = ap_condition_187)) then 
                    dz_age_value <= ap_const_lv16_0;
                end if;
            end if; 
        end if;
    end process;

    dz_age_value_loc_0_reg_349_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                dz_age_value_loc_0_reg_349 <= dz_age_value;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_0) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1))) then 
                dz_age_value_loc_0_reg_349 <= add_ln83_fu_573_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_1) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1))) then 
                dz_age_value_loc_0_reg_349 <= dz_age_value_load_reg_730;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln71_reg_762 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)) or ((icmp_ln70_reg_758 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1))))) then 
                dz_age_value_loc_0_reg_349 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    dz_high_count_value_loc_1_reg_334_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                dz_high_count_value_loc_1_reg_334 <= dz_high_count_value;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_0) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_1) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1)))) then 
                dz_high_count_value_loc_1_reg_334 <= dz_high_count_value_load_reg_721;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln71_reg_762 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)) or ((icmp_ln70_reg_758 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1))))) then 
                dz_high_count_value_loc_1_reg_334 <= ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4;
            end if; 
        end if;
    end process;

    dz_low_count_value_loc_0_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_get_filtered_value_fu_363_ap_done = ap_const_logic_1))) then
                if ((icmp_ln70_reg_758 = ap_const_lv1_1)) then 
                    dz_low_count_value_loc_0_reg_299 <= dz_low_count_value_load_reg_714;
                elsif ((icmp_ln70_reg_758 = ap_const_lv1_0)) then 
                    dz_low_count_value_loc_0_reg_299 <= add_ln75_fu_539_p2;
                end if;
            end if; 
        end if;
    end process;

    dz_low_count_value_loc_1_reg_317_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                dz_low_count_value_loc_1_reg_317 <= dz_low_count_value;
            elsif ((((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_0) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_1) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln71_reg_762 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)) or ((icmp_ln70_reg_758 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)))))) then 
                dz_low_count_value_loc_1_reg_317 <= dz_low_count_value_loc_0_reg_299;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                dz_age_value_load_reg_730 <= dz_age_value;
                dz_high_count_value_load_reg_721 <= dz_high_count_value;
                dz_low_count_value_load_reg_714 <= dz_low_count_value;
                rail_high_input_load_reg_709 <= rail_high_input;
                rail_low_input_load_reg_704 <= rail_low_input;
                tmp_reg_700 <= tmp_nbreadreq_fu_182_p9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln71_reg_762 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1))) then
                dz_high_count_value <= add_ln78_fu_550_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_get_filtered_value_fu_363_ap_done = ap_const_logic_1) and (icmp_ln70_reg_758 = ap_const_lv1_0))) then
                dz_low_count_value <= add_ln75_fu_539_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                dz_status_value <= tmp_1_fu_505_p3;
                filter_mode_input_load_reg_753 <= filter_mode_input;
                icmp_ln70_reg_758 <= icmp_ln70_fu_481_p2;
                icmp_ln71_reg_762 <= icmp_ln71_fu_493_p2;
                raw_value <= xadc_stream_TDATA_int_regslice;
                tmp_data_V_reg_738 <= xadc_stream_TDATA_int_regslice;
                trim_count_input_load_reg_748 <= trim_count_input;
                window_size_input_load_reg_743 <= window_size_input;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_get_filtered_value_fu_363_ap_done = ap_const_logic_1))) then
                dz_window_value <= grp_get_filtered_value_fu_363_ap_return_1;
                filtered_value <= grp_get_filtered_value_fu_363_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                filter_mode_input <= empty_31_fu_391_p1;
                rail_high_input <= empty_33_fu_399_p1;
                rail_low_input <= empty_32_fu_395_p1;
                trim_count_input <= empty_30_fu_387_p1;
                window_size_input <= empty_fu_383_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, tmp_nbreadreq_fu_182_p9, ap_CS_fsm_state2, grp_get_filtered_value_fu_363_ap_done, xadc_stream_TVALID_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_get_filtered_value_fu_363_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln75_fu_539_p2 <= std_logic_vector(unsigned(dz_low_count_value_load_reg_714) + unsigned(ap_const_lv32_1));
    add_ln78_fu_550_p2 <= std_logic_vector(unsigned(dz_high_count_value_load_reg_721) + unsigned(ap_const_lv32_1));
    add_ln83_fu_573_p2 <= std_logic_vector(unsigned(dz_age_value_load_reg_730) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(tmp_nbreadreq_fu_182_p9, xadc_stream_TVALID_int_regslice)
    begin
                ap_block_state1 <= ((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call6_assign_proc : process(tmp_nbreadreq_fu_182_p9, xadc_stream_TVALID_int_regslice)
    begin
                ap_block_state1_ignore_call6 <= ((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_187_assign_proc : process(tmp_reg_700, icmp_ln70_reg_758, icmp_ln71_reg_762)
    begin
                ap_condition_187 <= (((icmp_ln71_reg_762 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)) or ((icmp_ln70_reg_758 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)));
    end process;


    ap_condition_193_assign_proc : process(tmp_reg_700, icmp_ln70_reg_758, icmp_ln71_reg_762, icmp_ln82_fu_568_p2)
    begin
                ap_condition_193 <= ((icmp_ln82_fu_568_p2 = ap_const_lv1_1) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1));
    end process;


    ap_condition_197_assign_proc : process(tmp_reg_700, icmp_ln70_reg_758, icmp_ln71_reg_762, icmp_ln82_fu_568_p2)
    begin
                ap_condition_197 <= ((icmp_ln82_fu_568_p2 = ap_const_lv1_0) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1));
    end process;


    ap_phi_mux_dz_age_value_loc_0_phi_fu_352_p8_assign_proc : process(dz_age_value_load_reg_730, ap_CS_fsm_state3, dz_age_value_loc_0_reg_349, add_ln83_fu_573_p2, ap_condition_187, ap_condition_193, ap_condition_197)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_boolean_1 = ap_condition_197)) then 
                ap_phi_mux_dz_age_value_loc_0_phi_fu_352_p8 <= add_ln83_fu_573_p2;
            elsif ((ap_const_boolean_1 = ap_condition_193)) then 
                ap_phi_mux_dz_age_value_loc_0_phi_fu_352_p8 <= dz_age_value_load_reg_730;
            elsif ((ap_const_boolean_1 = ap_condition_187)) then 
                ap_phi_mux_dz_age_value_loc_0_phi_fu_352_p8 <= ap_const_lv16_0;
            else 
                ap_phi_mux_dz_age_value_loc_0_phi_fu_352_p8 <= dz_age_value_loc_0_reg_349;
            end if;
        else 
            ap_phi_mux_dz_age_value_loc_0_phi_fu_352_p8 <= dz_age_value_loc_0_reg_349;
        end if; 
    end process;


    ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4_assign_proc : process(tmp_reg_700, dz_high_count_value_load_reg_721, icmp_ln70_reg_758, icmp_ln71_reg_762, add_ln78_fu_550_p2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (tmp_reg_700 = ap_const_lv1_1))) then
            if (((icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_0))) then 
                ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4 <= dz_high_count_value_load_reg_721;
            elsif ((icmp_ln71_reg_762 = ap_const_lv1_0)) then 
                ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4 <= add_ln78_fu_550_p2;
            else 
                ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_dz_high_count_value_loc_1_phi_fu_337_p8_assign_proc : process(tmp_reg_700, dz_high_count_value_load_reg_721, icmp_ln70_reg_758, icmp_ln71_reg_762, ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4, ap_CS_fsm_state3, icmp_ln82_fu_568_p2, dz_high_count_value_loc_1_reg_334)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_0) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_1) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1)))) then 
            ap_phi_mux_dz_high_count_value_loc_1_phi_fu_337_p8 <= dz_high_count_value_load_reg_721;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln71_reg_762 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)) or ((icmp_ln70_reg_758 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1))))) then 
            ap_phi_mux_dz_high_count_value_loc_1_phi_fu_337_p8 <= ap_phi_mux_dz_high_count_value_loc_0_phi_fu_311_p4;
        else 
            ap_phi_mux_dz_high_count_value_loc_1_phi_fu_337_p8 <= dz_high_count_value_loc_1_reg_334;
        end if; 
    end process;


    ap_phi_mux_dz_low_count_value_loc_1_phi_fu_320_p8_assign_proc : process(tmp_reg_700, icmp_ln70_reg_758, icmp_ln71_reg_762, dz_low_count_value_loc_0_reg_299, ap_CS_fsm_state3, dz_low_count_value_loc_1_reg_317, icmp_ln82_fu_568_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_0) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln82_fu_568_p2 = ap_const_lv1_1) and (icmp_ln71_reg_762 = ap_const_lv1_1) and (icmp_ln70_reg_758 = ap_const_lv1_1) and (tmp_reg_700 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln71_reg_762 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)) or ((icmp_ln70_reg_758 = ap_const_lv1_0) and (tmp_reg_700 = ap_const_lv1_1)))))) then 
            ap_phi_mux_dz_low_count_value_loc_1_phi_fu_320_p8 <= dz_low_count_value_loc_0_reg_299;
        else 
            ap_phi_mux_dz_low_count_value_loc_1_phi_fu_320_p8 <= dz_low_count_value_loc_1_reg_317;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    at_high_rail_fu_499_p2 <= (icmp_ln71_fu_493_p2 xor ap_const_lv1_1);
    at_low_rail_fu_487_p2 <= (icmp_ln70_fu_481_p2 xor ap_const_lv1_1);
    dz_age_o <= (tmp_7_fu_681_p4 & ap_phi_mux_dz_age_value_loc_0_phi_fu_352_p8);

    dz_age_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dz_age_o_ap_vld <= ap_const_logic_1;
        else 
            dz_age_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    dz_high_count_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dz_high_count_ap_vld <= ap_const_logic_1;
        else 
            dz_high_count_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    dz_low_count_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dz_low_count_ap_vld <= ap_const_logic_1;
        else 
            dz_low_count_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    dz_status_o <= (tmp_5_fu_639_p4 & zext_ln94_fu_635_p1);

    dz_status_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dz_status_o_ap_vld <= ap_const_logic_1;
        else 
            dz_status_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    dz_window_o <= (tmp_6_fu_662_p4 & dz_window_value);

    dz_window_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dz_window_o_ap_vld <= ap_const_logic_1;
        else 
            dz_window_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    empty_30_fu_387_p1 <= trim_count(16 - 1 downto 0);
    empty_31_fu_391_p1 <= filter_mode(16 - 1 downto 0);
    empty_32_fu_395_p1 <= rail_low(16 - 1 downto 0);
    empty_33_fu_399_p1 <= rail_high(16 - 1 downto 0);
    empty_fu_383_p1 <= window_size(16 - 1 downto 0);
    filtered_o <= (tmp_3_fu_589_p4 & filtered_value);

    filtered_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            filtered_o_ap_vld <= ap_const_logic_1;
        else 
            filtered_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_get_filtered_value_fu_363_ap_start <= grp_get_filtered_value_fu_363_ap_start_reg;
    icmp_ln70_fu_481_p2 <= "1" when (unsigned(rail_low_input) < unsigned(xadc_stream_TDATA_int_regslice)) else "0";
    icmp_ln71_fu_493_p2 <= "1" when (unsigned(xadc_stream_TDATA_int_regslice) < unsigned(rail_high_input)) else "0";
    icmp_ln82_fu_568_p2 <= "1" when (dz_age_value_load_reg_730 = ap_const_lv16_FFFF) else "0";
    raw_o <= (tmp_4_fu_612_p4 & raw_value);

    raw_o_ap_vld_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            raw_o_ap_vld <= ap_const_logic_1;
        else 
            raw_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_505_p3 <= (at_high_rail_fu_499_p2 & at_low_rail_fu_487_p2);
    tmp_3_fu_589_p4 <= filtered_i(31 downto 16);
    tmp_4_fu_612_p4 <= raw_i(31 downto 16);
    tmp_5_fu_639_p4 <= dz_status_i(31 downto 16);
    tmp_6_fu_662_p4 <= dz_window_i(31 downto 16);
    tmp_7_fu_681_p4 <= dz_age_i(31 downto 16);
    tmp_nbreadreq_fu_182_p9 <= (0=>(xadc_stream_TVALID_int_regslice), others=>'-');

    xadc_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_182_p9, xadc_stream_TVALID_int_regslice)
    begin
        if (((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xadc_stream_TDATA_blk_n <= xadc_stream_TVALID_int_regslice;
        else 
            xadc_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xadc_stream_TREADY <= regslice_both_xadc_stream_V_data_V_U_ack_in;

    xadc_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, tmp_nbreadreq_fu_182_p9, xadc_stream_TVALID_int_regslice)
    begin
        if ((not(((tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (xadc_stream_TVALID_int_regslice = ap_const_logic_0))) and (tmp_nbreadreq_fu_182_p9 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xadc_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            xadc_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln94_fu_635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dz_status_value),16));
end behav;
