-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity median_filter_get_filtered_value is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    newValue : IN STD_LOGIC_VECTOR (15 downto 0);
    window_size : IN STD_LOGIC_VECTOR (15 downto 0);
    trim_count : IN STD_LOGIC_VECTOR (15 downto 0);
    filter_mode : IN STD_LOGIC_VECTOR (15 downto 0);
    rail_low : IN STD_LOGIC_VECTOR (15 downto 0);
    rail_high : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of median_filter_get_filtered_value is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv16_40 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv23_1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal lastWindowSize : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal currentWindowSize : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal bufferIndex : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal buffer_r_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buffer_r_ce0 : STD_LOGIC;
    signal buffer_r_we0 : STD_LOGIC;
    signal buffer_r_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal window_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal window_ce0 : STD_LOGIC;
    signal window_we0 : STD_LOGIC;
    signal window_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal window_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal window_ce1 : STD_LOGIC;
    signal window_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_reg_251 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_reg_251_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal c_3_reg_263 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_3_reg_273 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_reg_284 : STD_LOGIC_VECTOR (15 downto 0);
    signal bit_reg_297 : STD_LOGIC_VECTOR (4 downto 0);
    signal remainder_reg_308 : STD_LOGIC_VECTOR (30 downto 0);
    signal quotient_reg_319 : STD_LOGIC_VECTOR (31 downto 0);
    signal filter_mode_read_read_fu_164_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln24_fu_394_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln24_reg_1411 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln39_fu_398_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln39_reg_1416 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln54_fu_434_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln54_reg_1476 : STD_LOGIC_VECTOR (14 downto 0);
    signal removal_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal removal_reg_1482 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal n_out_fu_523_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal n_out_reg_1493 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln57_fu_531_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln57_reg_1499 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln57_fu_535_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln57_reg_1503 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln63_1_reg_1510 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_reg_1515 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln64_2_reg_1520 : STD_LOGIC_VECTOR (14 downto 0);
    signal oldValue_reg_1525 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal mid_lo_fu_638_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal mid_lo_reg_1531 : STD_LOGIC_VECTOR (15 downto 0);
    signal first_index_fu_646_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal first_index_reg_1536 : STD_LOGIC_VECTOR (15 downto 0);
    signal last_index_fu_654_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal last_index_reg_1542 : STD_LOGIC_VECTOR (15 downto 0);
    signal mid_hi_fu_683_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal mid_hi_reg_1548 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln82_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_reg_1563 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln82_reg_1563_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln82_fu_696_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln82_reg_1567 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln87_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_reg_1577 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_reg_1577_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln87_reg_1577_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_m1_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_m1_reg_1581 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_0_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_0_reg_1586 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_p1_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_p1_reg_1592 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_fu_790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_reg_1598 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_reg_1598_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_reg_1598_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_1_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_1_reg_1603 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_1_reg_1603_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln125_1_reg_1603_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln128_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln128_reg_1608 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln128_reg_1608_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln131_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln131_reg_1613 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln131_reg_1613_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal d_reg_1618 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal skip_now_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal skip_now_reg_1623 : STD_LOGIC_VECTOR (0 downto 0);
    signal cand_valid_fu_852_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cand_valid_reg_1629 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln108_fu_858_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln108_reg_1634 : STD_LOGIC_VECTOR (0 downto 0);
    signal take_new_2_fu_872_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal take_new_2_reg_1639 : STD_LOGIC_VECTOR (0 downto 0);
    signal skip_now_2_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal skip_now_2_reg_1645 : STD_LOGIC_VECTOR (0 downto 0);
    signal take_new_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal take_new_reg_1651 : STD_LOGIC_VECTOR (0 downto 0);
    signal med_lo_2_reg_1657 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal out_5_fu_1029_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_5_reg_1663 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln137_fu_1052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln137_reg_1668 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln137_1_fu_1057_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln137_1_reg_1673 : STD_LOGIC_VECTOR (0 downto 0);
    signal kept_count_fu_1149_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal kept_count_reg_1678 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal sext_ln160_fu_1157_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln160_reg_1687 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal sext_ln160_2_fu_1160_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln160_2_reg_1692 : STD_LOGIC_VECTOR (30 downto 0);
    signal numerator_fu_1228_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal numerator_reg_1697 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal zext_ln161_fu_1257_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln161_reg_1707 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_block_state11_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state12_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal trunc_ln165_1_fu_1266_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln165_1_reg_1712 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_1280_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1718 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln163_fu_1288_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln163_reg_1722 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal or_ln166_fu_1339_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln166_reg_1727 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal quotient_1_fu_1355_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal remainder_3_fu_1363_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_condition_pp0_exit_iter2_state6 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_flush_enable : STD_LOGIC;
    signal n_old_reg_228 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln39_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bufferIndex_loc_0_reg_240 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_i_phi_fu_255_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_c_3_phi_fu_266_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_b_3_phi_fu_276_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_a_phi_fu_288_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_bit_phi_fu_301_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal ap_phi_mux_retval_0_phi_fu_333_p8 : STD_LOGIC_VECTOR (15 downto 0);
    signal retval_0_reg_330 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln171_fu_1371_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal zext_ln46_fu_477_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln85_fu_742_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln82_fu_902_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln10_1_fu_386_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln48_fu_509_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal med_lo_fu_128 : STD_LOGIC_VECTOR (15 downto 0);
    signal med_lo_3_fu_1038_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_2_fu_1101_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal med_hi_fu_136 : STD_LOGIC_VECTOR (15 downto 0);
    signal med_hi_2_fu_1045_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal rail_hits_fu_140 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln137_fu_1131_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal skip_done_fu_144 : STD_LOGIC_VECTOR (0 downto 0);
    signal skip_done_3_fu_993_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal inserted_fu_148 : STD_LOGIC_VECTOR (0 downto 0);
    signal inserted_2_fu_1007_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln13_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln10_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln10_fu_372_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln24_1_fu_356_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_1_fu_426_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln24_fu_352_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln48_fu_482_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln48_fu_486_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln48_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln48_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln48_1_fu_503_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_fu_517_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln63_fu_539_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln_fu_588_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln57_fu_595_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln57_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln63_fu_610_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_fu_615_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln63_1_fu_623_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln63_2_fu_628_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln57_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln24_1_fu_585_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln64_fu_659_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln64_1_fu_664_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln64_1_fu_677_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln64_fu_674_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln84_fu_702_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln84_1_fu_710_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln84_fu_714_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_4_fu_720_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln84_1_fu_728_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal prefetch_idx_fu_734_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln84_fu_706_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln94_fu_752_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln94_fu_758_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln96_fu_774_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln96_fu_780_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln100_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln101_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal eq_b_fu_815_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln106_fu_842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal le_c_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal le_b_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln108_fu_866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal eq_a_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln113_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln117_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln109_fu_919_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln111_fu_932_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln111_fu_937_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_fu_960_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_972_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln104_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal skip_done_1_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_978_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel31_fu_985_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln104_fu_1001_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln118_fu_954_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_fu_926_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln112_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_1_fu_947_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_2_fu_1013_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_3_fu_1021_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln125_fu_1082_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln126_fu_1092_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln125_fu_1087_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_1_fu_1095_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln137_fu_1109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln137_1_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln137_fu_1119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rail_hits_1_fu_1125_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln160_1_fu_1163_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln160_fu_1173_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal lshr_ln160_1_fu_1179_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln160_fu_1189_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln160_1_fu_1199_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln160_3_fu_1208_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_1166_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln160_1_fu_1193_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln160_1_fu_1212_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln160_fu_1216_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln82_fu_1153_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln160_4_fu_1224_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln153_1_fu_1237_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln153_fu_1234_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln153_fu_1241_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal lshr_ln165_fu_1261_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln163_fu_1270_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal bit_1_fu_1274_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln165_fu_1294_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal remainder_1_fu_1298_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln_fu_1305_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln166_fu_1312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln168_fu_1322_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln166_fu_1335_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal select_ln166_fu_1327_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_fu_1345_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal remainder_2_fu_1317_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_block_pp1 : BOOLEAN;
    signal ap_enable_operation_109 : BOOLEAN;
    signal ap_enable_state4_pp0_iter0_stage0 : BOOLEAN;
    signal ap_enable_operation_127 : BOOLEAN;
    signal ap_enable_state5_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op172_store_state6 : BOOLEAN;
    signal ap_enable_operation_172 : BOOLEAN;
    signal ap_enable_state6_pp0_iter2_stage0 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;

    component median_filter_get_filtered_value_buffer_r IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component median_filter_get_filtered_value_window IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    buffer_r_U : component median_filter_get_filtered_value_buffer_r
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buffer_r_address0,
        ce0 => buffer_r_ce0,
        we0 => buffer_r_we0,
        d0 => newValue,
        q0 => buffer_r_q0);

    window_U : component median_filter_get_filtered_value_window
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => window_address0,
        ce0 => window_ce0,
        we0 => window_we0,
        d0 => out_5_fu_1029_p3,
        q0 => window_q0,
        address1 => window_address1,
        ce1 => window_ce1,
        q1 => window_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter2_state6)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter2_state6))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp1_flush_enable)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv16_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    ap_return_0_preg <= ap_phi_mux_retval_0_phi_fu_333_p8;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv16_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    ap_return_1_preg <= rail_hits_fu_140;
                end if; 
            end if;
        end if;
    end process;


    a_reg_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
                a_reg_284 <= b_3_reg_273;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                a_reg_284 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    b_3_reg_273_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
                b_3_reg_273 <= c_3_reg_263;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                b_3_reg_273 <= window_q1;
            end if; 
        end if;
    end process;

    bit_reg_297_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (tmp_6_reg_1718 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                bit_reg_297 <= add_ln163_reg_1722;
            elsif ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                bit_reg_297 <= ap_const_lv5_16;
            end if; 
        end if;
    end process;

    bufferIndex_loc_0_reg_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                if ((icmp_ln39_fu_406_p2 = ap_const_lv1_0)) then 
                    bufferIndex_loc_0_reg_240 <= ap_const_lv16_0;
                elsif ((icmp_ln39_fu_406_p2 = ap_const_lv1_1)) then 
                    bufferIndex_loc_0_reg_240 <= bufferIndex;
                end if;
            end if; 
        end if;
    end process;

    c_3_reg_263_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
                c_3_reg_263 <= d_reg_1618;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                c_3_reg_263 <= window_q0;
            end if; 
        end if;
    end process;

    i_reg_251_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln82_reg_1563 = ap_const_lv1_0))) then 
                i_reg_251 <= add_ln82_reg_1567;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_reg_251 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    inserted_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln87_reg_1577_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
                inserted_fu_148 <= inserted_2_fu_1007_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                inserted_fu_148 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    med_hi_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln87_reg_1577_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
                med_hi_fu_136 <= med_hi_2_fu_1045_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                med_hi_fu_136 <= newValue;
            end if; 
        end if;
    end process;

    med_lo_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln87_reg_1577_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
                med_lo_fu_128 <= med_lo_3_fu_1038_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                med_lo_fu_128 <= newValue;
            end if; 
        end if;
    end process;

    n_old_reg_228_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                if ((icmp_ln39_fu_406_p2 = ap_const_lv1_0)) then 
                    n_old_reg_228 <= ap_const_lv16_0;
                elsif ((icmp_ln39_fu_406_p2 = ap_const_lv1_1)) then 
                    n_old_reg_228 <= currentWindowSize;
                end if;
            end if; 
        end if;
    end process;

    quotient_reg_319_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (tmp_6_reg_1718 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                quotient_reg_319 <= quotient_1_fu_1355_p3;
            elsif ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                quotient_reg_319 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    rail_hits_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln87_reg_1577_pp0_iter2_reg = ap_const_lv1_1))) then 
                rail_hits_fu_140 <= select_ln137_fu_1131_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                rail_hits_fu_140 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    remainder_reg_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (tmp_6_reg_1718 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                remainder_reg_308 <= remainder_3_fu_1363_p3;
            elsif ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                remainder_reg_308 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    retval_0_reg_330_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                retval_0_reg_330 <= trunc_ln171_fu_1371_p1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (trunc_ln57_reg_1499 = ap_const_lv1_1) and (filter_mode_read_read_fu_164_p2 = ap_const_lv16_1))) then 
                retval_0_reg_330 <= med_lo_2_reg_1657;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (filter_mode_read_read_fu_164_p2 = ap_const_lv16_0))) then 
                retval_0_reg_330 <= newValue;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                retval_0_reg_330 <= add_ln153_fu_1241_p2(16 downto 1);
            end if; 
        end if;
    end process;

    skip_done_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln87_reg_1577_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
                skip_done_fu_144 <= skip_done_3_fu_993_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                skip_done_fu_144 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    sum_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (icmp_ln87_reg_1577_pp0_iter2_reg = ap_const_lv1_1))) then 
                sum_fu_132 <= sum_2_fu_1101_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                sum_fu_132 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                add_ln163_reg_1722 <= add_ln163_fu_1288_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                add_ln82_reg_1567 <= add_ln82_fu_696_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                bufferIndex <= select_ln48_fu_509_p3;
                currentWindowSize <= n_out_fu_523_p3;
                n_out_reg_1493 <= n_out_fu_523_p3;
                removal_reg_1482 <= removal_fu_472_p2;
                sext_ln57_reg_1503 <= sext_ln57_fu_535_p1;
                tmp_3_reg_1515 <= n_out_fu_523_p3(15 downto 15);
                trunc_ln57_reg_1499 <= trunc_ln57_fu_531_p1;
                trunc_ln63_1_reg_1510 <= sub_ln63_fu_539_p2(16 downto 1);
                trunc_ln64_2_reg_1520 <= n_out_fu_523_p3(15 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln87_reg_1577 = ap_const_lv1_1) and (icmp_ln82_reg_1563 = ap_const_lv1_0))) then
                cand_valid_reg_1629 <= cand_valid_fu_852_p3;
                select_ln108_reg_1634 <= select_ln108_fu_858_p3;
                skip_now_2_reg_1645 <= skip_now_2_fu_883_p2;
                skip_now_reg_1623 <= skip_now_fu_847_p2;
                take_new_2_reg_1639 <= take_new_2_fu_872_p2;
                take_new_reg_1651 <= take_new_fu_893_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln82_reg_1563 = ap_const_lv1_0))) then
                d_reg_1618 <= window_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                first_index_reg_1536 <= first_index_fu_646_p3;
                last_index_reg_1542 <= last_index_fu_654_p2;
                mid_hi_reg_1548 <= mid_hi_fu_683_p3;
                mid_lo_reg_1531 <= mid_lo_fu_638_p3;
                oldValue_reg_1525 <= buffer_r_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_reg_251_pp0_iter1_reg <= i_reg_251;
                icmp_ln125_1_reg_1603_pp0_iter1_reg <= icmp_ln125_1_reg_1603;
                icmp_ln125_reg_1598_pp0_iter1_reg <= icmp_ln125_reg_1598;
                icmp_ln128_reg_1608_pp0_iter1_reg <= icmp_ln128_reg_1608;
                icmp_ln131_reg_1613_pp0_iter1_reg <= icmp_ln131_reg_1613;
                icmp_ln82_reg_1563 <= icmp_ln82_fu_690_p2;
                icmp_ln82_reg_1563_pp0_iter1_reg <= icmp_ln82_reg_1563;
                icmp_ln87_reg_1577_pp0_iter1_reg <= icmp_ln87_reg_1577;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln87_fu_747_p2 = ap_const_lv1_1) and (icmp_ln82_fu_690_p2 = ap_const_lv1_0))) then
                icmp_ln125_1_reg_1603 <= icmp_ln125_1_fu_795_p2;
                icmp_ln125_reg_1598 <= icmp_ln125_fu_790_p2;
                icmp_ln128_reg_1608 <= icmp_ln128_fu_800_p2;
                icmp_ln131_reg_1613 <= icmp_ln131_fu_805_p2;
                valid_0_reg_1586 <= valid_0_fu_768_p2;
                valid_m1_reg_1581 <= valid_m1_fu_762_p2;
                valid_p1_reg_1592 <= valid_p1_fu_784_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln125_1_reg_1603_pp0_iter2_reg <= icmp_ln125_1_reg_1603_pp0_iter1_reg;
                icmp_ln125_reg_1598_pp0_iter2_reg <= icmp_ln125_reg_1598_pp0_iter1_reg;
                icmp_ln87_reg_1577_pp0_iter2_reg <= icmp_ln87_reg_1577_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln87_reg_1577_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then
                icmp_ln137_1_reg_1673 <= icmp_ln137_1_fu_1057_p2;
                icmp_ln137_reg_1668 <= icmp_ln137_fu_1052_p2;
                out_5_reg_1663 <= out_5_fu_1029_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln82_fu_690_p2 = ap_const_lv1_0))) then
                icmp_ln87_reg_1577 <= icmp_ln87_fu_747_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                kept_count_reg_1678 <= kept_count_fu_1149_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_406_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                lastWindowSize <= select_ln10_1_fu_386_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                med_lo_2_reg_1657 <= med_lo_fu_128;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                numerator_reg_1697 <= numerator_fu_1228_p2;
                sext_ln160_2_reg_1692 <= sext_ln160_2_fu_1160_p1;
                sext_ln160_reg_1687 <= sext_ln160_fu_1157_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                or_ln166_reg_1727 <= or_ln166_fu_1339_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                select_ln54_reg_1476 <= select_ln54_fu_434_p3;
                    zext_ln24_reg_1411(6 downto 0) <= zext_ln24_fu_394_p1(6 downto 0);
                    zext_ln39_reg_1416(6 downto 0) <= zext_ln39_fu_398_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                tmp_6_reg_1718 <= bit_1_fu_1274_p2(5 downto 5);
                trunc_ln165_1_reg_1712 <= trunc_ln165_1_fu_1266_p1;
                    zext_ln161_reg_1707(4 downto 0) <= zext_ln161_fu_1257_p1(4 downto 0);
            end if;
        end if;
    end process;
    zext_ln24_reg_1411(15 downto 7) <= "000000000";
    zext_ln39_reg_1416(16 downto 7) <= "0000000000";
    zext_ln161_reg_1707(22 downto 5) <= "000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, filter_mode_read_read_fu_164_p2, trunc_ln57_reg_1499, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_state9, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state9) and (trunc_ln57_reg_1499 = ap_const_lv1_0) and (filter_mode_read_read_fu_164_p2 = ap_const_lv16_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    add_ln153_fu_1241_p2 <= std_logic_vector(unsigned(zext_ln153_1_fu_1237_p1) + unsigned(zext_ln153_fu_1234_p1));
    add_ln163_fu_1288_p2 <= std_logic_vector(signed(ap_const_lv5_1F) + signed(ap_phi_mux_bit_phi_fu_301_p4));
    add_ln48_1_fu_503_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(bufferIndex_loc_0_reg_240));
    add_ln48_fu_486_p2 <= std_logic_vector(unsigned(ap_const_lv17_1) + unsigned(sext_ln48_fu_482_p1));
    add_ln51_fu_517_p2 <= std_logic_vector(unsigned(ap_const_lv16_1) + unsigned(n_old_reg_228));
    add_ln63_fu_610_p2 <= std_logic_vector(signed(ap_const_lv17_1FFFF) + signed(sext_ln57_reg_1503));
    add_ln82_fu_696_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_phi_fu_255_p4) + unsigned(ap_const_lv7_1));
    add_ln84_1_fu_728_p2 <= std_logic_vector(unsigned(ap_const_lv6_2) + unsigned(trunc_ln84_fu_702_p1));
    add_ln84_fu_714_p2 <= std_logic_vector(unsigned(ap_const_lv7_2) + unsigned(zext_ln84_1_fu_710_p1));
    add_ln94_fu_752_p2 <= std_logic_vector(unsigned(zext_ln84_1_fu_710_p1) + unsigned(ap_const_lv7_7F));
    add_ln96_fu_774_p2 <= std_logic_vector(unsigned(zext_ln84_1_fu_710_p1) + unsigned(ap_const_lv7_1));
    and_ln106_fu_842_p2 <= (removal_reg_1482 and eq_b_fu_815_p2);
    and_ln111_fu_937_p2 <= (xor_ln111_fu_932_p2 and skip_now_reg_1623);
    and_ln112_fu_966_p2 <= (xor_ln112_fu_960_p2 and inserted_fu_148);
    and_ln113_fu_878_p2 <= (removal_reg_1482 and eq_a_fu_810_p2);
    and_ln125_fu_1087_p2 <= (xor_ln125_fu_1082_p2 and icmp_ln125_1_reg_1603_pp0_iter2_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(7);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(6);
    ap_CS_fsm_state13 <= ap_CS_fsm(8);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state8 <= ap_CS_fsm(4);
    ap_CS_fsm_state9 <= ap_CS_fsm(5);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_assign_proc : process(ap_CS_fsm, ap_block_pp1_stage0_subdone)
    begin
                ap_block_pp1 <= ((ap_const_boolean_1 = ap_block_pp1_stage0_subdone) and (ap_ST_fsm_pp1_stage0 = ap_CS_fsm));
    end process;

        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter2_state6_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter2_state6 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter2_state6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln82_fu_690_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln82_fu_690_p2 = ap_const_lv1_1))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_flush_enable_assign_proc : process(ap_CS_fsm_pp1_stage0, tmp_6_fu_1280_p3, ap_block_pp1_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (tmp_6_fu_1280_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_condition_pp1_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp1_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_operation_109_assign_proc : process(icmp_ln82_fu_690_p2)
    begin
                ap_enable_operation_109 <= (icmp_ln82_fu_690_p2 = ap_const_lv1_0);
    end process;


    ap_enable_operation_127_assign_proc : process(icmp_ln82_reg_1563)
    begin
                ap_enable_operation_127 <= (icmp_ln82_reg_1563 = ap_const_lv1_0);
    end process;


    ap_enable_operation_172_assign_proc : process(ap_predicate_op172_store_state6)
    begin
                ap_enable_operation_172 <= (ap_predicate_op172_store_state6 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_enable_state4_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
                ap_enable_state4_pp0_iter0_stage0 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_enable_state5_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state5_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state6_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state6_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_a_phi_fu_288_p4_assign_proc : process(b_3_reg_273, a_reg_284, icmp_ln82_reg_1563_pp0_iter1_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_a_phi_fu_288_p4 <= b_3_reg_273;
        else 
            ap_phi_mux_a_phi_fu_288_p4 <= a_reg_284;
        end if; 
    end process;


    ap_phi_mux_b_3_phi_fu_276_p4_assign_proc : process(c_3_reg_263, b_3_reg_273, icmp_ln82_reg_1563_pp0_iter1_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_b_3_phi_fu_276_p4 <= c_3_reg_263;
        else 
            ap_phi_mux_b_3_phi_fu_276_p4 <= b_3_reg_273;
        end if; 
    end process;


    ap_phi_mux_bit_phi_fu_301_p4_assign_proc : process(bit_reg_297, ap_CS_fsm_pp1_stage0, tmp_6_reg_1718, add_ln163_reg_1722, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (tmp_6_reg_1718 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_bit_phi_fu_301_p4 <= add_ln163_reg_1722;
        else 
            ap_phi_mux_bit_phi_fu_301_p4 <= bit_reg_297;
        end if; 
    end process;


    ap_phi_mux_c_3_phi_fu_266_p4_assign_proc : process(c_3_reg_263, icmp_ln82_reg_1563_pp0_iter1_reg, d_reg_1618, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_c_3_phi_fu_266_p4 <= d_reg_1618;
        else 
            ap_phi_mux_c_3_phi_fu_266_p4 <= c_3_reg_263;
        end if; 
    end process;


    ap_phi_mux_i_phi_fu_255_p4_assign_proc : process(i_reg_251, ap_CS_fsm_pp0_stage0, icmp_ln82_reg_1563, add_ln82_reg_1567, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln82_reg_1563 = ap_const_lv1_0))) then 
            ap_phi_mux_i_phi_fu_255_p4 <= add_ln82_reg_1567;
        else 
            ap_phi_mux_i_phi_fu_255_p4 <= i_reg_251;
        end if; 
    end process;


    ap_phi_mux_retval_0_phi_fu_333_p8_assign_proc : process(filter_mode_read_read_fu_164_p2, retval_0_reg_330, trunc_ln171_fu_1371_p1, ap_CS_fsm_state13)
    begin
        if ((not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_1)) and not((filter_mode_read_read_fu_164_p2 = ap_const_lv16_0)) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            ap_phi_mux_retval_0_phi_fu_333_p8 <= trunc_ln171_fu_1371_p1;
        else 
            ap_phi_mux_retval_0_phi_fu_333_p8 <= retval_0_reg_330;
        end if; 
    end process;


    ap_predicate_op172_store_state6_assign_proc : process(icmp_ln82_reg_1563_pp0_iter1_reg, icmp_ln87_reg_1577_pp0_iter1_reg)
    begin
                ap_predicate_op172_store_state6 <= ((icmp_ln87_reg_1577_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_phi_mux_retval_0_phi_fu_333_p8, ap_CS_fsm_state13, ap_return_0_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_return_0 <= ap_phi_mux_retval_0_phi_fu_333_p8;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state13, rail_hits_fu_140, ap_return_1_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_return_1 <= rail_hits_fu_140;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;

    bit_1_fu_1274_p2 <= std_logic_vector(signed(ap_const_lv6_3F) + signed(zext_ln163_fu_1270_p1));
    buffer_r_address0 <= zext_ln46_fu_477_p1(6 - 1 downto 0);

    buffer_r_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buffer_r_ce0 <= ap_const_logic_1;
        else 
            buffer_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buffer_r_we0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buffer_r_we0 <= ap_const_logic_1;
        else 
            buffer_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    cand_valid_fu_852_p3 <= 
        valid_p1_reg_1592 when (skip_now_fu_847_p2(0) = '1') else 
        valid_0_reg_1586;
    eq_a_fu_810_p2 <= "1" when (ap_phi_mux_a_phi_fu_288_p4 = oldValue_reg_1525) else "0";
    eq_b_fu_815_p2 <= "1" when (ap_phi_mux_b_3_phi_fu_276_p4 = oldValue_reg_1525) else "0";
    filter_mode_read_read_fu_164_p2 <= filter_mode;
    first_index_fu_646_p3 <= 
        mid_lo_fu_638_p3 when (xor_ln57_fu_604_p2(0) = '1') else 
        zext_ln24_1_fu_585_p1;
    icmp_ln100_fu_820_p2 <= "1" when (unsigned(ap_phi_mux_b_3_phi_fu_276_p4) < unsigned(newValue)) else "0";
    icmp_ln101_fu_831_p2 <= "1" when (unsigned(ap_phi_mux_c_3_phi_fu_266_p4) < unsigned(newValue)) else "0";
    icmp_ln10_fu_360_p2 <= "1" when (signed(window_size) < signed(ap_const_lv16_1)) else "0";
    icmp_ln125_1_fu_795_p2 <= "1" when (signed(zext_ln84_fu_706_p1) < signed(last_index_reg_1542)) else "0";
    icmp_ln125_fu_790_p2 <= "1" when (signed(zext_ln84_fu_706_p1) < signed(first_index_reg_1536)) else "0";
    icmp_ln128_fu_800_p2 <= "1" when (zext_ln84_fu_706_p1 = mid_lo_reg_1531) else "0";
    icmp_ln131_fu_805_p2 <= "1" when (zext_ln84_fu_706_p1 = mid_hi_reg_1548) else "0";
    icmp_ln137_1_fu_1057_p2 <= "1" when (unsigned(out_5_fu_1029_p3) < unsigned(rail_high)) else "0";
    icmp_ln137_fu_1052_p2 <= "1" when (unsigned(rail_low) < unsigned(out_5_fu_1029_p3)) else "0";
    icmp_ln13_fu_366_p2 <= "1" when (signed(window_size) > signed(ap_const_lv16_40)) else "0";
    icmp_ln166_fu_1312_p2 <= "1" when (unsigned(remainder_1_fu_1298_p3) < unsigned(sext_ln160_reg_1687)) else "0";
    icmp_ln39_fu_406_p2 <= "1" when (select_ln10_1_fu_386_p3 = lastWindowSize) else "0";
    icmp_ln48_fu_492_p2 <= "1" when (signed(add_ln48_fu_486_p2) < signed(zext_ln39_reg_1416)) else "0";
    icmp_ln57_fu_599_p2 <= "1" when (signed(zext_ln57_fu_595_p1) < signed(sext_ln57_reg_1503)) else "0";
    icmp_ln82_fu_690_p2 <= "1" when (ap_phi_mux_i_phi_fu_255_p4 = ap_const_lv7_40) else "0";
    icmp_ln87_fu_747_p2 <= "1" when (signed(zext_ln84_fu_706_p1) < signed(n_out_reg_1493)) else "0";
    inserted_2_fu_1007_p2 <= (select_ln104_fu_1001_p3 or inserted_fu_148);
    kept_count_fu_1149_p2 <= std_logic_vector(unsigned(last_index_reg_1542) - unsigned(first_index_reg_1536));
    last_index_fu_654_p2 <= std_logic_vector(signed(n_out_reg_1493) - signed(first_index_fu_646_p3));
    le_b_fu_825_p2 <= (icmp_ln100_fu_820_p2 xor ap_const_lv1_1);
    le_c_fu_836_p2 <= (icmp_ln101_fu_831_p2 xor ap_const_lv1_1);
    lshr_ln160_1_fu_1179_p4 <= sub_ln160_fu_1173_p2(16 downto 1);
    lshr_ln165_fu_1261_p2 <= std_logic_vector(shift_right(unsigned(numerator_reg_1697),to_integer(unsigned('0' & zext_ln161_fu_1257_p1(23-1 downto 0)))));
    med_hi_2_fu_1045_p3 <= 
        out_5_fu_1029_p3 when (icmp_ln131_reg_1613_pp0_iter1_reg(0) = '1') else 
        med_hi_fu_136;
    med_lo_3_fu_1038_p3 <= 
        out_5_fu_1029_p3 when (icmp_ln128_reg_1608_pp0_iter1_reg(0) = '1') else 
        med_lo_fu_128;
    mid_hi_fu_683_p3 <= 
        sub_ln64_1_fu_677_p2 when (tmp_3_reg_1515(0) = '1') else 
        sext_ln64_fu_674_p1;
    mid_lo_fu_638_p3 <= 
        sub_ln63_1_fu_623_p2 when (tmp_2_fu_615_p3(0) = '1') else 
        trunc_ln63_2_fu_628_p4;
    n_out_fu_523_p3 <= 
        n_old_reg_228 when (removal_fu_472_p2(0) = '1') else 
        add_ln51_fu_517_p2;
    newSel31_fu_985_p3 <= 
        skip_done_fu_144 when (or_ln104_fu_913_p2(0) = '1') else 
        skip_done_1_fu_942_p2;
    newSel_fu_978_p3 <= 
        skip_done_fu_144 when (sel_tmp6_fu_972_p2(0) = '1') else 
        skip_now_2_reg_1645;
    numerator_fu_1228_p2 <= std_logic_vector(unsigned(trunc_ln82_fu_1153_p1) + unsigned(sext_ln160_4_fu_1224_p1));
    or_ln104_fu_913_p2 <= (skip_done_fu_144 or inserted_fu_148);
    or_ln10_fu_380_p2 <= (icmp_ln13_fu_366_p2 or icmp_ln10_fu_360_p2);
    or_ln137_fu_1119_p2 <= (xor_ln137_fu_1109_p2 or xor_ln137_1_fu_1114_p2);
    or_ln166_fu_1339_p2 <= (trunc_ln166_fu_1335_p1 or select_ln166_fu_1327_p3);
    or_ln_fu_1305_p3 <= (trunc_ln165_fu_1294_p1 & trunc_ln165_1_reg_1712);
    out_1_fu_947_p3 <= 
        b_3_reg_273 when (skip_now_2_reg_1645(0) = '1') else 
        a_reg_284;
    out_2_fu_1013_p3 <= 
        select_ln118_fu_954_p3 when (or_ln104_fu_913_p2(0) = '1') else 
        out_fu_926_p3;
    out_3_fu_1021_p3 <= 
        out_1_fu_947_p3 when (and_ln112_fu_966_p2(0) = '1') else 
        out_2_fu_1013_p3;
    out_5_fu_1029_p3 <= 
        b_3_reg_273 when (sel_tmp6_fu_972_p2(0) = '1') else 
        out_3_fu_1021_p3;
    out_fu_926_p3 <= 
        newValue when (take_new_2_reg_1639(0) = '1') else 
        select_ln109_fu_919_p3;
    prefetch_idx_fu_734_p3 <= 
        ap_const_lv6_3F when (tmp_4_fu_720_p3(0) = '1') else 
        add_ln84_1_fu_728_p2;
    quotient_1_fu_1355_p3 <= (tmp_fu_1345_p4 & or_ln166_fu_1339_p2);
    rail_hits_1_fu_1125_p2 <= std_logic_vector(unsigned(rail_hits_fu_140) + unsigned(ap_const_lv16_1));
    remainder_1_fu_1298_p3 <= (remainder_reg_308 & trunc_ln165_1_reg_1712);
    remainder_2_fu_1317_p2 <= std_logic_vector(unsigned(or_ln_fu_1305_p3) - unsigned(sext_ln160_2_reg_1692));
    remainder_3_fu_1363_p3 <= 
        or_ln_fu_1305_p3 when (icmp_ln166_fu_1312_p2(0) = '1') else 
        remainder_2_fu_1317_p2;
    removal_fu_472_p2 <= "1" when (n_old_reg_228 = zext_ln24_reg_1411) else "0";
    sel_tmp6_fu_972_p2 <= (skip_done_fu_144 and inserted_fu_148);
    select_ln104_fu_1001_p3 <= 
        take_new_reg_1651 when (or_ln104_fu_913_p2(0) = '1') else 
        take_new_2_reg_1639;
    select_ln108_fu_858_p3 <= 
        le_c_fu_836_p2 when (skip_now_fu_847_p2(0) = '1') else 
        le_b_fu_825_p2;
    select_ln109_fu_919_p3 <= 
        c_3_reg_263 when (skip_now_reg_1623(0) = '1') else 
        b_3_reg_273;
    select_ln10_1_fu_386_p3 <= 
        select_ln10_fu_372_p3 when (or_ln10_fu_380_p2(0) = '1') else 
        trunc_ln24_1_fu_356_p1;
    select_ln10_fu_372_p3 <= 
        ap_const_lv7_1 when (icmp_ln10_fu_360_p2(0) = '1') else 
        ap_const_lv7_40;
    select_ln118_fu_954_p3 <= 
        newValue when (take_new_reg_1651(0) = '1') else 
        c_3_reg_263;
    select_ln137_fu_1131_p3 <= 
        rail_hits_1_fu_1125_p2 when (or_ln137_fu_1119_p2(0) = '1') else 
        rail_hits_fu_140;
    select_ln160_fu_1216_p3 <= 
        sub_ln160_1_fu_1193_p2 when (tmp_5_fu_1166_p3(0) = '1') else 
        zext_ln160_1_fu_1212_p1;
    select_ln166_fu_1327_p3 <= 
        ap_const_lv23_0 when (icmp_ln166_fu_1312_p2(0) = '1') else 
        shl_ln168_fu_1322_p2;
    select_ln48_fu_509_p3 <= 
        ap_const_lv16_0 when (xor_ln48_fu_497_p2(0) = '1') else 
        add_ln48_1_fu_503_p2;
    select_ln54_fu_434_p3 <= 
        ap_const_lv15_0 when (tmp_1_fu_426_p3(0) = '1') else 
        trunc_ln24_fu_352_p1;
        sext_ln160_1_fu_1163_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(kept_count_reg_1678),17));

        sext_ln160_2_fu_1160_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(kept_count_reg_1678),31));

        sext_ln160_3_fu_1208_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln160_1_fu_1199_p4),16));

        sext_ln160_4_fu_1224_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln160_fu_1216_p3),23));

        sext_ln160_fu_1157_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(kept_count_reg_1678),32));

        sext_ln48_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bufferIndex_loc_0_reg_240),17));

        sext_ln57_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(n_out_fu_523_p3),17));

        sext_ln64_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln64_2_reg_1520),16));

        sext_ln94_fu_758_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln94_fu_752_p2),16));

    shl_ln168_fu_1322_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv23_1),to_integer(unsigned('0' & zext_ln161_reg_1707(23-1 downto 0)))));
    shl_ln_fu_588_p3 <= (select_ln54_reg_1476 & ap_const_lv1_0);
    skip_done_1_fu_942_p2 <= (cand_valid_reg_1629 and and_ln111_fu_937_p2);
    skip_done_3_fu_993_p3 <= 
        newSel_fu_978_p3 when (inserted_fu_148(0) = '1') else 
        newSel31_fu_985_p3;
    skip_now_2_fu_883_p2 <= (valid_m1_reg_1581 and and_ln113_fu_878_p2);
    skip_now_fu_847_p2 <= (valid_0_reg_1586 and and_ln106_fu_842_p2);
    sub_ln160_1_fu_1193_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(zext_ln160_fu_1189_p1));
    sub_ln160_fu_1173_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln160_1_fu_1163_p1));
    sub_ln63_1_fu_623_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln63_1_reg_1510));
    sub_ln63_fu_539_p2 <= std_logic_vector(unsigned(ap_const_lv17_1) - unsigned(sext_ln57_fu_535_p1));
    sub_ln64_1_fu_677_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln64_1_fu_664_p4));
    sub_ln64_fu_659_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln57_reg_1503));
    sum_1_fu_1095_p2 <= std_logic_vector(unsigned(sum_fu_132) + unsigned(zext_ln126_fu_1092_p1));
    sum_2_fu_1101_p3 <= 
        sum_1_fu_1095_p2 when (and_ln125_fu_1087_p2(0) = '1') else 
        sum_fu_132;
    take_new_2_fu_872_p2 <= (xor_ln108_fu_866_p2 or select_ln108_fu_858_p3);
    take_new_fu_893_p2 <= (xor_ln117_fu_888_p2 or le_c_fu_836_p2);
    tmp_1_fu_426_p3 <= trim_count(15 downto 15);
    tmp_2_fu_615_p3 <= add_ln63_fu_610_p2(16 downto 16);
    tmp_4_fu_720_p3 <= add_ln84_fu_714_p2(6 downto 6);
    tmp_5_fu_1166_p3 <= kept_count_reg_1678(15 downto 15);
    tmp_6_fu_1280_p3 <= bit_1_fu_1274_p2(5 downto 5);
    tmp_fu_1345_p4 <= quotient_reg_319(31 downto 23);
    trunc_ln160_1_fu_1199_p4 <= kept_count_reg_1678(15 downto 1);
    trunc_ln165_1_fu_1266_p1 <= lshr_ln165_fu_1261_p2(1 - 1 downto 0);
    trunc_ln165_fu_1294_p1 <= remainder_reg_308(30 - 1 downto 0);
    trunc_ln166_fu_1335_p1 <= quotient_reg_319(23 - 1 downto 0);
    trunc_ln171_fu_1371_p1 <= or_ln166_reg_1727(16 - 1 downto 0);
    trunc_ln24_1_fu_356_p1 <= window_size(7 - 1 downto 0);
    trunc_ln24_fu_352_p1 <= trim_count(15 - 1 downto 0);
    trunc_ln57_fu_531_p1 <= n_out_fu_523_p3(1 - 1 downto 0);
    trunc_ln63_2_fu_628_p4 <= add_ln63_fu_610_p2(16 downto 1);
    trunc_ln64_1_fu_664_p4 <= sub_ln64_fu_659_p2(16 downto 1);
    trunc_ln82_fu_1153_p1 <= sum_fu_132(23 - 1 downto 0);
    trunc_ln84_fu_702_p1 <= ap_phi_mux_i_phi_fu_255_p4(6 - 1 downto 0);
    valid_0_fu_768_p2 <= "1" when (signed(zext_ln84_fu_706_p1) < signed(n_old_reg_228)) else "0";
    valid_m1_fu_762_p2 <= "1" when (signed(sext_ln94_fu_758_p1) < signed(n_old_reg_228)) else "0";
    valid_p1_fu_784_p2 <= "1" when (signed(zext_ln96_fu_780_p1) < signed(n_old_reg_228)) else "0";

    window_address0_assign_proc : process(ap_CS_fsm_state2, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, zext_ln82_fu_902_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            window_address0 <= zext_ln82_fu_902_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            window_address0 <= ap_const_lv6_1;
        else 
            window_address0 <= "XXXXXX";
        end if; 
    end process;


    window_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_state2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, zext_ln85_fu_742_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            window_address1 <= zext_ln85_fu_742_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            window_address1 <= ap_const_lv6_0;
        else 
            window_address1 <= "XXXXXX";
        end if; 
    end process;


    window_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_CS_fsm_state2, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            window_ce0 <= ap_const_logic_1;
        else 
            window_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    window_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_state2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then 
            window_ce1 <= ap_const_logic_1;
        else 
            window_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    window_we0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln82_reg_1563_pp0_iter1_reg, icmp_ln87_reg_1577_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln87_reg_1577_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln82_reg_1563_pp0_iter1_reg = ap_const_lv1_0))) then 
            window_we0 <= ap_const_logic_1;
        else 
            window_we0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln108_fu_866_p2 <= (cand_valid_fu_852_p3 xor ap_const_lv1_1);
    xor_ln111_fu_932_p2 <= (select_ln108_reg_1634 xor ap_const_lv1_1);
    xor_ln112_fu_960_p2 <= (skip_done_fu_144 xor ap_const_lv1_1);
    xor_ln117_fu_888_p2 <= (valid_p1_reg_1592 xor ap_const_lv1_1);
    xor_ln125_fu_1082_p2 <= (icmp_ln125_reg_1598_pp0_iter2_reg xor ap_const_lv1_1);
    xor_ln137_1_fu_1114_p2 <= (icmp_ln137_1_reg_1673 xor ap_const_lv1_1);
    xor_ln137_fu_1109_p2 <= (icmp_ln137_reg_1668 xor ap_const_lv1_1);
    xor_ln48_fu_497_p2 <= (icmp_ln48_fu_492_p2 xor ap_const_lv1_1);
    xor_ln57_fu_604_p2 <= (icmp_ln57_fu_599_p2 xor ap_const_lv1_1);
    zext_ln126_fu_1092_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_5_reg_1663),32));
    zext_ln153_1_fu_1237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(med_hi_fu_136),17));
    zext_ln153_fu_1234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(med_lo_2_reg_1657),17));
    zext_ln160_1_fu_1212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln160_3_fu_1208_p1),17));
    zext_ln160_fu_1189_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln160_1_fu_1179_p4),17));
    zext_ln161_fu_1257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_bit_phi_fu_301_p4),23));
    zext_ln163_fu_1270_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_bit_phi_fu_301_p4),6));
    zext_ln24_1_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln54_reg_1476),16));
    zext_ln24_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_1_fu_386_p3),16));
    zext_ln39_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_1_fu_386_p3),17));
    zext_ln46_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bufferIndex_loc_0_reg_240),64));
    zext_ln57_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_588_p3),17));
    zext_ln82_fu_902_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_251_pp0_iter1_reg),64));
    zext_ln84_1_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln84_fu_702_p1),7));
    zext_ln84_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln84_fu_702_p1),16));
    zext_ln85_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(prefetch_idx_fu_734_p3),64));
    zext_ln96_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln96_fu_774_p2),16));
end behav;
