-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity secloc_gate_secloc_gate_handle_transaction is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    req_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    req_in_TVALID : IN STD_LOGIC;
    req_in_TREADY : OUT STD_LOGIC;
    req_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    req_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    req_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    resp_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    resp_out_TVALID : OUT STD_LOGIC;
    resp_out_TREADY : IN STD_LOGIC;
    resp_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    resp_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    resp_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    marshal_req_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    marshal_req_TVALID : OUT STD_LOGIC;
    marshal_req_TREADY : IN STD_LOGIC;
    marshal_req_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    marshal_req_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    marshal_req_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    marshal_resp_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    marshal_resp_TVALID : IN STD_LOGIC;
    marshal_resp_TREADY : OUT STD_LOGIC;
    marshal_resp_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    marshal_resp_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    marshal_resp_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of secloc_gate_secloc_gate_handle_transaction is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (21 downto 0) := "0000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (21 downto 0) := "0000000010000000000000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000100000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (21 downto 0) := "0000001000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (21 downto 0) := "0000010000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (21 downto 0) := "0000100000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (21 downto 0) := "0001000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (21 downto 0) := "0010000000000000000000";
    constant ap_ST_fsm_pp3_stage0 : STD_LOGIC_VECTOR (21 downto 0) := "0100000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (21 downto 0) := "1000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_38D1B717 : STD_LOGIC_VECTOR (31 downto 0) := "00111000110100011011011100010111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv26_200000C : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000001100";
    constant ap_const_lv26_2000001 : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000000001";
    constant ap_const_lv26_2000004 : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000000100";
    constant ap_const_lv26_2000000 : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000000000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv64_C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001100";
    constant ap_const_lv64_D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001101";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001011";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv26_2 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000010";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal updates : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal gate_state_0 : STD_LOGIC_VECTOR (31 downto 0) := "00111000110100011011011100010111";
    signal gate_state_1 : STD_LOGIC_VECTOR (31 downto 0) := "00111000110100011011011100010111";
    signal gate_state_2 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    signal held_Q : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal req_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln38_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal resp_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp3_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp3_stage0 : signal is "none";
    signal ap_enable_reg_pp3_iter1 : STD_LOGIC := '0';
    signal ap_block_pp3_stage0 : BOOLEAN;
    signal icmp_ln53_1_reg_1126 : STD_LOGIC_VECTOR (0 downto 0);
    signal marshal_req_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln85_reg_1071 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_reg_456 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_2_reg_572 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln38_fu_628_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal req_words_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal control_flags_reg_903 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln141_fu_644_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln141_reg_908 : STD_LOGIC_VECTOR (0 downto 0);
    signal req_words_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tick_reg_912 : STD_LOGIC_VECTOR (31 downto 0);
    signal words_V_load_reg_929 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal words_V_load_1_reg_934 : STD_LOGIC_VECTOR (31 downto 0);
    signal words_V_load_2_reg_950 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal words_V_load_3_reg_956 : STD_LOGIC_VECTOR (31 downto 0);
    signal words_V_load_4_reg_972 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal gate_cfg_ref_period_ticks_reg_977 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_fu_648_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_reg_994 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal value_1_fu_651_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_1_reg_999 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_2_fu_654_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_2_reg_1004 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_3_fu_657_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_3_reg_1009 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_4_fu_660_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_4_reg_1014 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_5_fu_663_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_5_reg_1019 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_6_fu_667_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal value_6_reg_1024 : STD_LOGIC_VECTOR (31 downto 0);
    signal updates_load_reg_1029 : STD_LOGIC_VECTOR (31 downto 0);
    signal force_fu_675_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal force_reg_1036 : STD_LOGIC_VECTOR (0 downto 0);
    signal gate_eval_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal gate_eval_reg_1041 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_gate_should_sample_fu_603_ap_return : STD_LOGIC_VECTOR (0 downto 0);
    signal fire_reg_1047 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_gate_should_sample_fu_603_ap_ready : STD_LOGIC;
    signal grp_gate_should_sample_fu_603_ap_done : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal icmp_ln85_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state15_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state16_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_state16_io : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal add_ln85_fu_768_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal last_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_reg_1080 : STD_LOGIC_VECTOR (0 downto 0);
    signal wait_cycles_2_fu_791_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal resp_data_V_reg_1101 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln190_fu_814_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal zext_ln156_fu_851_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln156_reg_1111 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal zext_ln156_1_fu_855_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln156_1_reg_1116 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_18_fu_863_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_18_reg_1121 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln53_1_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state22_pp3_stage0_iter0 : BOOLEAN;
    signal ap_block_state23_pp3_stage0_iter1 : BOOLEAN;
    signal ap_block_state23_io : BOOLEAN;
    signal ap_block_pp3_stage0_11001 : BOOLEAN;
    signal i_3_fu_873_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_3_reg_1130 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp3_iter0 : STD_LOGIC := '0';
    signal last_1_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_1_reg_1135 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state15 : STD_LOGIC;
    signal ap_block_pp3_stage0_subdone : BOOLEAN;
    signal ap_condition_pp3_exit_iter0_state22 : STD_LOGIC;
    signal req_words_V_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal req_words_V_ce0 : STD_LOGIC;
    signal req_words_V_we0 : STD_LOGIC;
    signal req_words_V_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal req_words_V_ce1 : STD_LOGIC;
    signal marshal_inputs_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal marshal_inputs_V_ce0 : STD_LOGIC;
    signal marshal_inputs_V_we0 : STD_LOGIC;
    signal marshal_inputs_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal marshal_inputs_V_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal marshal_inputs_V_ce1 : STD_LOGIC;
    signal marshal_inputs_V_we1 : STD_LOGIC;
    signal marshal_inputs_V_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal marshal_inputs_V_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gate_should_sample_fu_603_ap_start : STD_LOGIC;
    signal grp_gate_should_sample_fu_603_ap_idle : STD_LOGIC;
    signal grp_gate_should_sample_fu_603_gate_state_2_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gate_should_sample_fu_603_gate_state_2_o_ap_vld : STD_LOGIC;
    signal grp_gate_should_sample_fu_603_gate_state_0_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gate_should_sample_fu_603_gate_state_0_o_ap_vld : STD_LOGIC;
    signal grp_gate_should_sample_fu_603_gate_state_1_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gate_should_sample_fu_603_gate_state_1_o_ap_vld : STD_LOGIC;
    signal i_reg_433 : STD_LOGIC_VECTOR (3 downto 0);
    signal gate_eval_0201_reg_444 : STD_LOGIC_VECTOR (0 downto 0);
    signal wait_cycles_reg_467 : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_n_1_fu_797_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal updates_loc_0_reg_479 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal gate_eval_0200_reg_490 : STD_LOGIC_VECTOR (0 downto 0);
    signal wait_cycles_1_reg_503 : STD_LOGIC_VECTOR (12 downto 0);
    signal status_word_reg_519 : STD_LOGIC_VECTOR (25 downto 0);
    signal updates_assign_reg_536 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_wait_cycles_3_phi_fu_553_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal wait_cycles_3_reg_549 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln199_fu_842_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_phi_mux_status_word_2_phi_fu_565_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal status_word_2_reg_561 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_phi_mux_i_2_phi_fu_576_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp3_iter0_data_V_1_reg_584 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp3_iter1_data_V_1_reg_584 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_gate_should_sample_fu_603_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal zext_ln38_fu_634_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln85_fu_774_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal value_7_fu_805_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal grp_nbread_fu_200_p5_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp3_stage0_01001 : BOOLEAN;
    signal or_ln39_fu_691_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_696_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln53_fu_710_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln53_fu_715_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln39_1_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln53_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln199_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln199_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal status_word_1_fu_836_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_idle_pp3 : STD_LOGIC;
    signal ap_enable_pp3 : STD_LOGIC;
    signal ap_condition_490 : BOOLEAN;
    signal ap_condition_327 : BOOLEAN;

    component secloc_gate_gate_should_sample IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
        p : IN STD_LOGIC_VECTOR (31 downto 0);
        a : IN STD_LOGIC_VECTOR (31 downto 0);
        tp : IN STD_LOGIC_VECTOR (31 downto 0);
        te : IN STD_LOGIC_VECTOR (31 downto 0);
        tick : IN STD_LOGIC_VECTOR (31 downto 0);
        gate_state_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
        gate_state_2_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        gate_state_2_o_ap_vld : OUT STD_LOGIC;
        gate_state_0_i : IN STD_LOGIC_VECTOR (31 downto 0);
        gate_state_0_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        gate_state_0_o_ap_vld : OUT STD_LOGIC;
        gate_state_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
        gate_state_1_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        gate_state_1_o_ap_vld : OUT STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component secloc_gate_secloc_gate_handle_transaction_req_words_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component secloc_gate_secloc_gate_handle_transaction_marshal_inputs_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    req_words_V_U : component secloc_gate_secloc_gate_handle_transaction_req_words_V
    generic map (
        DataWidth => 32,
        AddressRange => 14,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => req_words_V_address0,
        ce0 => req_words_V_ce0,
        we0 => req_words_V_we0,
        d0 => req_in_TDATA,
        q0 => req_words_V_q0,
        address1 => req_words_V_address1,
        ce1 => req_words_V_ce1,
        q1 => req_words_V_q1);

    marshal_inputs_V_U : component secloc_gate_secloc_gate_handle_transaction_marshal_inputs_V
    generic map (
        DataWidth => 32,
        AddressRange => 7,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => marshal_inputs_V_address0,
        ce0 => marshal_inputs_V_ce0,
        we0 => marshal_inputs_V_we0,
        d0 => marshal_inputs_V_d0,
        address1 => marshal_inputs_V_address1,
        ce1 => marshal_inputs_V_ce1,
        we1 => marshal_inputs_V_we1,
        d1 => marshal_inputs_V_d1,
        q1 => marshal_inputs_V_q1);

    grp_gate_should_sample_fu_603 : component secloc_gate_gate_should_sample
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_gate_should_sample_fu_603_ap_start,
        ap_done => grp_gate_should_sample_fu_603_ap_done,
        ap_idle => grp_gate_should_sample_fu_603_ap_idle,
        ap_ready => grp_gate_should_sample_fu_603_ap_ready,
        p_read => value_4_reg_1014,
        p_read1 => gate_cfg_ref_period_ticks_reg_977,
        p_read2 => value_5_reg_1019,
        p_read3 => value_6_reg_1024,
        p => value_1_reg_999,
        a => value_reg_994,
        tp => value_3_reg_1009,
        te => value_2_reg_1004,
        tick => tick_reg_912,
        gate_state_2_i => gate_state_2,
        gate_state_2_o => grp_gate_should_sample_fu_603_gate_state_2_o,
        gate_state_2_o_ap_vld => grp_gate_should_sample_fu_603_gate_state_2_o_ap_vld,
        gate_state_0_i => gate_state_0,
        gate_state_0_o => grp_gate_should_sample_fu_603_gate_state_0_o,
        gate_state_0_o_ap_vld => grp_gate_should_sample_fu_603_gate_state_0_o_ap_vld,
        gate_state_1_i => gate_state_1,
        gate_state_1_o => grp_gate_should_sample_fu_603_gate_state_1_o,
        gate_state_1_o_ap_vld => grp_gate_should_sample_fu_603_gate_state_1_o_ap_vld,
        ap_return => grp_gate_should_sample_fu_603_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state15) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state15))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state15);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0) and (ap_const_logic_1 = ap_condition_pp3_exit_iter0_state22))) then 
                    ap_enable_reg_pp3_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                    ap_enable_reg_pp3_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp3_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp3_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp3_exit_iter0_state22))) then 
                    ap_enable_reg_pp3_iter1 <= (ap_const_logic_1 xor ap_condition_pp3_exit_iter0_state22);
                elsif ((ap_const_boolean_0 = ap_block_pp3_stage0_subdone)) then 
                    ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                    ap_enable_reg_pp3_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_gate_should_sample_fu_603_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_gate_should_sample_fu_603_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_gate_should_sample_fu_603_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_gate_should_sample_fu_603_ap_ready = ap_const_logic_1)) then 
                    grp_gate_should_sample_fu_603_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp3_iter1_data_V_1_reg_584_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_327)) then
                if (((ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_1) and (icmp_ln53_1_fu_867_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp3_iter1_data_V_1_reg_584 <= zext_ln156_reg_1111;
                elsif (((ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_0) and (icmp_ln53_1_fu_867_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp3_iter1_data_V_1_reg_584 <= empty_18_reg_1121;
                elsif (((ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_2) and (icmp_ln53_1_fu_867_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp3_iter1_data_V_1_reg_584 <= updates_assign_reg_536;
                elsif (((ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_3) and (icmp_ln53_1_fu_867_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp3_iter1_data_V_1_reg_584 <= zext_ln156_1_reg_1116;
                elsif ((ap_const_boolean_1 = ap_condition_490)) then 
                    ap_phi_reg_pp3_iter1_data_V_1_reg_584 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp3_iter1_data_V_1_reg_584 <= ap_phi_reg_pp3_iter0_data_V_1_reg_584;
                end if;
            end if; 
        end if;
    end process;

    gate_eval_0200_reg_490_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((fire_reg_1047 = ap_const_lv1_0) and (force_reg_1036 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                gate_eval_0200_reg_490 <= gate_eval_reg_1041;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19))) then 
                gate_eval_0200_reg_490 <= gate_eval_0201_reg_444;
            end if; 
        end if;
    end process;

    gate_eval_0201_reg_444_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((fire_reg_1047 = ap_const_lv1_1) and (force_reg_1036 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                gate_eval_0201_reg_444 <= gate_eval_reg_1041;
            elsif (((force_fu_675_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then 
                gate_eval_0201_reg_444 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    gate_state_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then 
                gate_state_0 <= ap_const_lv32_38D1B717;
            elsif (((grp_gate_should_sample_fu_603_gate_state_0_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                gate_state_0 <= grp_gate_should_sample_fu_603_gate_state_0_o;
            end if; 
        end if;
    end process;

    gate_state_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then 
                gate_state_1 <= ap_const_lv32_38D1B717;
            elsif (((grp_gate_should_sample_fu_603_gate_state_1_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                gate_state_1 <= grp_gate_should_sample_fu_603_gate_state_1_o;
            end if; 
        end if;
    end process;

    gate_state_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then 
                gate_state_2 <= ap_const_lv32_FFFFFFFF;
            elsif (((grp_gate_should_sample_fu_603_gate_state_2_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                gate_state_2 <= grp_gate_should_sample_fu_603_gate_state_2_o;
            end if; 
        end if;
    end process;

    held_Q_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                held_Q <= value_7_fu_805_p1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then 
                held_Q <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_1_reg_456_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                i_1_reg_456 <= ap_const_lv3_0;
            elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln85_fu_762_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                i_1_reg_456 <= add_ln85_fu_768_p2;
            end if; 
        end if;
    end process;

    i_2_reg_572_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_1_reg_1126 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
                i_2_reg_572 <= i_3_reg_1130;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                i_2_reg_572 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    i_reg_433_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_433 <= ap_const_lv4_0;
            elsif ((not(((icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (req_in_TVALID = ap_const_logic_0))) and (icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_reg_433 <= add_ln38_fu_628_p2;
            end if; 
        end if;
    end process;

    status_word_2_reg_561_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then 
                status_word_2_reg_561(0) <= '0';
                status_word_2_reg_561(1) <= '0';
                status_word_2_reg_561(2) <= '0';
                status_word_2_reg_561(3) <= '0';
            elsif (((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then 
                                status_word_2_reg_561(3 downto 0) <= select_ln199_fu_842_p3(3 downto 0);
            end if; 
        end if;
    end process;

    status_word_reg_519_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((fire_reg_1047 = ap_const_lv1_0) and (force_reg_1036 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                status_word_reg_519(0) <= '0';
                status_word_reg_519(2) <= '1';
                status_word_reg_519(3) <= '0';
            elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                status_word_reg_519(0) <= '1';
                status_word_reg_519(2) <= '0';
                status_word_reg_519(3) <= '0';
            elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                status_word_reg_519(0) <= '0';
                status_word_reg_519(2) <= '1';
                status_word_reg_519(3) <= '1';
            end if; 
        end if;
    end process;

    updates_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                updates <= add_ln190_fu_814_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then 
                updates <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    updates_assign_reg_536_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then 
                updates_assign_reg_536 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then 
                updates_assign_reg_536 <= updates_loc_0_reg_479;
            end if; 
        end if;
    end process;

    updates_loc_0_reg_479_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                updates_loc_0_reg_479 <= add_ln190_fu_814_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state20) or ((fire_reg_1047 = ap_const_lv1_0) and (force_reg_1036 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
                updates_loc_0_reg_479 <= updates_load_reg_1029;
            end if; 
        end if;
    end process;

    wait_cycles_1_reg_503_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((fire_reg_1047 = ap_const_lv1_0) and (force_reg_1036 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                wait_cycles_1_reg_503 <= ap_const_lv13_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                wait_cycles_1_reg_503 <= wait_cycles_reg_467;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                wait_cycles_1_reg_503 <= ap_const_lv13_1000;
            end if; 
        end if;
    end process;

    wait_cycles_3_reg_549_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then 
                wait_cycles_3_reg_549 <= ap_const_lv13_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then 
                wait_cycles_3_reg_549 <= wait_cycles_1_reg_503;
            end if; 
        end if;
    end process;

    wait_cycles_reg_467_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
                wait_cycles_reg_467 <= ap_const_lv13_0;
            elsif (((empty_n_1_fu_797_p1 = ap_const_lv1_0) and (icmp_ln102_fu_785_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
                wait_cycles_reg_467 <= wait_cycles_2_fu_791_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                control_flags_reg_903 <= req_words_V_q1;
                tick_reg_912 <= req_words_V_q0;
                trunc_ln141_reg_908 <= trunc_ln141_fu_644_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                empty_18_reg_1121 <= empty_18_fu_863_p1;
                    zext_ln156_1_reg_1116(12 downto 0) <= zext_ln156_1_fu_855_p1(12 downto 0);
                    zext_ln156_reg_1111(3 downto 0) <= zext_ln156_fu_851_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_gate_should_sample_fu_603_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                fire_reg_1047 <= grp_gate_should_sample_fu_603_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then
                force_reg_1036 <= control_flags_reg_903(1 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                gate_cfg_ref_period_ticks_reg_977 <= req_words_V_q1;
                words_V_load_4_reg_972 <= req_words_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((force_fu_675_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then
                gate_eval_reg_1041 <= gate_eval_fu_726_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                i_3_reg_1130 <= i_3_fu_873_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                icmp_ln53_1_reg_1126 <= icmp_ln53_1_fu_867_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln85_reg_1071 <= icmp_ln85_fu_762_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (icmp_ln53_1_fu_867_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then
                last_1_reg_1135 <= last_1_fu_879_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln85_fu_762_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                last_reg_1080 <= last_fu_779_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln102_fu_785_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                resp_data_V_reg_1101 <= marshal_resp_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                updates_load_reg_1029 <= updates;
                value_1_reg_999 <= value_1_fu_651_p1;
                value_2_reg_1004 <= value_2_fu_654_p1;
                value_3_reg_1009 <= value_3_fu_657_p1;
                value_4_reg_1014 <= value_4_fu_660_p1;
                value_5_reg_1019 <= value_5_fu_663_p1;
                value_6_reg_1024 <= value_6_fu_667_p1;
                value_reg_994 <= value_fu_648_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                words_V_load_1_reg_934 <= req_words_V_q1;
                words_V_load_reg_929 <= req_words_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                words_V_load_2_reg_950 <= req_words_V_q0;
                words_V_load_3_reg_956 <= req_words_V_q1;
            end if;
        end if;
    end process;
    zext_ln156_reg_1111(31 downto 4) <= "0000001000000000000000000000";
    zext_ln156_1_reg_1116(31 downto 13) <= "0000000000000000000";
    status_word_reg_519(1) <= '0';
    status_word_reg_519(25 downto 4) <= "1000000000000000000000";
    status_word_2_reg_561(25 downto 4) <= "1000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, req_in_TVALID, ap_CS_fsm_state2, icmp_ln38_fu_622_p2, trunc_ln141_reg_908, ap_CS_fsm_state8, force_fu_675_p3, force_reg_1036, fire_reg_1047, ap_CS_fsm_state10, grp_gate_should_sample_fu_603_ap_done, ap_CS_fsm_state11, icmp_ln85_fu_762_p2, ap_enable_reg_pp1_iter0, ap_CS_fsm_state18, icmp_ln102_fu_785_p2, icmp_ln53_1_fu_867_p2, ap_enable_reg_pp3_iter0, ap_block_pp1_stage0_subdone, ap_block_pp3_stage0_subdone, empty_n_1_fu_797_p1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (req_in_TVALID = ap_const_logic_0))) and (icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (req_in_TVALID = ap_const_logic_0))) and (icmp_ln38_fu_622_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                elsif (((force_fu_675_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((grp_gate_should_sample_fu_603_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((fire_reg_1047 = ap_const_lv1_0) and (force_reg_1036 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln85_fu_762_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln85_fu_762_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                if (((empty_n_1_fu_797_p1 = ap_const_lv1_0) and (icmp_ln102_fu_785_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state18;
                elsif (((icmp_ln102_fu_785_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
            when ap_ST_fsm_pp3_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (icmp_ln53_1_fu_867_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp3_stage0_subdone) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (icmp_ln53_1_fu_867_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state24;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp3_stage0;
                end if;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln190_fu_814_p2 <= std_logic_vector(unsigned(updates_load_reg_1029) + unsigned(ap_const_lv32_1));
    add_ln38_fu_628_p2 <= std_logic_vector(unsigned(i_reg_433) + unsigned(ap_const_lv4_1));
    add_ln85_fu_768_p2 <= std_logic_vector(unsigned(i_1_reg_456) + unsigned(ap_const_lv3_1));
    and_ln199_fu_830_p2 <= (xor_ln199_fu_825_p2 and gate_eval_0200_reg_490);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(14);
    ap_CS_fsm_pp3_stage0 <= ap_CS_fsm(20);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state17 <= ap_CS_fsm(15);
    ap_CS_fsm_state18 <= ap_CS_fsm(16);
    ap_CS_fsm_state19 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(18);
    ap_CS_fsm_state21 <= ap_CS_fsm(19);
    ap_CS_fsm_state24 <= ap_CS_fsm(21);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp1_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_11001_assign_proc : process(ap_enable_reg_pp1_iter1, ap_block_state16_io)
    begin
                ap_block_pp1_stage0_11001 <= ((ap_const_boolean_1 = ap_block_state16_io) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(ap_enable_reg_pp1_iter1, ap_block_state16_io)
    begin
                ap_block_pp1_stage0_subdone <= ((ap_const_boolean_1 = ap_block_state16_io) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp3_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp3_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp3_stage0_11001_assign_proc : process(ap_enable_reg_pp3_iter1, ap_block_state23_io)
    begin
                ap_block_pp3_stage0_11001 <= ((ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state23_io));
    end process;


    ap_block_pp3_stage0_subdone_assign_proc : process(ap_enable_reg_pp3_iter1, ap_block_state23_io)
    begin
                ap_block_pp3_stage0_subdone <= ((ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state23_io));
    end process;

        ap_block_state15_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state16_io_assign_proc : process(marshal_req_TREADY, icmp_ln85_reg_1071)
    begin
                ap_block_state16_io <= ((marshal_req_TREADY = ap_const_logic_0) and (icmp_ln85_reg_1071 = ap_const_lv1_0));
    end process;

        ap_block_state16_pp1_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_assign_proc : process(req_in_TVALID, icmp_ln38_fu_622_p2)
    begin
                ap_block_state2 <= ((icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (req_in_TVALID = ap_const_logic_0));
    end process;

        ap_block_state22_pp3_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state23_io_assign_proc : process(resp_out_TREADY, icmp_ln53_1_reg_1126)
    begin
                ap_block_state23_io <= ((icmp_ln53_1_reg_1126 = ap_const_lv1_0) and (resp_out_TREADY = ap_const_logic_0));
    end process;

        ap_block_state23_pp3_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_327_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_block_pp3_stage0_11001, ap_enable_reg_pp3_iter0)
    begin
                ap_condition_327 <= ((ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0));
    end process;


    ap_condition_490_assign_proc : process(icmp_ln53_1_fu_867_p2, ap_phi_mux_i_2_phi_fu_576_p4)
    begin
                ap_condition_490 <= (not((ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_3)) and not((ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_2)) and not((ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_1)) and not((ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_0)) and (icmp_ln53_1_fu_867_p2 = ap_const_lv1_0));
    end process;


    ap_condition_pp1_exit_iter0_state15_assign_proc : process(icmp_ln85_fu_762_p2)
    begin
        if ((icmp_ln85_fu_762_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state15 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state15 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp3_exit_iter0_state22_assign_proc : process(icmp_ln53_1_fu_867_p2)
    begin
        if ((icmp_ln53_1_fu_867_p2 = ap_const_lv1_1)) then 
            ap_condition_pp3_exit_iter0_state22 <= ap_const_logic_1;
        else 
            ap_condition_pp3_exit_iter0_state22 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state24)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state24) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);
    ap_enable_pp3 <= (ap_idle_pp3 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp3_assign_proc : process(ap_enable_reg_pp3_iter1, ap_enable_reg_pp3_iter0)
    begin
        if (((ap_enable_reg_pp3_iter1 = ap_const_logic_0) and (ap_enable_reg_pp3_iter0 = ap_const_logic_0))) then 
            ap_idle_pp3 <= ap_const_logic_1;
        else 
            ap_idle_pp3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i_2_phi_fu_576_p4_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln53_1_reg_1126, i_2_reg_572, i_3_reg_1130)
    begin
        if (((icmp_ln53_1_reg_1126 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
            ap_phi_mux_i_2_phi_fu_576_p4 <= i_3_reg_1130;
        else 
            ap_phi_mux_i_2_phi_fu_576_p4 <= i_2_reg_572;
        end if; 
    end process;


    ap_phi_mux_status_word_2_phi_fu_565_p4_assign_proc : process(trunc_ln141_reg_908, ap_CS_fsm_state21, select_ln199_fu_842_p3, status_word_2_reg_561)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then 
            ap_phi_mux_status_word_2_phi_fu_565_p4 <= select_ln199_fu_842_p3;
        else 
            ap_phi_mux_status_word_2_phi_fu_565_p4 <= status_word_2_reg_561;
        end if; 
    end process;


    ap_phi_mux_wait_cycles_3_phi_fu_553_p4_assign_proc : process(trunc_ln141_reg_908, ap_CS_fsm_state21, wait_cycles_1_reg_503, wait_cycles_3_reg_549)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) and (trunc_ln141_reg_908 = ap_const_lv1_0))) then 
            ap_phi_mux_wait_cycles_3_phi_fu_553_p4 <= wait_cycles_1_reg_503;
        else 
            ap_phi_mux_wait_cycles_3_phi_fu_553_p4 <= wait_cycles_3_reg_549;
        end if; 
    end process;

    ap_phi_reg_pp3_iter0_data_V_1_reg_584 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_state24)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_18_fu_863_p1 <= held_Q;
    empty_n_1_fu_797_p1 <= grp_nbread_fu_200_p5_0;
    force_fu_675_p3 <= control_flags_reg_903(1 downto 1);
    gate_eval_fu_726_p2 <= (xor_ln53_fu_720_p2 or or_ln39_1_fu_704_p2);
    grp_gate_should_sample_fu_603_ap_start <= grp_gate_should_sample_fu_603_ap_start_reg;
    grp_nbread_fu_200_p5_0 <= (0=>(marshal_resp_TVALID), others=>'-');
    i_3_fu_873_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_2_phi_fu_576_p4) + unsigned(ap_const_lv3_1));
    icmp_ln102_fu_785_p2 <= "1" when (wait_cycles_reg_467 = ap_const_lv13_1000) else "0";
    icmp_ln38_fu_622_p2 <= "1" when (i_reg_433 = ap_const_lv4_E) else "0";
    icmp_ln39_fu_682_p2 <= "1" when (signed(gate_cfg_ref_period_ticks_reg_977) < signed(ap_const_lv32_1)) else "0";
    icmp_ln53_1_fu_867_p2 <= "1" when (ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_4) else "0";
    icmp_ln53_fu_715_p2 <= "1" when (signed(sub_ln53_fu_710_p2) < signed(gate_cfg_ref_period_ticks_reg_977)) else "0";
    icmp_ln85_fu_762_p2 <= "1" when (i_1_reg_456 = ap_const_lv3_7) else "0";
    last_1_fu_879_p2 <= "1" when (ap_phi_mux_i_2_phi_fu_576_p4 = ap_const_lv3_3) else "0";
    last_fu_779_p2 <= "1" when (i_1_reg_456 = ap_const_lv3_6) else "0";

    marshal_inputs_V_address0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            marshal_inputs_V_address0 <= ap_const_lv64_2(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            marshal_inputs_V_address0 <= ap_const_lv64_1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            marshal_inputs_V_address0 <= ap_const_lv64_6(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            marshal_inputs_V_address0 <= ap_const_lv64_5(3 - 1 downto 0);
        else 
            marshal_inputs_V_address0 <= "XXX";
        end if; 
    end process;


    marshal_inputs_V_address1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_enable_reg_pp1_iter0, ap_CS_fsm_state14, zext_ln85_fu_774_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            marshal_inputs_V_address1 <= zext_ln85_fu_774_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            marshal_inputs_V_address1 <= ap_const_lv64_4(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            marshal_inputs_V_address1 <= ap_const_lv64_0(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            marshal_inputs_V_address1 <= ap_const_lv64_3(3 - 1 downto 0);
        else 
            marshal_inputs_V_address1 <= "XXX";
        end if; 
    end process;


    marshal_inputs_V_ce0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            marshal_inputs_V_ce0 <= ap_const_logic_1;
        else 
            marshal_inputs_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    marshal_inputs_V_ce1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            marshal_inputs_V_ce1 <= ap_const_logic_1;
        else 
            marshal_inputs_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    marshal_inputs_V_d0_assign_proc : process(req_words_V_q0, words_V_load_2_reg_950, words_V_load_3_reg_956, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            marshal_inputs_V_d0 <= req_words_V_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            marshal_inputs_V_d0 <= words_V_load_3_reg_956;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            marshal_inputs_V_d0 <= words_V_load_2_reg_950;
        else 
            marshal_inputs_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    marshal_inputs_V_d1_assign_proc : process(req_words_V_q1, words_V_load_1_reg_934, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            marshal_inputs_V_d1 <= req_words_V_q1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            marshal_inputs_V_d1 <= words_V_load_1_reg_934;
        else 
            marshal_inputs_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    marshal_inputs_V_we0_assign_proc : process(force_reg_1036, fire_reg_1047, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_logic_1 = ap_CS_fsm_state11) and ((fire_reg_1047 = ap_const_lv1_1) or (force_reg_1036 = ap_const_lv1_1))))) then 
            marshal_inputs_V_we0 <= ap_const_logic_1;
        else 
            marshal_inputs_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    marshal_inputs_V_we1_assign_proc : process(force_reg_1036, fire_reg_1047, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_logic_1 = ap_CS_fsm_state11) and ((fire_reg_1047 = ap_const_lv1_1) or (force_reg_1036 = ap_const_lv1_1))))) then 
            marshal_inputs_V_we1 <= ap_const_logic_1;
        else 
            marshal_inputs_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    marshal_req_TDATA <= marshal_inputs_V_q1;

    marshal_req_TDATA_blk_n_assign_proc : process(marshal_req_TREADY, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln85_reg_1071)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln85_reg_1071 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1))) then 
            marshal_req_TDATA_blk_n <= marshal_req_TREADY;
        else 
            marshal_req_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    marshal_req_TKEEP <= ap_const_lv4_F;
    marshal_req_TLAST <= last_reg_1080;
    marshal_req_TSTRB <= ap_const_lv4_F;

    marshal_req_TVALID_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln85_reg_1071, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln85_reg_1071 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1))) then 
            marshal_req_TVALID <= ap_const_logic_1;
        else 
            marshal_req_TVALID <= ap_const_logic_0;
        end if; 
    end process;


    marshal_resp_TREADY_assign_proc : process(marshal_resp_TVALID, ap_CS_fsm_state18, icmp_ln102_fu_785_p2, ap_CS_fsm_state20)
    begin
        if (((marshal_resp_TVALID = ap_const_logic_1) and ((ap_const_logic_1 = ap_CS_fsm_state20) or ((marshal_resp_TVALID = ap_const_logic_1) and ((ap_const_logic_1 = ap_CS_fsm_state20) or ((marshal_resp_TVALID = ap_const_logic_1) and ((ap_const_logic_1 = ap_CS_fsm_state20) or ((marshal_resp_TVALID = ap_const_logic_1) and ((ap_const_logic_1 = ap_CS_fsm_state20) or ((marshal_resp_TVALID = ap_const_logic_1) and (icmp_ln102_fu_785_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state18))))))))))) then 
            marshal_resp_TREADY <= ap_const_logic_1;
        else 
            marshal_resp_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    or_ln39_1_fu_704_p2 <= (tmp_fu_696_p3 or icmp_ln39_fu_682_p2);
    or_ln39_fu_691_p2 <= (tick_reg_912 or gate_state_2);

    req_in_TDATA_blk_n_assign_proc : process(req_in_TVALID, ap_CS_fsm_state2, icmp_ln38_fu_622_p2)
    begin
        if (((icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            req_in_TDATA_blk_n <= req_in_TVALID;
        else 
            req_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    req_in_TREADY_assign_proc : process(req_in_TVALID, ap_CS_fsm_state2, icmp_ln38_fu_622_p2)
    begin
        if ((not(((icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (req_in_TVALID = ap_const_logic_0))) and (icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            req_in_TREADY <= ap_const_logic_1;
        else 
            req_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    req_words_V_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13, zext_ln38_fu_634_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            req_words_V_address0 <= ap_const_lv64_9(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            req_words_V_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            req_words_V_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            req_words_V_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            req_words_V_address0 <= ap_const_lv64_C(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            req_words_V_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            req_words_V_address0 <= ap_const_lv64_1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            req_words_V_address0 <= zext_ln38_fu_634_p1(4 - 1 downto 0);
        else 
            req_words_V_address0 <= "XXXX";
        end if; 
    end process;


    req_words_V_address1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state11, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            req_words_V_address1 <= ap_const_lv64_B(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            req_words_V_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            req_words_V_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            req_words_V_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            req_words_V_address1 <= ap_const_lv64_D(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            req_words_V_address1 <= ap_const_lv64_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            req_words_V_address1 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            req_words_V_address1 <= "XXXX";
        end if; 
    end process;


    req_words_V_ce0_assign_proc : process(req_in_TVALID, ap_CS_fsm_state2, icmp_ln38_fu_622_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (not(((icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (req_in_TVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            req_words_V_ce0 <= ap_const_logic_1;
        else 
            req_words_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    req_words_V_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state11, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            req_words_V_ce1 <= ap_const_logic_1;
        else 
            req_words_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    req_words_V_we0_assign_proc : process(req_in_TVALID, ap_CS_fsm_state2, icmp_ln38_fu_622_p2)
    begin
        if ((not(((icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (req_in_TVALID = ap_const_logic_0))) and (icmp_ln38_fu_622_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            req_words_V_we0 <= ap_const_logic_1;
        else 
            req_words_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    resp_out_TDATA <= ap_phi_reg_pp3_iter1_data_V_1_reg_584;

    resp_out_TDATA_blk_n_assign_proc : process(resp_out_TREADY, ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, ap_block_pp3_stage0, icmp_ln53_1_reg_1126)
    begin
        if (((icmp_ln53_1_reg_1126 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp3_stage0) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
            resp_out_TDATA_blk_n <= resp_out_TREADY;
        else 
            resp_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    resp_out_TKEEP <= ap_const_lv4_F;
    resp_out_TLAST <= last_1_reg_1135;
    resp_out_TSTRB <= ap_const_lv4_F;

    resp_out_TVALID_assign_proc : process(ap_CS_fsm_pp3_stage0, ap_enable_reg_pp3_iter1, icmp_ln53_1_reg_1126, ap_block_pp3_stage0_11001)
    begin
        if (((icmp_ln53_1_reg_1126 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp3_stage0_11001) and (ap_enable_reg_pp3_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp3_stage0))) then 
            resp_out_TVALID <= ap_const_logic_1;
        else 
            resp_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln199_fu_842_p3 <= 
        status_word_1_fu_836_p2 when (and_ln199_fu_830_p2(0) = '1') else 
        status_word_reg_519;
    status_word_1_fu_836_p2 <= (status_word_reg_519 or ap_const_lv26_2);
    sub_ln53_fu_710_p2 <= std_logic_vector(unsigned(tick_reg_912) - unsigned(gate_state_2));
    tmp_fu_696_p3 <= or_ln39_fu_691_p2(31 downto 31);
    trunc_ln141_fu_644_p1 <= req_words_V_q1(1 - 1 downto 0);
    value_1_fu_651_p1 <= words_V_load_1_reg_934;
    value_2_fu_654_p1 <= words_V_load_2_reg_950;
    value_3_fu_657_p1 <= words_V_load_3_reg_956;
    value_4_fu_660_p1 <= words_V_load_4_reg_972;
    value_5_fu_663_p1 <= req_words_V_q0;
    value_6_fu_667_p1 <= req_words_V_q1;
    value_7_fu_805_p1 <= resp_data_V_reg_1101;
    value_fu_648_p1 <= words_V_load_reg_929;
    wait_cycles_2_fu_791_p2 <= std_logic_vector(unsigned(wait_cycles_reg_467) + unsigned(ap_const_lv13_1));
    xor_ln199_fu_825_p2 <= (force_reg_1036 xor ap_const_lv1_1);
    xor_ln53_fu_720_p2 <= (icmp_ln53_fu_715_p2 xor ap_const_lv1_1);
    zext_ln156_1_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_wait_cycles_3_phi_fu_553_p4),32));
    zext_ln156_fu_851_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_status_word_2_phi_fu_565_p4),32));
    zext_ln38_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_433),64));
    zext_ln85_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_reg_456),64));
end behav;
