-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity secloc_gate_gate_should_sample is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
    p : IN STD_LOGIC_VECTOR (31 downto 0);
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    tp : IN STD_LOGIC_VECTOR (31 downto 0);
    te : IN STD_LOGIC_VECTOR (31 downto 0);
    tick : IN STD_LOGIC_VECTOR (31 downto 0);
    gate_state_2_i : IN STD_LOGIC_VECTOR (31 downto 0);
    gate_state_2_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    gate_state_2_o_ap_vld : OUT STD_LOGIC;
    gate_state_0_i : IN STD_LOGIC_VECTOR (31 downto 0);
    gate_state_0_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    gate_state_0_o_ap_vld : OUT STD_LOGIC;
    gate_state_1_i : IN STD_LOGIC_VECTOR (31 downto 0);
    gate_state_1_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    gate_state_1_o_ap_vld : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of secloc_gate_gate_should_sample is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000001000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state50 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000010000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state51 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000100000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state52 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000001000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state53 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000010000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state54 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000100000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state55 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000001000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state56 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000010000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state57 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000100000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state58 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000001000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state59 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000010000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state60 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000100000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state61 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000001000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state62 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000010000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state63 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000100000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state64 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000001000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state65 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000010000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state66 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000100000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state67 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000001000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state68 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000010000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state69 : STD_LOGIC_VECTOR (80 downto 0) := "000000000000100000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state70 : STD_LOGIC_VECTOR (80 downto 0) := "000000000001000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state71 : STD_LOGIC_VECTOR (80 downto 0) := "000000000010000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state72 : STD_LOGIC_VECTOR (80 downto 0) := "000000000100000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state73 : STD_LOGIC_VECTOR (80 downto 0) := "000000001000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state74 : STD_LOGIC_VECTOR (80 downto 0) := "000000010000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state75 : STD_LOGIC_VECTOR (80 downto 0) := "000000100000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state76 : STD_LOGIC_VECTOR (80 downto 0) := "000001000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state77 : STD_LOGIC_VECTOR (80 downto 0) := "000010000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state78 : STD_LOGIC_VECTOR (80 downto 0) := "000100000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state79 : STD_LOGIC_VECTOR (80 downto 0) := "001000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state80 : STD_LOGIC_VECTOR (80 downto 0) := "010000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state81 : STD_LOGIC_VECTOR (80 downto 0) := "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_40490FDB : STD_LOGIC_VECTOR (31 downto 0) := "01000000010010010000111111011011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (80 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_151_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_175 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_158_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_180 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal ap_CS_fsm_state42 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state42 : signal is "none";
    signal ap_CS_fsm_state62 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state62 : signal is "none";
    signal ap_CS_fsm_state78 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state78 : signal is "none";
    signal or_cond_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_reg_971 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln21_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_reg_1016 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_1_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_1_reg_1021 : STD_LOGIC_VECTOR (0 downto 0);
    signal shift_1_fu_321_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shift_1_reg_1026 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1032 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos_shift_2_fu_380_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal pos_shift_2_reg_1037 : STD_LOGIC_VECTOR (31 downto 0);
    signal shift_4_fu_397_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shift_4_reg_1045 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln103_2_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln103_2_reg_1053 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln103_3_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln103_3_reg_1058 : STD_LOGIC_VECTOR (0 downto 0);
    signal gate_state_0_load_reg_1063 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_1070 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal tmp_10_reg_1075 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_fu_535_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_reg_1080 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal icmp_ln106_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_reg_1084 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal icmp_ln106_1_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_1_reg_1089 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1094 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal icmp_ln106_4_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_4_reg_1099 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state43 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state43 : signal is "none";
    signal icmp_ln106_5_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_5_reg_1104 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln106_2_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln106_2_reg_1109 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state44 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state44 : signal is "none";
    signal and_ln106_3_fu_646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln106_3_reg_1114 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln106_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state45 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state45 : signal is "none";
    signal icmp_ln112_2_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_2_reg_1124 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_3_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_3_reg_1129 : STD_LOGIC_VECTOR (0 downto 0);
    signal gate_state_1_load_reg_1134 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_reg_1141 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state46 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state46 : signal is "none";
    signal tmp_20_reg_1146 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_reg_1151 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state47 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state47 : signal is "none";
    signal icmp_ln115_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_reg_1155 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state63 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state63 : signal is "none";
    signal icmp_ln115_1_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_1_reg_1160 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_reg_1165 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state64 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state64 : signal is "none";
    signal or_ln115_2_fu_866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_2_reg_1170 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state79 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state79 : signal is "none";
    signal icmp_ln115_4_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_4_reg_1176 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_5_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_5_reg_1181 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_3_fu_911_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_3_reg_1186 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state80 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state80 : signal is "none";
    signal ang_spike_reg_110 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_pos_spike_phi_fu_126_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos_spike_reg_122 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state81 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state81 : signal is "none";
    signal ap_phi_mux_retval_0_i_phi_fu_137_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_0_i_reg_133 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln127_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_953_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_151_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_151_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_158_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_158_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_163_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_163_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_fu_169_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln39_fu_190_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_26_fu_196_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln53_fu_216_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln53_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln39_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln21_fu_240_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_244_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln21_fu_254_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal bitcast_ln18_fu_270_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_273_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln18_fu_283_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln18_1_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln18_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln19_fu_311_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln18_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shift_fu_317_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln90_fu_328_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_332_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln90_fu_342_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln90_1_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln90_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln90_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln91_fu_370_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln90_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos_shift_1_fu_376_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln21_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln21_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln103_1_fu_405_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_408_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln103_1_fu_418_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal bitcast_ln103_fu_439_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_442_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln103_fu_452_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln103_1_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln103_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln103_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln103_1_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_1_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln103_2_fu_489_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_492_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln103_2_fu_502_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln103_5_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln103_4_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln103_2_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_3_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln103_2_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln103_fu_529_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln106_fu_541_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_545_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln106_fu_555_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal bitcast_ln106_2_fu_571_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_575_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln106_2_fu_585_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal bitcast_ln106_1_fu_601_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_604_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln106_1_fu_614_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln106_3_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln106_2_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln106_3_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln106_2_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln106_1_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln106_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln106_1_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln112_1_fu_671_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_674_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln112_1_fu_684_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal bitcast_ln112_fu_705_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_708_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln112_fu_718_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln112_1_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_1_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_1_fu_744_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln112_2_fu_755_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_19_fu_758_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln112_2_fu_768_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln112_5_fu_778_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln112_4_fu_772_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln112_2_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_3_fu_790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln112_2_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln112_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln115_fu_807_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_811_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln115_fu_821_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal bitcast_ln115_1_fu_837_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_fu_840_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln115_1_fu_850_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln115_3_fu_860_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln115_2_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln115_2_fu_872_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_24_fu_876_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln115_2_fu_886_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln115_3_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_2_fu_906_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_1_fu_917_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_1_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_163_opcode : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_169_opcode : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (80 downto 0);

    component secloc_gate_fsub_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component secloc_gate_fdiv_32ns_32ns_32_16_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component secloc_gate_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    fsub_32ns_32ns_32_5_full_dsp_1_U1 : component secloc_gate_fsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_151_p0,
        din1 => grp_fu_151_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_151_p2);

    fdiv_32ns_32ns_32_16_no_dsp_1_U2 : component secloc_gate_fdiv_32ns_32ns_32_16_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_158_p0,
        din1 => grp_fu_158_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_158_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U3 : component secloc_gate_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_163_p0,
        din1 => grp_fu_163_p1,
        ce => ap_const_logic_1,
        opcode => grp_fu_163_opcode,
        dout => grp_fu_163_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U4 : component secloc_gate_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_169_p0,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        opcode => grp_fu_169_opcode,
        dout => grp_fu_169_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state81)) then 
                    ap_return_preg <= ap_phi_mux_retval_0_i_phi_fu_137_p8;
                end if; 
            end if;
        end if;
    end process;


    ang_spike_reg_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) and (ap_const_lv1_0 = and_ln103_fu_535_p2))) then 
                ang_spike_reg_110 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln103_reg_1080) and (ap_const_logic_1 = ap_CS_fsm_state45))) then 
                ang_spike_reg_110 <= or_ln106_fu_666_p2;
            end if; 
        end if;
    end process;

    pos_spike_reg_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state47) and (ap_const_lv1_0 = and_ln112_fu_801_p2))) then 
                pos_spike_reg_122 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln112_reg_1151) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
                pos_spike_reg_122 <= or_ln115_fu_931_p2;
            end if; 
        end if;
    end process;

    retval_0_i_reg_133_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((or_ln127_fu_947_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (or_cond_reg_971 = ap_const_lv1_1)))) then 
                retval_0_i_reg_133 <= ap_const_lv1_0;
            elsif ((((tmp_27_fu_953_p3 = ap_const_lv1_1) and (or_ln127_fu_947_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0)) or ((tmp_27_fu_953_p3 = ap_const_lv1_0) and (or_ln127_fu_947_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0)))) then 
                retval_0_i_reg_133 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                and_ln103_reg_1080 <= and_ln103_fu_535_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state44)) then
                and_ln106_3_reg_1114 <= and_ln106_3_fu_646_p2;
                or_ln106_2_reg_1109 <= or_ln106_2_fu_630_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state47)) then
                and_ln112_reg_1151 <= and_ln112_fu_801_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state80)) then
                and_ln115_3_reg_1186 <= and_ln115_3_fu_911_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                gate_state_0_load_reg_1063 <= gate_state_0_i;
                icmp_ln103_2_reg_1053 <= icmp_ln103_2_fu_422_p2;
                icmp_ln103_3_reg_1058 <= icmp_ln103_3_fu_428_p2;
                shift_4_reg_1045 <= shift_4_fu_397_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state45)) then
                gate_state_1_load_reg_1134 <= gate_state_1_i;
                icmp_ln112_2_reg_1124 <= icmp_ln112_2_fu_688_p2;
                icmp_ln112_3_reg_1129 <= icmp_ln112_3_fu_694_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state27)) then
                icmp_ln106_1_reg_1089 <= icmp_ln106_1_fu_565_p2;
                icmp_ln106_reg_1084 <= icmp_ln106_fu_559_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state43)) then
                icmp_ln106_4_reg_1099 <= icmp_ln106_4_fu_589_p2;
                icmp_ln106_5_reg_1104 <= icmp_ln106_5_fu_595_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state63)) then
                icmp_ln115_1_reg_1160 <= icmp_ln115_1_fu_831_p2;
                icmp_ln115_reg_1155 <= icmp_ln115_fu_825_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state79)) then
                icmp_ln115_4_reg_1176 <= icmp_ln115_4_fu_890_p2;
                icmp_ln115_5_reg_1181 <= icmp_ln115_5_fu_896_p2;
                or_ln115_2_reg_1170 <= or_ln115_2_fu_866_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (or_cond_reg_971 = ap_const_lv1_0))) then
                icmp_ln21_1_reg_1021 <= icmp_ln21_1_fu_264_p2;
                icmp_ln21_reg_1016 <= icmp_ln21_fu_258_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                or_cond_reg_971 <= or_cond_fu_234_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                pos_shift_2_reg_1037 <= pos_shift_2_fu_380_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state6))) then
                reg_175 <= grp_fu_151_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state78) or (ap_const_logic_1 = ap_CS_fsm_state62) or (ap_const_logic_1 = ap_CS_fsm_state42) or (ap_const_logic_1 = ap_CS_fsm_state26))) then
                reg_180 <= grp_fu_158_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                shift_1_reg_1026 <= shift_1_fu_321_p3;
                tmp_4_reg_1032 <= grp_fu_169_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                tmp_10_reg_1075 <= grp_fu_169_p2;
                tmp_9_reg_1070 <= grp_fu_163_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state28)) then
                tmp_13_reg_1094 <= grp_fu_163_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state46)) then
                tmp_18_reg_1141 <= grp_fu_163_p2;
                tmp_20_reg_1146 <= grp_fu_169_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state64)) then
                tmp_23_reg_1165 <= grp_fu_163_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, or_cond_reg_971, ap_CS_fsm_state2, and_ln103_fu_535_p2, ap_CS_fsm_state11, and_ln112_fu_801_p2, ap_CS_fsm_state47)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (or_cond_reg_971 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state81;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (ap_const_lv1_0 = and_ln103_fu_535_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state45;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state47) and (ap_const_lv1_0 = and_ln112_fu_801_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state81;
                else
                    ap_NS_fsm <= ap_ST_fsm_state48;
                end if;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state50;
            when ap_ST_fsm_state50 => 
                ap_NS_fsm <= ap_ST_fsm_state51;
            when ap_ST_fsm_state51 => 
                ap_NS_fsm <= ap_ST_fsm_state52;
            when ap_ST_fsm_state52 => 
                ap_NS_fsm <= ap_ST_fsm_state53;
            when ap_ST_fsm_state53 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when ap_ST_fsm_state54 => 
                ap_NS_fsm <= ap_ST_fsm_state55;
            when ap_ST_fsm_state55 => 
                ap_NS_fsm <= ap_ST_fsm_state56;
            when ap_ST_fsm_state56 => 
                ap_NS_fsm <= ap_ST_fsm_state57;
            when ap_ST_fsm_state57 => 
                ap_NS_fsm <= ap_ST_fsm_state58;
            when ap_ST_fsm_state58 => 
                ap_NS_fsm <= ap_ST_fsm_state59;
            when ap_ST_fsm_state59 => 
                ap_NS_fsm <= ap_ST_fsm_state60;
            when ap_ST_fsm_state60 => 
                ap_NS_fsm <= ap_ST_fsm_state61;
            when ap_ST_fsm_state61 => 
                ap_NS_fsm <= ap_ST_fsm_state62;
            when ap_ST_fsm_state62 => 
                ap_NS_fsm <= ap_ST_fsm_state63;
            when ap_ST_fsm_state63 => 
                ap_NS_fsm <= ap_ST_fsm_state64;
            when ap_ST_fsm_state64 => 
                ap_NS_fsm <= ap_ST_fsm_state65;
            when ap_ST_fsm_state65 => 
                ap_NS_fsm <= ap_ST_fsm_state66;
            when ap_ST_fsm_state66 => 
                ap_NS_fsm <= ap_ST_fsm_state67;
            when ap_ST_fsm_state67 => 
                ap_NS_fsm <= ap_ST_fsm_state68;
            when ap_ST_fsm_state68 => 
                ap_NS_fsm <= ap_ST_fsm_state69;
            when ap_ST_fsm_state69 => 
                ap_NS_fsm <= ap_ST_fsm_state70;
            when ap_ST_fsm_state70 => 
                ap_NS_fsm <= ap_ST_fsm_state71;
            when ap_ST_fsm_state71 => 
                ap_NS_fsm <= ap_ST_fsm_state72;
            when ap_ST_fsm_state72 => 
                ap_NS_fsm <= ap_ST_fsm_state73;
            when ap_ST_fsm_state73 => 
                ap_NS_fsm <= ap_ST_fsm_state74;
            when ap_ST_fsm_state74 => 
                ap_NS_fsm <= ap_ST_fsm_state75;
            when ap_ST_fsm_state75 => 
                ap_NS_fsm <= ap_ST_fsm_state76;
            when ap_ST_fsm_state76 => 
                ap_NS_fsm <= ap_ST_fsm_state77;
            when ap_ST_fsm_state77 => 
                ap_NS_fsm <= ap_ST_fsm_state78;
            when ap_ST_fsm_state78 => 
                ap_NS_fsm <= ap_ST_fsm_state79;
            when ap_ST_fsm_state79 => 
                ap_NS_fsm <= ap_ST_fsm_state80;
            when ap_ST_fsm_state80 => 
                ap_NS_fsm <= ap_ST_fsm_state81;
            when ap_ST_fsm_state81 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    and_ln103_1_fu_478_p2 <= (or_ln103_fu_468_p2 and or_ln103_1_fu_474_p2);
    and_ln103_2_fu_484_p2 <= (tmp_9_reg_1070 and and_ln103_1_fu_478_p2);
    and_ln103_3_fu_524_p2 <= (tmp_10_reg_1075 and or_ln103_2_fu_518_p2);
    and_ln103_fu_535_p2 <= (xor_ln103_fu_529_p2 and and_ln103_2_fu_484_p2);
    and_ln106_1_fu_661_p2 <= (tmp_13_reg_1094 and and_ln106_fu_656_p2);
    and_ln106_2_fu_640_p2 <= (or_ln106_3_fu_636_p2 and or_ln106_2_fu_630_p2);
    and_ln106_3_fu_646_p2 <= (grp_fu_163_p2 and and_ln106_2_fu_640_p2);
    and_ln106_fu_656_p2 <= (or_ln106_2_reg_1109 and or_ln106_1_fu_652_p2);
    and_ln112_1_fu_744_p2 <= (or_ln112_fu_734_p2 and or_ln112_1_fu_740_p2);
    and_ln112_2_fu_750_p2 <= (tmp_18_reg_1141 and and_ln112_1_fu_744_p2);
    and_ln112_3_fu_790_p2 <= (tmp_20_reg_1146 and or_ln112_2_fu_784_p2);
    and_ln112_fu_801_p2 <= (xor_ln112_fu_795_p2 and and_ln112_2_fu_750_p2);
    and_ln115_1_fu_926_p2 <= (tmp_23_reg_1165 and and_ln115_fu_921_p2);
    and_ln115_2_fu_906_p2 <= (or_ln115_3_fu_902_p2 and or_ln115_2_reg_1170);
    and_ln115_3_fu_911_p2 <= (grp_fu_163_p2 and and_ln115_2_fu_906_p2);
    and_ln115_fu_921_p2 <= (or_ln115_2_reg_1170 and or_ln115_1_fu_917_p2);
    and_ln18_fu_305_p2 <= (or_ln18_fu_299_p2 and grp_fu_163_p2);
    and_ln21_fu_392_p2 <= (tmp_4_reg_1032 and or_ln21_fu_388_p2);
    and_ln90_fu_364_p2 <= (or_ln90_fu_358_p2 and grp_fu_163_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state42 <= ap_CS_fsm(41);
    ap_CS_fsm_state43 <= ap_CS_fsm(42);
    ap_CS_fsm_state44 <= ap_CS_fsm(43);
    ap_CS_fsm_state45 <= ap_CS_fsm(44);
    ap_CS_fsm_state46 <= ap_CS_fsm(45);
    ap_CS_fsm_state47 <= ap_CS_fsm(46);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state62 <= ap_CS_fsm(61);
    ap_CS_fsm_state63 <= ap_CS_fsm(62);
    ap_CS_fsm_state64 <= ap_CS_fsm(63);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state78 <= ap_CS_fsm(77);
    ap_CS_fsm_state79 <= ap_CS_fsm(78);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state80 <= ap_CS_fsm(79);
    ap_CS_fsm_state81 <= ap_CS_fsm(80);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state81)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state81) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_pos_spike_phi_fu_126_p4_assign_proc : process(or_cond_reg_971, and_ln112_reg_1151, or_ln115_fu_931_p2, pos_spike_reg_122, ap_CS_fsm_state81)
    begin
        if (((ap_const_lv1_1 = and_ln112_reg_1151) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            ap_phi_mux_pos_spike_phi_fu_126_p4 <= or_ln115_fu_931_p2;
        else 
            ap_phi_mux_pos_spike_phi_fu_126_p4 <= pos_spike_reg_122;
        end if; 
    end process;


    ap_phi_mux_retval_0_i_phi_fu_137_p8_assign_proc : process(or_cond_reg_971, ap_CS_fsm_state81, retval_0_i_reg_133, or_ln127_fu_947_p2, tmp_27_fu_953_p3)
    begin
        if (((or_ln127_fu_947_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            ap_phi_mux_retval_0_i_phi_fu_137_p8 <= ap_const_lv1_0;
        elsif ((((tmp_27_fu_953_p3 = ap_const_lv1_1) and (or_ln127_fu_947_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0)) or ((tmp_27_fu_953_p3 = ap_const_lv1_0) and (or_ln127_fu_947_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0)))) then 
            ap_phi_mux_retval_0_i_phi_fu_137_p8 <= ap_const_lv1_1;
        else 
            ap_phi_mux_retval_0_i_phi_fu_137_p8 <= retval_0_i_reg_133;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state81)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state81)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state81, ap_phi_mux_retval_0_i_phi_fu_137_p8, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state81)) then 
            ap_return <= ap_phi_mux_retval_0_i_phi_fu_137_p8;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    bitcast_ln103_1_fu_405_p1 <= p_read2;
    bitcast_ln103_2_fu_489_p1 <= gate_state_0_load_reg_1063;
    bitcast_ln103_fu_439_p1 <= shift_4_reg_1045;
    bitcast_ln106_1_fu_601_p1 <= p_read;
    bitcast_ln106_2_fu_571_p1 <= reg_180;
    bitcast_ln106_fu_541_p1 <= reg_180;
    bitcast_ln112_1_fu_671_p1 <= p_read3;
    bitcast_ln112_2_fu_755_p1 <= gate_state_1_load_reg_1134;
    bitcast_ln112_fu_705_p1 <= pos_shift_2_reg_1037;
    bitcast_ln115_1_fu_837_p1 <= p_read;
    bitcast_ln115_2_fu_872_p1 <= reg_180;
    bitcast_ln115_fu_807_p1 <= reg_180;
    bitcast_ln18_fu_270_p1 <= a;
    bitcast_ln21_fu_240_p1 <= te;
    bitcast_ln90_fu_328_p1 <= reg_175;

    gate_state_0_o_assign_proc : process(gate_state_0_i, or_cond_reg_971, shift_4_reg_1045, ang_spike_reg_110, ap_CS_fsm_state81)
    begin
        if (((ap_const_lv1_1 = ang_spike_reg_110) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            gate_state_0_o <= shift_4_reg_1045;
        else 
            gate_state_0_o <= gate_state_0_i;
        end if; 
    end process;


    gate_state_0_o_ap_vld_assign_proc : process(or_cond_reg_971, ang_spike_reg_110, ap_CS_fsm_state81)
    begin
        if (((ap_const_lv1_1 = ang_spike_reg_110) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            gate_state_0_o_ap_vld <= ap_const_logic_1;
        else 
            gate_state_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    gate_state_1_o_assign_proc : process(gate_state_1_i, or_cond_reg_971, pos_shift_2_reg_1037, ap_phi_mux_pos_spike_phi_fu_126_p4, ap_CS_fsm_state81)
    begin
        if (((ap_phi_mux_pos_spike_phi_fu_126_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            gate_state_1_o <= pos_shift_2_reg_1037;
        else 
            gate_state_1_o <= gate_state_1_i;
        end if; 
    end process;


    gate_state_1_o_ap_vld_assign_proc : process(or_cond_reg_971, ap_phi_mux_pos_spike_phi_fu_126_p4, ap_CS_fsm_state81)
    begin
        if (((ap_phi_mux_pos_spike_phi_fu_126_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            gate_state_1_o_ap_vld <= ap_const_logic_1;
        else 
            gate_state_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    gate_state_2_o_assign_proc : process(tick, gate_state_2_i, or_cond_reg_971, ap_CS_fsm_state81, or_ln127_fu_947_p2, tmp_27_fu_953_p3)
    begin
        if (((tmp_27_fu_953_p3 = ap_const_lv1_0) and (or_ln127_fu_947_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            gate_state_2_o <= tick;
        else 
            gate_state_2_o <= gate_state_2_i;
        end if; 
    end process;


    gate_state_2_o_ap_vld_assign_proc : process(or_cond_reg_971, ap_CS_fsm_state81, or_ln127_fu_947_p2, tmp_27_fu_953_p3)
    begin
        if (((tmp_27_fu_953_p3 = ap_const_lv1_0) and (or_ln127_fu_947_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state81) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            gate_state_2_o_ap_vld <= ap_const_logic_1;
        else 
            gate_state_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_151_p0_assign_proc : process(p, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_151_p0 <= ap_const_lv32_40490FDB;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_151_p0 <= p;
        else 
            grp_fu_151_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_151_p1_assign_proc : process(tp, ap_CS_fsm_state2, shift_1_reg_1026, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_151_p1 <= shift_1_reg_1026;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_151_p1 <= tp;
        else 
            grp_fu_151_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_158_p0_assign_proc : process(pos_shift_2_reg_1037, shift_4_reg_1045, ap_CS_fsm_state11, ap_CS_fsm_state27, ap_CS_fsm_state47, ap_CS_fsm_state63)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state47)) then 
            grp_fu_158_p0 <= pos_shift_2_reg_1037;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state63) or (ap_const_logic_1 = ap_CS_fsm_state27))) then 
            grp_fu_158_p0 <= ap_const_lv32_3F800000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_158_p0 <= shift_4_reg_1045;
        else 
            grp_fu_158_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_158_p1_assign_proc : process(reg_180, gate_state_0_load_reg_1063, ap_CS_fsm_state11, ap_CS_fsm_state27, gate_state_1_load_reg_1134, ap_CS_fsm_state47, ap_CS_fsm_state63)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state47)) then 
            grp_fu_158_p1 <= gate_state_1_load_reg_1134;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state63) or (ap_const_logic_1 = ap_CS_fsm_state27))) then 
            grp_fu_158_p1 <= reg_180;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_158_p1 <= gate_state_0_load_reg_1063;
        else 
            grp_fu_158_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_163_opcode_assign_proc : process(or_cond_reg_971, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state27, ap_CS_fsm_state43, ap_CS_fsm_state45, ap_CS_fsm_state63, ap_CS_fsm_state79, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state79) or (ap_const_logic_1 = ap_CS_fsm_state63) or (ap_const_logic_1 = ap_CS_fsm_state43) or (ap_const_logic_1 = ap_CS_fsm_state27))) then 
            grp_fu_163_opcode <= ap_const_lv5_3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state45) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            grp_fu_163_opcode <= ap_const_lv5_2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (or_cond_reg_971 = ap_const_lv1_0)))) then 
            grp_fu_163_opcode <= ap_const_lv5_4;
        else 
            grp_fu_163_opcode <= "XXXXX";
        end if; 
    end process;


    grp_fu_163_p0_assign_proc : process(a, reg_175, reg_180, ap_CS_fsm_state2, pos_shift_2_reg_1037, shift_4_fu_397_p3, ap_CS_fsm_state9, ap_CS_fsm_state27, ap_CS_fsm_state43, ap_CS_fsm_state45, ap_CS_fsm_state63, ap_CS_fsm_state79, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state45)) then 
            grp_fu_163_p0 <= pos_shift_2_reg_1037;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state79) or (ap_const_logic_1 = ap_CS_fsm_state63) or (ap_const_logic_1 = ap_CS_fsm_state43) or (ap_const_logic_1 = ap_CS_fsm_state27))) then 
            grp_fu_163_p0 <= reg_180;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_163_p0 <= shift_4_fu_397_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_163_p0 <= reg_175;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_163_p0 <= a;
        else 
            grp_fu_163_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_163_p1_assign_proc : process(p_read, p_read2, p_read3, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state27, ap_CS_fsm_state43, ap_CS_fsm_state45, ap_CS_fsm_state63, ap_CS_fsm_state79, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state45)) then 
            grp_fu_163_p1 <= p_read3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state79) or (ap_const_logic_1 = ap_CS_fsm_state63) or (ap_const_logic_1 = ap_CS_fsm_state43) or (ap_const_logic_1 = ap_CS_fsm_state27))) then 
            grp_fu_163_p1 <= p_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_163_p1 <= p_read2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            grp_fu_163_p1 <= ap_const_lv32_0;
        else 
            grp_fu_163_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_169_opcode_assign_proc : process(or_cond_reg_971, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state45)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state45) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            grp_fu_169_opcode <= ap_const_lv5_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (or_cond_reg_971 = ap_const_lv1_0))) then 
            grp_fu_169_opcode <= ap_const_lv5_4;
        else 
            grp_fu_169_opcode <= "XXXXX";
        end if; 
    end process;


    grp_fu_169_p0_assign_proc : process(te, gate_state_0_i, gate_state_1_i, ap_CS_fsm_state2, ap_CS_fsm_state9, ap_CS_fsm_state45)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state45)) then 
            grp_fu_169_p0 <= gate_state_1_i;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_169_p0 <= gate_state_0_i;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_169_p0 <= te;
        else 
            grp_fu_169_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln103_1_fu_462_p2 <= "1" when (trunc_ln103_fu_452_p1 = ap_const_lv23_0) else "0";
    icmp_ln103_2_fu_422_p2 <= "0" when (tmp_8_fu_408_p4 = ap_const_lv8_FF) else "1";
    icmp_ln103_3_fu_428_p2 <= "1" when (trunc_ln103_1_fu_418_p1 = ap_const_lv23_0) else "0";
    icmp_ln103_4_fu_506_p2 <= "0" when (tmp_s_fu_492_p4 = ap_const_lv8_FF) else "1";
    icmp_ln103_5_fu_512_p2 <= "1" when (trunc_ln103_2_fu_502_p1 = ap_const_lv23_0) else "0";
    icmp_ln103_fu_456_p2 <= "0" when (tmp_7_fu_442_p4 = ap_const_lv8_FF) else "1";
    icmp_ln106_1_fu_565_p2 <= "1" when (trunc_ln106_fu_555_p1 = ap_const_lv23_0) else "0";
    icmp_ln106_2_fu_618_p2 <= "0" when (tmp_12_fu_604_p4 = ap_const_lv8_FF) else "1";
    icmp_ln106_3_fu_624_p2 <= "1" when (trunc_ln106_1_fu_614_p1 = ap_const_lv23_0) else "0";
    icmp_ln106_4_fu_589_p2 <= "0" when (tmp_14_fu_575_p4 = ap_const_lv8_FF) else "1";
    icmp_ln106_5_fu_595_p2 <= "1" when (trunc_ln106_2_fu_585_p1 = ap_const_lv23_0) else "0";
    icmp_ln106_fu_559_p2 <= "0" when (tmp_11_fu_545_p4 = ap_const_lv8_FF) else "1";
    icmp_ln112_1_fu_728_p2 <= "1" when (trunc_ln112_fu_718_p1 = ap_const_lv23_0) else "0";
    icmp_ln112_2_fu_688_p2 <= "0" when (tmp_17_fu_674_p4 = ap_const_lv8_FF) else "1";
    icmp_ln112_3_fu_694_p2 <= "1" when (trunc_ln112_1_fu_684_p1 = ap_const_lv23_0) else "0";
    icmp_ln112_4_fu_772_p2 <= "0" when (tmp_19_fu_758_p4 = ap_const_lv8_FF) else "1";
    icmp_ln112_5_fu_778_p2 <= "1" when (trunc_ln112_2_fu_768_p1 = ap_const_lv23_0) else "0";
    icmp_ln112_fu_722_p2 <= "0" when (tmp_16_fu_708_p4 = ap_const_lv8_FF) else "1";
    icmp_ln115_1_fu_831_p2 <= "1" when (trunc_ln115_fu_821_p1 = ap_const_lv23_0) else "0";
    icmp_ln115_2_fu_854_p2 <= "0" when (tmp_22_fu_840_p4 = ap_const_lv8_FF) else "1";
    icmp_ln115_3_fu_860_p2 <= "1" when (trunc_ln115_1_fu_850_p1 = ap_const_lv23_0) else "0";
    icmp_ln115_4_fu_890_p2 <= "0" when (tmp_24_fu_876_p4 = ap_const_lv8_FF) else "1";
    icmp_ln115_5_fu_896_p2 <= "1" when (trunc_ln115_2_fu_886_p1 = ap_const_lv23_0) else "0";
    icmp_ln115_fu_825_p2 <= "0" when (tmp_21_fu_811_p4 = ap_const_lv8_FF) else "1";
    icmp_ln18_1_fu_293_p2 <= "1" when (trunc_ln18_fu_283_p1 = ap_const_lv23_0) else "0";
    icmp_ln18_fu_287_p2 <= "0" when (tmp_1_fu_273_p4 = ap_const_lv8_FF) else "1";
    icmp_ln21_1_fu_264_p2 <= "1" when (trunc_ln21_fu_254_p1 = ap_const_lv23_0) else "0";
    icmp_ln21_fu_258_p2 <= "0" when (tmp_3_fu_244_p4 = ap_const_lv8_FF) else "1";
    icmp_ln39_fu_210_p2 <= "1" when (signed(p_read1) > signed(ap_const_lv32_0)) else "0";
    icmp_ln53_fu_222_p2 <= "1" when (signed(sub_ln53_fu_216_p2) < signed(p_read1)) else "0";
    icmp_ln90_1_fu_352_p2 <= "1" when (trunc_ln90_fu_342_p1 = ap_const_lv23_0) else "0";
    icmp_ln90_fu_346_p2 <= "0" when (tmp_5_fu_332_p4 = ap_const_lv8_FF) else "1";
    or_cond_fu_234_p2 <= (tmp_fu_228_p2 and icmp_ln39_fu_210_p2);
    or_ln103_1_fu_474_p2 <= (icmp_ln103_3_reg_1058 or icmp_ln103_2_reg_1053);
    or_ln103_2_fu_518_p2 <= (icmp_ln103_5_fu_512_p2 or icmp_ln103_4_fu_506_p2);
    or_ln103_fu_468_p2 <= (icmp_ln103_fu_456_p2 or icmp_ln103_1_fu_462_p2);
    or_ln106_1_fu_652_p2 <= (icmp_ln106_reg_1084 or icmp_ln106_1_reg_1089);
    or_ln106_2_fu_630_p2 <= (icmp_ln106_3_fu_624_p2 or icmp_ln106_2_fu_618_p2);
    or_ln106_3_fu_636_p2 <= (icmp_ln106_5_reg_1104 or icmp_ln106_4_reg_1099);
    or_ln106_fu_666_p2 <= (and_ln106_3_reg_1114 or and_ln106_1_fu_661_p2);
    or_ln112_1_fu_740_p2 <= (icmp_ln112_3_reg_1129 or icmp_ln112_2_reg_1124);
    or_ln112_2_fu_784_p2 <= (icmp_ln112_5_fu_778_p2 or icmp_ln112_4_fu_772_p2);
    or_ln112_fu_734_p2 <= (icmp_ln112_fu_722_p2 or icmp_ln112_1_fu_728_p2);
    or_ln115_1_fu_917_p2 <= (icmp_ln115_reg_1155 or icmp_ln115_1_reg_1160);
    or_ln115_2_fu_866_p2 <= (icmp_ln115_3_fu_860_p2 or icmp_ln115_2_fu_854_p2);
    or_ln115_3_fu_902_p2 <= (icmp_ln115_5_reg_1181 or icmp_ln115_4_reg_1176);
    or_ln115_fu_931_p2 <= (and_ln115_3_reg_1186 or and_ln115_1_fu_926_p2);
    or_ln127_fu_947_p2 <= (ap_phi_mux_pos_spike_phi_fu_126_p4 or ang_spike_reg_110);
    or_ln18_fu_299_p2 <= (icmp_ln18_fu_287_p2 or icmp_ln18_1_fu_293_p2);
    or_ln21_fu_388_p2 <= (icmp_ln21_reg_1016 or icmp_ln21_1_reg_1021);
    or_ln39_fu_190_p2 <= (tick or gate_state_2_i);
    or_ln90_fu_358_p2 <= (icmp_ln90_fu_346_p2 or icmp_ln90_1_fu_352_p2);
    pos_shift_1_fu_376_p1 <= xor_ln91_fu_370_p2;
    pos_shift_2_fu_380_p3 <= 
        pos_shift_1_fu_376_p1 when (and_ln90_fu_364_p2(0) = '1') else 
        reg_175;
    shift_1_fu_321_p3 <= 
        shift_fu_317_p1 when (and_ln18_fu_305_p2(0) = '1') else 
        a;
    shift_4_fu_397_p3 <= 
        reg_175 when (and_ln21_fu_392_p2(0) = '1') else 
        shift_1_reg_1026;
    shift_fu_317_p1 <= xor_ln19_fu_311_p2;
    sub_ln53_fu_216_p2 <= std_logic_vector(unsigned(tick) - unsigned(gate_state_2_i));
    tmp_11_fu_545_p4 <= bitcast_ln106_fu_541_p1(30 downto 23);
    tmp_12_fu_604_p4 <= bitcast_ln106_1_fu_601_p1(30 downto 23);
    tmp_14_fu_575_p4 <= bitcast_ln106_2_fu_571_p1(30 downto 23);
    tmp_16_fu_708_p4 <= bitcast_ln112_fu_705_p1(30 downto 23);
    tmp_17_fu_674_p4 <= bitcast_ln112_1_fu_671_p1(30 downto 23);
    tmp_19_fu_758_p4 <= bitcast_ln112_2_fu_755_p1(30 downto 23);
    tmp_1_fu_273_p4 <= bitcast_ln18_fu_270_p1(30 downto 23);
    tmp_21_fu_811_p4 <= bitcast_ln115_fu_807_p1(30 downto 23);
    tmp_22_fu_840_p4 <= bitcast_ln115_1_fu_837_p1(30 downto 23);
    tmp_24_fu_876_p4 <= bitcast_ln115_2_fu_872_p1(30 downto 23);
    tmp_26_fu_196_p3 <= or_ln39_fu_190_p2(31 downto 31);
    tmp_27_fu_953_p3 <= tick(31 downto 31);
    tmp_3_fu_244_p4 <= bitcast_ln21_fu_240_p1(30 downto 23);
    tmp_5_fu_332_p4 <= bitcast_ln90_fu_328_p1(30 downto 23);
    tmp_7_fu_442_p4 <= bitcast_ln103_fu_439_p1(30 downto 23);
    tmp_8_fu_408_p4 <= bitcast_ln103_1_fu_405_p1(30 downto 23);
    tmp_fu_228_p2 <= (xor_ln39_fu_204_p2 and icmp_ln53_fu_222_p2);
    tmp_s_fu_492_p4 <= bitcast_ln103_2_fu_489_p1(30 downto 23);
    trunc_ln103_1_fu_418_p1 <= bitcast_ln103_1_fu_405_p1(23 - 1 downto 0);
    trunc_ln103_2_fu_502_p1 <= bitcast_ln103_2_fu_489_p1(23 - 1 downto 0);
    trunc_ln103_fu_452_p1 <= bitcast_ln103_fu_439_p1(23 - 1 downto 0);
    trunc_ln106_1_fu_614_p1 <= bitcast_ln106_1_fu_601_p1(23 - 1 downto 0);
    trunc_ln106_2_fu_585_p1 <= bitcast_ln106_2_fu_571_p1(23 - 1 downto 0);
    trunc_ln106_fu_555_p1 <= bitcast_ln106_fu_541_p1(23 - 1 downto 0);
    trunc_ln112_1_fu_684_p1 <= bitcast_ln112_1_fu_671_p1(23 - 1 downto 0);
    trunc_ln112_2_fu_768_p1 <= bitcast_ln112_2_fu_755_p1(23 - 1 downto 0);
    trunc_ln112_fu_718_p1 <= bitcast_ln112_fu_705_p1(23 - 1 downto 0);
    trunc_ln115_1_fu_850_p1 <= bitcast_ln115_1_fu_837_p1(23 - 1 downto 0);
    trunc_ln115_2_fu_886_p1 <= bitcast_ln115_2_fu_872_p1(23 - 1 downto 0);
    trunc_ln115_fu_821_p1 <= bitcast_ln115_fu_807_p1(23 - 1 downto 0);
    trunc_ln18_fu_283_p1 <= bitcast_ln18_fu_270_p1(23 - 1 downto 0);
    trunc_ln21_fu_254_p1 <= bitcast_ln21_fu_240_p1(23 - 1 downto 0);
    trunc_ln90_fu_342_p1 <= bitcast_ln90_fu_328_p1(23 - 1 downto 0);
    xor_ln103_fu_529_p2 <= (ap_const_lv1_1 xor and_ln103_3_fu_524_p2);
    xor_ln112_fu_795_p2 <= (ap_const_lv1_1 xor and_ln112_3_fu_790_p2);
    xor_ln19_fu_311_p2 <= (bitcast_ln18_fu_270_p1 xor ap_const_lv32_80000000);
    xor_ln39_fu_204_p2 <= (tmp_26_fu_196_p3 xor ap_const_lv1_1);
    xor_ln91_fu_370_p2 <= (bitcast_ln90_fu_328_p1 xor ap_const_lv32_80000000);
end behav;
