// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="secloc_shell_secloc_shell,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.644000,HLS_SYN_LAT=29,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1321,HLS_SYN_LUT=1548,HLS_VERSION=2020_1}" *)

module secloc_shell (
        ap_clk,
        ap_rst_n,
        gate_req_TDATA,
        gate_req_TVALID,
        gate_req_TREADY,
        gate_req_TKEEP,
        gate_req_TSTRB,
        gate_req_TLAST,
        gate_resp_TDATA,
        gate_resp_TVALID,
        gate_resp_TREADY,
        gate_resp_TKEEP,
        gate_resp_TSTRB,
        gate_resp_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] gate_req_TDATA;
output   gate_req_TVALID;
input   gate_req_TREADY;
output  [3:0] gate_req_TKEEP;
output  [3:0] gate_req_TSTRB;
output  [0:0] gate_req_TLAST;
input  [31:0] gate_resp_TDATA;
input   gate_resp_TVALID;
output   gate_resp_TREADY;
input  [3:0] gate_resp_TKEEP;
input  [3:0] gate_resp_TSTRB;
input  [0:0] gate_resp_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] angleD;
wire   [31:0] angle_cos;
wire   [31:0] angle_sin;
wire   [31:0] position;
wire   [31:0] positionD;
wire   [31:0] target_equilibrium;
wire   [31:0] target_position;
wire   [31:0] angle;
wire   [31:0] tick;
wire   [31:0] log_base;
wire   [31:0] ref_period_ticks;
wire   [31:0] dead_ang;
wire   [31:0] dead_pos;
wire   [31:0] control_flags;
reg    Q_ap_vld;
reg    status_ap_vld;
reg    update_count_ap_vld;
reg    nn_wait_cycles_ap_vld;
reg    gate_resp_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln60_fu_335_p2;
reg   [31:0] control_flags_read_reg_415;
reg   [31:0] dead_pos_read_reg_420;
reg   [31:0] dead_ang_read_reg_425;
reg   [31:0] ref_period_ticks_read_reg_430;
reg   [31:0] log_base_read_reg_435;
reg   [31:0] tick_read_reg_440;
reg   [31:0] angle_read_reg_445;
reg   [31:0] target_position_read_reg_450;
reg   [31:0] target_equilibrium_read_reg_455;
reg   [31:0] positionD_read_reg_460;
reg   [31:0] position_read_reg_465;
reg   [31:0] angle_sin_read_reg_470;
reg   [31:0] angle_cos_read_reg_475;
reg   [31:0] angleD_read_reg_480;
wire   [2:0] add_ln60_fu_341_p2;
reg    ap_block_state3;
wire    grp_write_request_packet_fu_295_ap_start;
wire    grp_write_request_packet_fu_295_ap_done;
wire    grp_write_request_packet_fu_295_ap_idle;
wire    grp_write_request_packet_fu_295_ap_ready;
wire   [31:0] grp_write_request_packet_fu_295_gate_req_TDATA;
wire    grp_write_request_packet_fu_295_gate_req_TVALID;
wire    grp_write_request_packet_fu_295_gate_req_TREADY;
wire   [3:0] grp_write_request_packet_fu_295_gate_req_TKEEP;
wire   [3:0] grp_write_request_packet_fu_295_gate_req_TSTRB;
wire   [0:0] grp_write_request_packet_fu_295_gate_req_TLAST;
reg   [2:0] i_reg_284;
wire    ap_CS_fsm_state2;
reg    grp_write_request_packet_fu_295_ap_start_reg;
reg   [31:0] beat_data_V_fu_144;
wire   [1:0] trunc_ln63_fu_351_p1;
wire    ap_CS_fsm_state4;
reg   [31:0] beat_data_V_1_fu_148;
reg   [31:0] beat_data_V_2_fu_152;
reg   [31:0] beat_data_V_3_fu_156;
wire    regslice_both_gate_req_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
wire    gate_req_TREADY_int_regslice;
wire    regslice_both_gate_req_V_data_V_U_vld_out;
wire    regslice_both_gate_req_V_keep_V_U_apdone_blk;
wire    regslice_both_gate_req_V_keep_V_U_ack_in_dummy;
wire    regslice_both_gate_req_V_keep_V_U_vld_out;
wire    regslice_both_gate_req_V_strb_V_U_apdone_blk;
wire    regslice_both_gate_req_V_strb_V_U_ack_in_dummy;
wire    regslice_both_gate_req_V_strb_V_U_vld_out;
wire    regslice_both_gate_req_V_last_V_U_apdone_blk;
wire    regslice_both_gate_req_V_last_V_U_ack_in_dummy;
wire    regslice_both_gate_req_V_last_V_U_vld_out;
wire    regslice_both_gate_resp_V_data_V_U_apdone_blk;
wire   [31:0] gate_resp_TDATA_int_regslice;
wire    gate_resp_TVALID_int_regslice;
reg    gate_resp_TREADY_int_regslice;
wire    regslice_both_gate_resp_V_data_V_U_ack_in;
wire    regslice_both_gate_resp_V_keep_V_U_apdone_blk;
wire   [3:0] gate_resp_TKEEP_int_regslice;
wire    regslice_both_gate_resp_V_keep_V_U_vld_out;
wire    regslice_both_gate_resp_V_keep_V_U_ack_in;
wire    regslice_both_gate_resp_V_strb_V_U_apdone_blk;
wire   [3:0] gate_resp_TSTRB_int_regslice;
wire    regslice_both_gate_resp_V_strb_V_U_vld_out;
wire    regslice_both_gate_resp_V_strb_V_U_ack_in;
wire    regslice_both_gate_resp_V_last_V_U_apdone_blk;
wire   [0:0] gate_resp_TLAST_int_regslice;
wire    regslice_both_gate_resp_V_last_V_U_vld_out;
wire    regslice_both_gate_resp_V_last_V_U_ack_in;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_write_request_packet_fu_295_ap_start_reg = 1'b0;
end

secloc_shell_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .angleD(angleD),
    .angle_cos(angle_cos),
    .angle_sin(angle_sin),
    .position(position),
    .positionD(positionD),
    .target_equilibrium(target_equilibrium),
    .target_position(target_position),
    .angle(angle),
    .tick(tick),
    .log_base(log_base),
    .ref_period_ticks(ref_period_ticks),
    .dead_ang(dead_ang),
    .dead_pos(dead_pos),
    .control_flags(control_flags),
    .Q(beat_data_V_fu_144),
    .Q_ap_vld(Q_ap_vld),
    .status(beat_data_V_1_fu_148),
    .status_ap_vld(status_ap_vld),
    .update_count(beat_data_V_2_fu_152),
    .update_count_ap_vld(update_count_ap_vld),
    .nn_wait_cycles(beat_data_V_3_fu_156),
    .nn_wait_cycles_ap_vld(nn_wait_cycles_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

secloc_shell_write_request_packet grp_write_request_packet_fu_295(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_write_request_packet_fu_295_ap_start),
    .ap_done(grp_write_request_packet_fu_295_ap_done),
    .ap_idle(grp_write_request_packet_fu_295_ap_idle),
    .ap_ready(grp_write_request_packet_fu_295_ap_ready),
    .gate_req_TDATA(grp_write_request_packet_fu_295_gate_req_TDATA),
    .gate_req_TVALID(grp_write_request_packet_fu_295_gate_req_TVALID),
    .gate_req_TREADY(grp_write_request_packet_fu_295_gate_req_TREADY),
    .gate_req_TKEEP(grp_write_request_packet_fu_295_gate_req_TKEEP),
    .gate_req_TSTRB(grp_write_request_packet_fu_295_gate_req_TSTRB),
    .gate_req_TLAST(grp_write_request_packet_fu_295_gate_req_TLAST),
    .control_flags(control_flags_read_reg_415),
    .tick(tick_read_reg_440),
    .log_base(log_base_read_reg_435),
    .ref_period_ticks(ref_period_ticks_read_reg_430),
    .dead_ang(dead_ang_read_reg_425),
    .dead_pos(dead_pos_read_reg_420),
    .angle(angle_read_reg_445),
    .angleD(angleD_read_reg_480),
    .angle_cos(angle_cos_read_reg_475),
    .angle_sin(angle_sin_read_reg_470),
    .position(position_read_reg_465),
    .positionD(positionD_read_reg_460),
    .target_equilibrium(target_equilibrium_read_reg_455),
    .target_position(target_position_read_reg_450)
);

regslice_both #(
    .DataWidth( 32 ))
regslice_both_gate_req_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_write_request_packet_fu_295_gate_req_TDATA),
    .vld_in(grp_write_request_packet_fu_295_gate_req_TVALID),
    .ack_in(gate_req_TREADY_int_regslice),
    .data_out(gate_req_TDATA),
    .vld_out(regslice_both_gate_req_V_data_V_U_vld_out),
    .ack_out(gate_req_TREADY),
    .apdone_blk(regslice_both_gate_req_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_gate_req_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_write_request_packet_fu_295_gate_req_TKEEP),
    .vld_in(grp_write_request_packet_fu_295_gate_req_TVALID),
    .ack_in(regslice_both_gate_req_V_keep_V_U_ack_in_dummy),
    .data_out(gate_req_TKEEP),
    .vld_out(regslice_both_gate_req_V_keep_V_U_vld_out),
    .ack_out(gate_req_TREADY),
    .apdone_blk(regslice_both_gate_req_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_gate_req_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_write_request_packet_fu_295_gate_req_TSTRB),
    .vld_in(grp_write_request_packet_fu_295_gate_req_TVALID),
    .ack_in(regslice_both_gate_req_V_strb_V_U_ack_in_dummy),
    .data_out(gate_req_TSTRB),
    .vld_out(regslice_both_gate_req_V_strb_V_U_vld_out),
    .ack_out(gate_req_TREADY),
    .apdone_blk(regslice_both_gate_req_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_gate_req_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_write_request_packet_fu_295_gate_req_TLAST),
    .vld_in(grp_write_request_packet_fu_295_gate_req_TVALID),
    .ack_in(regslice_both_gate_req_V_last_V_U_ack_in_dummy),
    .data_out(gate_req_TLAST),
    .vld_out(regslice_both_gate_req_V_last_V_U_vld_out),
    .ack_out(gate_req_TREADY),
    .apdone_blk(regslice_both_gate_req_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 32 ))
regslice_both_gate_resp_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(gate_resp_TDATA),
    .vld_in(gate_resp_TVALID),
    .ack_in(regslice_both_gate_resp_V_data_V_U_ack_in),
    .data_out(gate_resp_TDATA_int_regslice),
    .vld_out(gate_resp_TVALID_int_regslice),
    .ack_out(gate_resp_TREADY_int_regslice),
    .apdone_blk(regslice_both_gate_resp_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_gate_resp_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(gate_resp_TKEEP),
    .vld_in(gate_resp_TVALID),
    .ack_in(regslice_both_gate_resp_V_keep_V_U_ack_in),
    .data_out(gate_resp_TKEEP_int_regslice),
    .vld_out(regslice_both_gate_resp_V_keep_V_U_vld_out),
    .ack_out(gate_resp_TREADY_int_regslice),
    .apdone_blk(regslice_both_gate_resp_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_gate_resp_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(gate_resp_TSTRB),
    .vld_in(gate_resp_TVALID),
    .ack_in(regslice_both_gate_resp_V_strb_V_U_ack_in),
    .data_out(gate_resp_TSTRB_int_regslice),
    .vld_out(regslice_both_gate_resp_V_strb_V_U_vld_out),
    .ack_out(gate_resp_TREADY_int_regslice),
    .apdone_blk(regslice_both_gate_resp_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_gate_resp_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(gate_resp_TLAST),
    .vld_in(gate_resp_TVALID),
    .ack_in(regslice_both_gate_resp_V_last_V_U_ack_in),
    .data_out(gate_resp_TLAST_int_regslice),
    .vld_out(regslice_both_gate_resp_V_last_V_U_vld_out),
    .ack_out(gate_resp_TREADY_int_regslice),
    .apdone_blk(regslice_both_gate_resp_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_write_request_packet_fu_295_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_write_request_packet_fu_295_ap_start_reg <= 1'b1;
        end else if ((grp_write_request_packet_fu_295_ap_ready == 1'b1)) begin
            grp_write_request_packet_fu_295_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0)) & (icmp_ln60_fu_335_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_284 <= add_ln60_fu_341_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_write_request_packet_fu_295_ap_done == 1'b1))) begin
        i_reg_284 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        angleD_read_reg_480 <= angleD;
        angle_cos_read_reg_475 <= angle_cos;
        angle_read_reg_445 <= angle;
        angle_sin_read_reg_470 <= angle_sin;
        control_flags_read_reg_415 <= control_flags;
        dead_ang_read_reg_425 <= dead_ang;
        dead_pos_read_reg_420 <= dead_pos;
        log_base_read_reg_435 <= log_base;
        positionD_read_reg_460 <= positionD;
        position_read_reg_465 <= position;
        ref_period_ticks_read_reg_430 <= ref_period_ticks;
        target_equilibrium_read_reg_455 <= target_equilibrium;
        target_position_read_reg_450 <= target_position;
        tick_read_reg_440 <= tick;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0)) & (icmp_ln60_fu_335_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (trunc_ln63_fu_351_p1 == 2'd1))) begin
        beat_data_V_1_fu_148 <= gate_resp_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0)) & (icmp_ln60_fu_335_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (trunc_ln63_fu_351_p1 == 2'd2))) begin
        beat_data_V_2_fu_152 <= gate_resp_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0)) & (icmp_ln60_fu_335_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (trunc_ln63_fu_351_p1 == 2'd3))) begin
        beat_data_V_3_fu_156 <= gate_resp_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0)) & (icmp_ln60_fu_335_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (trunc_ln63_fu_351_p1 == 2'd0))) begin
        beat_data_V_fu_144 <= gate_resp_TDATA_int_regslice;
    end
end

always @ (*) begin
    if (((regslice_both_gate_req_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        Q_ap_vld = 1'b1;
    end else begin
        Q_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_gate_req_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_gate_req_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_335_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        gate_resp_TDATA_blk_n = gate_resp_TVALID_int_regslice;
    end else begin
        gate_resp_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0)) & (icmp_ln60_fu_335_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        gate_resp_TREADY_int_regslice = 1'b1;
    end else begin
        gate_resp_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_gate_req_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        nn_wait_cycles_ap_vld = 1'b1;
    end else begin
        nn_wait_cycles_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_gate_req_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        status_ap_vld = 1'b1;
    end else begin
        status_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_gate_req_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        update_count_ap_vld = 1'b1;
    end else begin
        update_count_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_write_request_packet_fu_295_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0)) & (icmp_ln60_fu_335_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0)) & (icmp_ln60_fu_335_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((regslice_both_gate_req_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_fu_341_p2 = (i_reg_284 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state3 = ((icmp_ln60_fu_335_p2 == 1'd0) & (gate_resp_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign gate_req_TVALID = regslice_both_gate_req_V_data_V_U_vld_out;

assign gate_resp_TREADY = regslice_both_gate_resp_V_data_V_U_ack_in;

assign grp_write_request_packet_fu_295_ap_start = grp_write_request_packet_fu_295_ap_start_reg;

assign grp_write_request_packet_fu_295_gate_req_TREADY = (gate_req_TREADY_int_regslice & ap_CS_fsm_state2);

assign icmp_ln60_fu_335_p2 = ((i_reg_284 == 3'd4) ? 1'b1 : 1'b0);

assign trunc_ln63_fu_351_p1 = i_reg_284[1:0];

endmodule //secloc_shell
