// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module secloc_shell_write_request_packet (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        gate_req_TDATA,
        gate_req_TVALID,
        gate_req_TREADY,
        gate_req_TKEEP,
        gate_req_TSTRB,
        gate_req_TLAST,
        control_flags,
        tick,
        log_base,
        ref_period_ticks,
        dead_ang,
        dead_pos,
        angle,
        angleD,
        angle_cos,
        angle_sin,
        position,
        positionD,
        target_equilibrium,
        target_position
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_pp0_stage0 = 9'd128;
parameter    ap_ST_fsm_state10 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] gate_req_TDATA;
output   gate_req_TVALID;
input   gate_req_TREADY;
output  [3:0] gate_req_TKEEP;
output  [3:0] gate_req_TSTRB;
output  [0:0] gate_req_TLAST;
input  [31:0] control_flags;
input  [31:0] tick;
input  [31:0] log_base;
input  [31:0] ref_period_ticks;
input  [31:0] dead_ang;
input  [31:0] dead_pos;
input  [31:0] angle;
input  [31:0] angleD;
input  [31:0] angle_cos;
input  [31:0] angle_sin;
input  [31:0] position;
input  [31:0] positionD;
input  [31:0] target_equilibrium;
input  [31:0] target_position;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg gate_req_TVALID;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gate_req_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln44_reg_431;
reg   [3:0] i_reg_342;
wire   [0:0] icmp_ln44_fu_408_p2;
wire    ap_block_state8_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_state9_io;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] add_ln44_fu_414_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] last_fu_425_p2;
reg   [0:0] last_reg_440;
wire    ap_CS_fsm_state7;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state8;
reg   [3:0] words_V_address0;
reg    words_V_ce0;
reg    words_V_we0;
reg   [31:0] words_V_d0;
wire   [31:0] words_V_q0;
reg   [3:0] words_V_address1;
reg    words_V_ce1;
reg    words_V_we1;
reg   [31:0] words_V_d1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln44_fu_420_p1;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] bitcast_ln67_fu_353_p1;
wire   [31:0] bitcast_ln67_1_fu_358_p1;
wire   [31:0] bitcast_ln67_2_fu_363_p1;
wire   [31:0] bitcast_ln67_3_fu_368_p1;
wire   [31:0] bitcast_ln67_4_fu_373_p1;
wire   [31:0] bitcast_ln67_5_fu_378_p1;
wire   [31:0] bitcast_ln67_6_fu_383_p1;
wire   [31:0] bitcast_ln67_7_fu_388_p1;
wire   [31:0] bitcast_ln67_8_fu_393_p1;
wire   [31:0] bitcast_ln67_9_fu_398_p1;
wire   [31:0] bitcast_ln67_10_fu_403_p1;
wire    ap_CS_fsm_state10;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

secloc_shell_write_request_packet_words_V #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
words_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(words_V_address0),
    .ce0(words_V_ce0),
    .we0(words_V_we0),
    .d0(words_V_d0),
    .q0(words_V_q0),
    .address1(words_V_address1),
    .ce1(words_V_ce1),
    .we1(words_V_we1),
    .d1(words_V_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state8))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state8))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state8);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_reg_342 <= 4'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln44_fu_408_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_342 <= add_ln44_fu_414_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln44_reg_431 <= icmp_ln44_fu_408_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln44_fu_408_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        last_reg_440 <= last_fu_425_p2;
    end
end

always @ (*) begin
    if ((icmp_ln44_fu_408_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln44_reg_431 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gate_req_TDATA_blk_n = gate_req_TREADY;
    end else begin
        gate_req_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln44_reg_431 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gate_req_TVALID = 1'b1;
    end else begin
        gate_req_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        words_V_address0 = zext_ln44_fu_420_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        words_V_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        words_V_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        words_V_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        words_V_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        words_V_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        words_V_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        words_V_address0 = 64'd1;
    end else begin
        words_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        words_V_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        words_V_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        words_V_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        words_V_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        words_V_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        words_V_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        words_V_address1 = 64'd0;
    end else begin
        words_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        words_V_ce0 = 1'b1;
    end else begin
        words_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        words_V_ce1 = 1'b1;
    end else begin
        words_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        words_V_d0 = bitcast_ln67_10_fu_403_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        words_V_d0 = bitcast_ln67_8_fu_393_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        words_V_d0 = bitcast_ln67_6_fu_383_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        words_V_d0 = bitcast_ln67_4_fu_373_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        words_V_d0 = bitcast_ln67_2_fu_363_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        words_V_d0 = ref_period_ticks;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        words_V_d0 = tick;
    end else begin
        words_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        words_V_d1 = bitcast_ln67_9_fu_398_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        words_V_d1 = bitcast_ln67_7_fu_388_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        words_V_d1 = bitcast_ln67_5_fu_378_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        words_V_d1 = bitcast_ln67_3_fu_368_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        words_V_d1 = bitcast_ln67_1_fu_358_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        words_V_d1 = bitcast_ln67_fu_353_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        words_V_d1 = control_flags;
    end else begin
        words_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        words_V_we0 = 1'b1;
    end else begin
        words_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        words_V_we1 = 1'b1;
    end else begin
        words_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln44_fu_408_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln44_fu_408_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln44_fu_414_p2 = (i_reg_342 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_io));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_io));
end

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((icmp_ln44_reg_431 == 1'd0) & (gate_req_TREADY == 1'b0));
end

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bitcast_ln67_10_fu_403_p1 = target_position;

assign bitcast_ln67_1_fu_358_p1 = dead_ang;

assign bitcast_ln67_2_fu_363_p1 = dead_pos;

assign bitcast_ln67_3_fu_368_p1 = angle;

assign bitcast_ln67_4_fu_373_p1 = angleD;

assign bitcast_ln67_5_fu_378_p1 = angle_cos;

assign bitcast_ln67_6_fu_383_p1 = angle_sin;

assign bitcast_ln67_7_fu_388_p1 = position;

assign bitcast_ln67_8_fu_393_p1 = positionD;

assign bitcast_ln67_9_fu_398_p1 = target_equilibrium;

assign bitcast_ln67_fu_353_p1 = log_base;

assign gate_req_TDATA = words_V_q0;

assign gate_req_TKEEP = 4'd15;

assign gate_req_TLAST = last_reg_440;

assign gate_req_TSTRB = 4'd15;

assign icmp_ln44_fu_408_p2 = ((i_reg_342 == 4'd14) ? 1'b1 : 1'b0);

assign last_fu_425_p2 = ((i_reg_342 == 4'd13) ? 1'b1 : 1'b0);

assign zext_ln44_fu_420_p1 = i_reg_342;

endmodule //secloc_shell_write_request_packet
