// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module median_filter_get_filtered_value (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        newValue,
        window_size,
        trim_count,
        filter_mode,
        rail_low,
        rail_high,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_pp0_stage0 = 9'd8;
parameter    ap_ST_fsm_state8 = 9'd16;
parameter    ap_ST_fsm_state9 = 9'd32;
parameter    ap_ST_fsm_state10 = 9'd64;
parameter    ap_ST_fsm_pp1_stage0 = 9'd128;
parameter    ap_ST_fsm_state13 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] newValue;
input  [15:0] window_size;
input  [15:0] trim_count;
input  [15:0] filter_mode;
input  [15:0] rail_low;
input  [15:0] rail_high;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] lastWindowSize;
reg   [15:0] currentWindowSize;
reg   [15:0] bufferIndex;
wire   [5:0] buffer_r_address0;
reg    buffer_r_ce0;
reg    buffer_r_we0;
wire   [15:0] buffer_r_q0;
reg   [5:0] window_address0;
reg    window_ce0;
reg    window_we0;
wire   [15:0] window_q0;
reg   [5:0] window_address1;
reg    window_ce1;
wire   [15:0] window_q1;
reg   [6:0] i_reg_251;
reg   [6:0] i_reg_251_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] c_3_reg_263;
reg   [15:0] b_3_reg_273;
reg   [15:0] a_reg_284;
reg   [4:0] bit_reg_297;
reg   [30:0] remainder_reg_308;
reg   [31:0] quotient_reg_319;
wire   [15:0] filter_mode_read_read_fu_164_p2;
wire   [15:0] zext_ln24_fu_394_p1;
reg   [15:0] zext_ln24_reg_1411;
wire   [16:0] zext_ln39_fu_398_p1;
reg   [16:0] zext_ln39_reg_1416;
wire   [14:0] select_ln54_fu_434_p3;
reg   [14:0] select_ln54_reg_1476;
wire   [0:0] removal_fu_472_p2;
reg   [0:0] removal_reg_1482;
wire    ap_CS_fsm_state2;
wire  signed [15:0] n_out_fu_523_p3;
reg  signed [15:0] n_out_reg_1493;
wire   [0:0] trunc_ln57_fu_531_p1;
reg   [0:0] trunc_ln57_reg_1499;
wire  signed [16:0] sext_ln57_fu_535_p1;
reg  signed [16:0] sext_ln57_reg_1503;
reg   [15:0] trunc_ln63_1_reg_1510;
reg   [0:0] tmp_3_reg_1515;
reg   [14:0] trunc_ln64_2_reg_1520;
reg   [15:0] oldValue_reg_1525;
wire    ap_CS_fsm_state3;
wire   [15:0] mid_lo_fu_638_p3;
reg   [15:0] mid_lo_reg_1531;
wire   [15:0] first_index_fu_646_p3;
reg   [15:0] first_index_reg_1536;
wire   [15:0] last_index_fu_654_p2;
reg   [15:0] last_index_reg_1542;
wire   [15:0] mid_hi_fu_683_p3;
reg   [15:0] mid_hi_reg_1548;
wire   [0:0] icmp_ln82_fu_690_p2;
reg   [0:0] icmp_ln82_reg_1563;
reg   [0:0] icmp_ln82_reg_1563_pp0_iter1_reg;
wire   [6:0] add_ln82_fu_696_p2;
reg   [6:0] add_ln82_reg_1567;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln87_fu_747_p2;
reg   [0:0] icmp_ln87_reg_1577;
reg   [0:0] icmp_ln87_reg_1577_pp0_iter1_reg;
reg   [0:0] icmp_ln87_reg_1577_pp0_iter2_reg;
wire   [0:0] valid_m1_fu_762_p2;
reg   [0:0] valid_m1_reg_1581;
wire   [0:0] valid_0_fu_768_p2;
reg   [0:0] valid_0_reg_1586;
wire   [0:0] valid_p1_fu_784_p2;
reg   [0:0] valid_p1_reg_1592;
wire   [0:0] icmp_ln125_fu_790_p2;
reg   [0:0] icmp_ln125_reg_1598;
reg   [0:0] icmp_ln125_reg_1598_pp0_iter1_reg;
reg   [0:0] icmp_ln125_reg_1598_pp0_iter2_reg;
wire   [0:0] icmp_ln125_1_fu_795_p2;
reg   [0:0] icmp_ln125_1_reg_1603;
reg   [0:0] icmp_ln125_1_reg_1603_pp0_iter1_reg;
reg   [0:0] icmp_ln125_1_reg_1603_pp0_iter2_reg;
wire   [0:0] icmp_ln128_fu_800_p2;
reg   [0:0] icmp_ln128_reg_1608;
reg   [0:0] icmp_ln128_reg_1608_pp0_iter1_reg;
wire   [0:0] icmp_ln131_fu_805_p2;
reg   [0:0] icmp_ln131_reg_1613;
reg   [0:0] icmp_ln131_reg_1613_pp0_iter1_reg;
reg   [15:0] d_reg_1618;
reg    ap_enable_reg_pp0_iter1;
wire   [0:0] skip_now_fu_847_p2;
reg   [0:0] skip_now_reg_1623;
wire   [0:0] cand_valid_fu_852_p3;
reg   [0:0] cand_valid_reg_1629;
wire   [0:0] select_ln108_fu_858_p3;
reg   [0:0] select_ln108_reg_1634;
wire   [0:0] take_new_2_fu_872_p2;
reg   [0:0] take_new_2_reg_1639;
wire   [0:0] skip_now_2_fu_883_p2;
reg   [0:0] skip_now_2_reg_1645;
wire   [0:0] take_new_fu_893_p2;
reg   [0:0] take_new_reg_1651;
reg   [15:0] med_lo_2_reg_1657;
reg    ap_enable_reg_pp0_iter2;
wire   [15:0] out_5_fu_1029_p3;
reg   [15:0] out_5_reg_1663;
wire   [0:0] icmp_ln137_fu_1052_p2;
reg   [0:0] icmp_ln137_reg_1668;
wire   [0:0] icmp_ln137_1_fu_1057_p2;
reg   [0:0] icmp_ln137_1_reg_1673;
wire  signed [15:0] kept_count_fu_1149_p2;
reg  signed [15:0] kept_count_reg_1678;
wire    ap_CS_fsm_state8;
wire  signed [31:0] sext_ln160_fu_1157_p1;
reg  signed [31:0] sext_ln160_reg_1687;
wire    ap_CS_fsm_state9;
wire  signed [30:0] sext_ln160_2_fu_1160_p1;
reg  signed [30:0] sext_ln160_2_reg_1692;
wire   [22:0] numerator_fu_1228_p2;
reg   [22:0] numerator_reg_1697;
wire    ap_CS_fsm_state10;
wire   [22:0] zext_ln161_fu_1257_p1;
reg   [22:0] zext_ln161_reg_1707;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state11_pp1_stage0_iter0;
wire    ap_block_state12_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [0:0] trunc_ln165_1_fu_1266_p1;
reg   [0:0] trunc_ln165_1_reg_1712;
wire   [0:0] tmp_6_fu_1280_p3;
reg   [0:0] tmp_6_reg_1718;
wire   [4:0] add_ln163_fu_1288_p2;
reg   [4:0] add_ln163_reg_1722;
reg    ap_enable_reg_pp1_iter0;
wire   [22:0] or_ln166_fu_1339_p2;
reg   [22:0] or_ln166_reg_1727;
reg    ap_enable_reg_pp1_iter1;
wire   [31:0] quotient_1_fu_1355_p3;
wire   [30:0] remainder_3_fu_1363_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_condition_pp0_exit_iter2_state6;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_flush_enable;
reg   [15:0] n_old_reg_228;
wire   [0:0] icmp_ln39_fu_406_p2;
reg  signed [15:0] bufferIndex_loc_0_reg_240;
reg   [6:0] ap_phi_mux_i_phi_fu_255_p4;
wire    ap_block_pp0_stage0;
reg   [15:0] ap_phi_mux_c_3_phi_fu_266_p4;
reg   [15:0] ap_phi_mux_b_3_phi_fu_276_p4;
reg   [15:0] ap_phi_mux_a_phi_fu_288_p4;
reg   [4:0] ap_phi_mux_bit_phi_fu_301_p4;
wire    ap_block_pp1_stage0;
reg   [15:0] ap_phi_mux_retval_0_phi_fu_333_p8;
reg   [15:0] retval_0_reg_330;
wire   [15:0] trunc_ln171_fu_1371_p1;
wire    ap_CS_fsm_state13;
wire   [63:0] zext_ln46_fu_477_p1;
wire   [63:0] zext_ln85_fu_742_p1;
wire   [63:0] zext_ln82_fu_902_p1;
wire   [6:0] select_ln10_1_fu_386_p3;
wire   [15:0] select_ln48_fu_509_p3;
reg   [15:0] med_lo_fu_128;
wire   [15:0] med_lo_3_fu_1038_p3;
reg   [31:0] sum_fu_132;
wire   [31:0] sum_2_fu_1101_p3;
reg   [15:0] med_hi_fu_136;
wire   [15:0] med_hi_2_fu_1045_p3;
reg   [15:0] rail_hits_fu_140;
wire   [15:0] select_ln137_fu_1131_p3;
reg   [0:0] skip_done_fu_144;
wire   [0:0] skip_done_3_fu_993_p3;
reg   [0:0] inserted_fu_148;
wire   [0:0] inserted_2_fu_1007_p2;
wire   [0:0] icmp_ln10_fu_360_p2;
wire   [0:0] icmp_ln13_fu_366_p2;
wire   [0:0] or_ln10_fu_380_p2;
wire   [6:0] select_ln10_fu_372_p3;
wire   [6:0] trunc_ln24_1_fu_356_p1;
wire   [0:0] tmp_1_fu_426_p3;
wire   [14:0] trunc_ln24_fu_352_p1;
wire  signed [16:0] sext_ln48_fu_482_p1;
wire   [16:0] add_ln48_fu_486_p2;
wire   [0:0] icmp_ln48_fu_492_p2;
wire   [0:0] xor_ln48_fu_497_p2;
wire   [15:0] add_ln48_1_fu_503_p2;
wire   [15:0] add_ln51_fu_517_p2;
wire   [16:0] sub_ln63_fu_539_p2;
wire   [15:0] shl_ln_fu_588_p3;
wire   [16:0] zext_ln57_fu_595_p1;
wire   [0:0] icmp_ln57_fu_599_p2;
wire   [16:0] add_ln63_fu_610_p2;
wire   [0:0] tmp_2_fu_615_p3;
wire   [15:0] sub_ln63_1_fu_623_p2;
wire   [15:0] trunc_ln63_2_fu_628_p4;
wire   [0:0] xor_ln57_fu_604_p2;
wire   [15:0] zext_ln24_1_fu_585_p1;
wire   [16:0] sub_ln64_fu_659_p2;
wire   [15:0] trunc_ln64_1_fu_664_p4;
wire   [15:0] sub_ln64_1_fu_677_p2;
wire  signed [15:0] sext_ln64_fu_674_p1;
wire   [5:0] trunc_ln84_fu_702_p1;
wire   [6:0] zext_ln84_1_fu_710_p1;
wire   [6:0] add_ln84_fu_714_p2;
wire   [0:0] tmp_4_fu_720_p3;
wire   [5:0] add_ln84_1_fu_728_p2;
wire   [5:0] prefetch_idx_fu_734_p3;
wire   [15:0] zext_ln84_fu_706_p1;
wire   [6:0] add_ln94_fu_752_p2;
wire  signed [15:0] sext_ln94_fu_758_p1;
wire   [6:0] add_ln96_fu_774_p2;
wire   [15:0] zext_ln96_fu_780_p1;
wire   [0:0] icmp_ln100_fu_820_p2;
wire   [0:0] icmp_ln101_fu_831_p2;
wire   [0:0] eq_b_fu_815_p2;
wire   [0:0] and_ln106_fu_842_p2;
wire   [0:0] le_c_fu_836_p2;
wire   [0:0] le_b_fu_825_p2;
wire   [0:0] xor_ln108_fu_866_p2;
wire   [0:0] eq_a_fu_810_p2;
wire   [0:0] and_ln113_fu_878_p2;
wire   [0:0] xor_ln117_fu_888_p2;
wire   [15:0] select_ln109_fu_919_p3;
wire   [0:0] xor_ln111_fu_932_p2;
wire   [0:0] and_ln111_fu_937_p2;
wire   [0:0] xor_ln112_fu_960_p2;
wire   [0:0] sel_tmp6_fu_972_p2;
wire   [0:0] or_ln104_fu_913_p2;
wire   [0:0] skip_done_1_fu_942_p2;
wire   [0:0] newSel_fu_978_p3;
wire   [0:0] newSel31_fu_985_p3;
wire   [0:0] select_ln104_fu_1001_p3;
wire   [15:0] select_ln118_fu_954_p3;
wire   [15:0] out_fu_926_p3;
wire   [0:0] and_ln112_fu_966_p2;
wire   [15:0] out_1_fu_947_p3;
wire   [15:0] out_2_fu_1013_p3;
wire   [15:0] out_3_fu_1021_p3;
wire   [0:0] xor_ln125_fu_1082_p2;
wire   [31:0] zext_ln126_fu_1092_p1;
wire   [0:0] and_ln125_fu_1087_p2;
wire   [31:0] sum_1_fu_1095_p2;
wire   [0:0] xor_ln137_fu_1109_p2;
wire   [0:0] xor_ln137_1_fu_1114_p2;
wire   [0:0] or_ln137_fu_1119_p2;
wire   [15:0] rail_hits_1_fu_1125_p2;
wire  signed [16:0] sext_ln160_1_fu_1163_p1;
wire   [16:0] sub_ln160_fu_1173_p2;
wire   [15:0] lshr_ln160_1_fu_1179_p4;
wire   [16:0] zext_ln160_fu_1189_p1;
wire   [14:0] trunc_ln160_1_fu_1199_p4;
wire  signed [15:0] sext_ln160_3_fu_1208_p1;
wire   [0:0] tmp_5_fu_1166_p3;
wire   [16:0] sub_ln160_1_fu_1193_p2;
wire   [16:0] zext_ln160_1_fu_1212_p1;
wire   [16:0] select_ln160_fu_1216_p3;
wire   [22:0] trunc_ln82_fu_1153_p1;
wire  signed [22:0] sext_ln160_4_fu_1224_p1;
wire   [16:0] zext_ln153_1_fu_1237_p1;
wire   [16:0] zext_ln153_fu_1234_p1;
wire   [16:0] add_ln153_fu_1241_p2;
wire   [22:0] lshr_ln165_fu_1261_p2;
wire   [5:0] zext_ln163_fu_1270_p1;
wire   [5:0] bit_1_fu_1274_p2;
wire   [29:0] trunc_ln165_fu_1294_p1;
wire   [31:0] remainder_1_fu_1298_p3;
wire   [30:0] or_ln_fu_1305_p3;
wire   [0:0] icmp_ln166_fu_1312_p2;
wire   [22:0] shl_ln168_fu_1322_p2;
wire   [22:0] trunc_ln166_fu_1335_p1;
wire   [22:0] select_ln166_fu_1327_p3;
wire   [8:0] tmp_fu_1345_p4;
wire   [30:0] remainder_2_fu_1317_p2;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [8:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_block_pp1;
reg    ap_enable_operation_109;
reg    ap_enable_state4_pp0_iter0_stage0;
reg    ap_enable_operation_127;
reg    ap_enable_state5_pp0_iter1_stage0;
reg    ap_predicate_op172_store_state6;
reg    ap_enable_operation_172;
reg    ap_enable_state6_pp0_iter2_stage0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 lastWindowSize = 7'd0;
#0 currentWindowSize = 16'd0;
#0 bufferIndex = 16'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
end

median_filter_get_filtered_value_buffer_r #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buffer_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buffer_r_address0),
    .ce0(buffer_r_ce0),
    .we0(buffer_r_we0),
    .d0(newValue),
    .q0(buffer_r_q0)
);

median_filter_get_filtered_value_window #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
window_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(window_address0),
    .ce0(window_ce0),
    .we0(window_we0),
    .d0(out_5_fu_1029_p3),
    .q0(window_q0),
    .address1(window_address1),
    .ce1(window_ce1),
    .q1(window_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter2_state6)))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter2_state6))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 16'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_return_0_preg <= ap_phi_mux_retval_0_phi_fu_333_p8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 16'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_return_1_preg <= rail_hits_fu_140;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        a_reg_284 <= b_3_reg_273;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        a_reg_284 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        b_3_reg_273 <= c_3_reg_263;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        b_3_reg_273 <= window_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (tmp_6_reg_1718 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        bit_reg_297 <= add_ln163_reg_1722;
    end else if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        bit_reg_297 <= 5'd22;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        if ((icmp_ln39_fu_406_p2 == 1'd0)) begin
            bufferIndex_loc_0_reg_240 <= 16'd0;
        end else if ((icmp_ln39_fu_406_p2 == 1'd1)) begin
            bufferIndex_loc_0_reg_240 <= bufferIndex;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        c_3_reg_263 <= d_reg_1618;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_3_reg_263 <= window_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln82_reg_1563 == 1'd0))) begin
        i_reg_251 <= add_ln82_reg_1567;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_251 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln87_reg_1577_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        inserted_fu_148 <= inserted_2_fu_1007_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        inserted_fu_148 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln87_reg_1577_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        med_hi_fu_136 <= med_hi_2_fu_1045_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        med_hi_fu_136 <= newValue;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln87_reg_1577_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        med_lo_fu_128 <= med_lo_3_fu_1038_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        med_lo_fu_128 <= newValue;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        if ((icmp_ln39_fu_406_p2 == 1'd0)) begin
            n_old_reg_228 <= 16'd0;
        end else if ((icmp_ln39_fu_406_p2 == 1'd1)) begin
            n_old_reg_228 <= currentWindowSize;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (tmp_6_reg_1718 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        quotient_reg_319 <= quotient_1_fu_1355_p3;
    end else if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        quotient_reg_319 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln87_reg_1577_pp0_iter2_reg == 1'd1))) begin
        rail_hits_fu_140 <= select_ln137_fu_1131_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        rail_hits_fu_140 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (tmp_6_reg_1718 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        remainder_reg_308 <= remainder_3_fu_1363_p3;
    end else if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        remainder_reg_308 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        retval_0_reg_330 <= trunc_ln171_fu_1371_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) & (trunc_ln57_reg_1499 == 1'd1) & (filter_mode_read_read_fu_164_p2 == 16'd1))) begin
        retval_0_reg_330 <= med_lo_2_reg_1657;
    end else if (((1'b1 == ap_CS_fsm_state9) & (filter_mode_read_read_fu_164_p2 == 16'd0))) begin
        retval_0_reg_330 <= newValue;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        retval_0_reg_330 <= {{add_ln153_fu_1241_p2[16:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln87_reg_1577_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        skip_done_fu_144 <= skip_done_3_fu_993_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        skip_done_fu_144 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln87_reg_1577_pp0_iter2_reg == 1'd1))) begin
        sum_fu_132 <= sum_2_fu_1101_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sum_fu_132 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        add_ln163_reg_1722 <= add_ln163_fu_1288_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        add_ln82_reg_1567 <= add_ln82_fu_696_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bufferIndex <= select_ln48_fu_509_p3;
        currentWindowSize <= n_out_fu_523_p3;
        n_out_reg_1493 <= n_out_fu_523_p3;
        removal_reg_1482 <= removal_fu_472_p2;
        sext_ln57_reg_1503 <= sext_ln57_fu_535_p1;
        tmp_3_reg_1515 <= n_out_fu_523_p3[32'd15];
        trunc_ln57_reg_1499 <= trunc_ln57_fu_531_p1;
        trunc_ln63_1_reg_1510 <= {{sub_ln63_fu_539_p2[16:1]}};
        trunc_ln64_2_reg_1520 <= {{n_out_fu_523_p3[15:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln87_reg_1577 == 1'd1) & (icmp_ln82_reg_1563 == 1'd0))) begin
        cand_valid_reg_1629 <= cand_valid_fu_852_p3;
        select_ln108_reg_1634 <= select_ln108_fu_858_p3;
        skip_now_2_reg_1645 <= skip_now_2_fu_883_p2;
        skip_now_reg_1623 <= skip_now_fu_847_p2;
        take_new_2_reg_1639 <= take_new_2_fu_872_p2;
        take_new_reg_1651 <= take_new_fu_893_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln82_reg_1563 == 1'd0))) begin
        d_reg_1618 <= window_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        first_index_reg_1536 <= first_index_fu_646_p3;
        last_index_reg_1542 <= last_index_fu_654_p2;
        mid_hi_reg_1548 <= mid_hi_fu_683_p3;
        mid_lo_reg_1531 <= mid_lo_fu_638_p3;
        oldValue_reg_1525 <= buffer_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_251_pp0_iter1_reg <= i_reg_251;
        icmp_ln125_1_reg_1603_pp0_iter1_reg <= icmp_ln125_1_reg_1603;
        icmp_ln125_reg_1598_pp0_iter1_reg <= icmp_ln125_reg_1598;
        icmp_ln128_reg_1608_pp0_iter1_reg <= icmp_ln128_reg_1608;
        icmp_ln131_reg_1613_pp0_iter1_reg <= icmp_ln131_reg_1613;
        icmp_ln82_reg_1563 <= icmp_ln82_fu_690_p2;
        icmp_ln82_reg_1563_pp0_iter1_reg <= icmp_ln82_reg_1563;
        icmp_ln87_reg_1577_pp0_iter1_reg <= icmp_ln87_reg_1577;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln87_fu_747_p2 == 1'd1) & (icmp_ln82_fu_690_p2 == 1'd0))) begin
        icmp_ln125_1_reg_1603 <= icmp_ln125_1_fu_795_p2;
        icmp_ln125_reg_1598 <= icmp_ln125_fu_790_p2;
        icmp_ln128_reg_1608 <= icmp_ln128_fu_800_p2;
        icmp_ln131_reg_1613 <= icmp_ln131_fu_805_p2;
        valid_0_reg_1586 <= valid_0_fu_768_p2;
        valid_m1_reg_1581 <= valid_m1_fu_762_p2;
        valid_p1_reg_1592 <= valid_p1_fu_784_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln125_1_reg_1603_pp0_iter2_reg <= icmp_ln125_1_reg_1603_pp0_iter1_reg;
        icmp_ln125_reg_1598_pp0_iter2_reg <= icmp_ln125_reg_1598_pp0_iter1_reg;
        icmp_ln87_reg_1577_pp0_iter2_reg <= icmp_ln87_reg_1577_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln87_reg_1577_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        icmp_ln137_1_reg_1673 <= icmp_ln137_1_fu_1057_p2;
        icmp_ln137_reg_1668 <= icmp_ln137_fu_1052_p2;
        out_5_reg_1663 <= out_5_fu_1029_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln82_fu_690_p2 == 1'd0))) begin
        icmp_ln87_reg_1577 <= icmp_ln87_fu_747_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kept_count_reg_1678 <= kept_count_fu_1149_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_406_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        lastWindowSize <= select_ln10_1_fu_386_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        med_lo_2_reg_1657 <= med_lo_fu_128;
    end
end

always @ (posedge ap_clk) begin
    if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        numerator_reg_1697 <= numerator_fu_1228_p2;
        sext_ln160_2_reg_1692 <= sext_ln160_2_fu_1160_p1;
        sext_ln160_reg_1687 <= sext_ln160_fu_1157_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        or_ln166_reg_1727 <= or_ln166_fu_1339_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        select_ln54_reg_1476 <= select_ln54_fu_434_p3;
        zext_ln24_reg_1411[6 : 0] <= zext_ln24_fu_394_p1[6 : 0];
        zext_ln39_reg_1416[6 : 0] <= zext_ln39_fu_398_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        tmp_6_reg_1718 <= bit_1_fu_1274_p2[32'd5];
        trunc_ln165_1_reg_1712 <= trunc_ln165_1_fu_1266_p1;
        zext_ln161_reg_1707[4 : 0] <= zext_ln161_fu_1257_p1[4 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln82_fu_690_p2 == 1'd1))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_subdone) & (tmp_6_fu_1280_p3 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_a_phi_fu_288_p4 = b_3_reg_273;
    end else begin
        ap_phi_mux_a_phi_fu_288_p4 = a_reg_284;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_b_3_phi_fu_276_p4 = c_3_reg_263;
    end else begin
        ap_phi_mux_b_3_phi_fu_276_p4 = b_3_reg_273;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (tmp_6_reg_1718 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_bit_phi_fu_301_p4 = add_ln163_reg_1722;
    end else begin
        ap_phi_mux_bit_phi_fu_301_p4 = bit_reg_297;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_c_3_phi_fu_266_p4 = d_reg_1618;
    end else begin
        ap_phi_mux_c_3_phi_fu_266_p4 = c_3_reg_263;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln82_reg_1563 == 1'd0))) begin
        ap_phi_mux_i_phi_fu_255_p4 = add_ln82_reg_1567;
    end else begin
        ap_phi_mux_i_phi_fu_255_p4 = i_reg_251;
    end
end

always @ (*) begin
    if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_phi_mux_retval_0_phi_fu_333_p8 = trunc_ln171_fu_1371_p1;
    end else begin
        ap_phi_mux_retval_0_phi_fu_333_p8 = retval_0_reg_330;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_return_0 = ap_phi_mux_retval_0_phi_fu_333_p8;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_return_1 = rail_hits_fu_140;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        buffer_r_ce0 = 1'b1;
    end else begin
        buffer_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        buffer_r_we0 = 1'b1;
    end else begin
        buffer_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        window_address0 = zext_ln82_fu_902_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        window_address0 = 6'd1;
    end else begin
        window_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        window_address1 = zext_ln85_fu_742_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        window_address1 = 6'd0;
    end else begin
        window_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        window_ce0 = 1'b1;
    end else begin
        window_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
        window_ce1 = 1'b1;
    end else begin
        window_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln87_reg_1577_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0))) begin
        window_we0 = 1'b1;
    end else begin
        window_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if ((~(filter_mode_read_read_fu_164_p2 == 16'd1) & ~(filter_mode_read_read_fu_164_p2 == 16'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b1 == ap_CS_fsm_state9) & (trunc_ln57_reg_1499 == 1'd0) & (filter_mode_read_read_fu_164_p2 == 16'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln153_fu_1241_p2 = (zext_ln153_1_fu_1237_p1 + zext_ln153_fu_1234_p1);

assign add_ln163_fu_1288_p2 = ($signed(5'd31) + $signed(ap_phi_mux_bit_phi_fu_301_p4));

assign add_ln48_1_fu_503_p2 = ($signed(16'd1) + $signed(bufferIndex_loc_0_reg_240));

assign add_ln48_fu_486_p2 = ($signed(17'd1) + $signed(sext_ln48_fu_482_p1));

assign add_ln51_fu_517_p2 = (16'd1 + n_old_reg_228);

assign add_ln63_fu_610_p2 = ($signed(17'd131071) + $signed(sext_ln57_reg_1503));

assign add_ln82_fu_696_p2 = (ap_phi_mux_i_phi_fu_255_p4 + 7'd1);

assign add_ln84_1_fu_728_p2 = (6'd2 + trunc_ln84_fu_702_p1);

assign add_ln84_fu_714_p2 = (7'd2 + zext_ln84_1_fu_710_p1);

assign add_ln94_fu_752_p2 = ($signed(zext_ln84_1_fu_710_p1) + $signed(7'd127));

assign add_ln96_fu_774_p2 = (zext_ln84_1_fu_710_p1 + 7'd1);

assign and_ln106_fu_842_p2 = (removal_reg_1482 & eq_b_fu_815_p2);

assign and_ln111_fu_937_p2 = (xor_ln111_fu_932_p2 & skip_now_reg_1623);

assign and_ln112_fu_966_p2 = (xor_ln112_fu_960_p2 & inserted_fu_148);

assign and_ln113_fu_878_p2 = (removal_reg_1482 & eq_a_fu_810_p2);

assign and_ln125_fu_1087_p2 = (xor_ln125_fu_1082_p2 & icmp_ln125_1_reg_1603_pp0_iter2_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1 = ((1'b1 == ap_block_pp1_stage0_subdone) & (ap_ST_fsm_pp1_stage0 == ap_CS_fsm));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_109 = (icmp_ln82_fu_690_p2 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_127 = (icmp_ln82_reg_1563 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_172 = (ap_predicate_op172_store_state6 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter0_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state6_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op172_store_state6 = ((icmp_ln87_reg_1577_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_1563_pp0_iter1_reg == 1'd0));
end

assign bit_1_fu_1274_p2 = ($signed(6'd63) + $signed(zext_ln163_fu_1270_p1));

assign buffer_r_address0 = zext_ln46_fu_477_p1;

assign cand_valid_fu_852_p3 = ((skip_now_fu_847_p2[0:0] === 1'b1) ? valid_p1_reg_1592 : valid_0_reg_1586);

assign eq_a_fu_810_p2 = ((ap_phi_mux_a_phi_fu_288_p4 == oldValue_reg_1525) ? 1'b1 : 1'b0);

assign eq_b_fu_815_p2 = ((ap_phi_mux_b_3_phi_fu_276_p4 == oldValue_reg_1525) ? 1'b1 : 1'b0);

assign filter_mode_read_read_fu_164_p2 = filter_mode;

assign first_index_fu_646_p3 = ((xor_ln57_fu_604_p2[0:0] === 1'b1) ? mid_lo_fu_638_p3 : zext_ln24_1_fu_585_p1);

assign icmp_ln100_fu_820_p2 = ((ap_phi_mux_b_3_phi_fu_276_p4 < newValue) ? 1'b1 : 1'b0);

assign icmp_ln101_fu_831_p2 = ((ap_phi_mux_c_3_phi_fu_266_p4 < newValue) ? 1'b1 : 1'b0);

assign icmp_ln10_fu_360_p2 = (($signed(window_size) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign icmp_ln125_1_fu_795_p2 = (($signed(zext_ln84_fu_706_p1) < $signed(last_index_reg_1542)) ? 1'b1 : 1'b0);

assign icmp_ln125_fu_790_p2 = (($signed(zext_ln84_fu_706_p1) < $signed(first_index_reg_1536)) ? 1'b1 : 1'b0);

assign icmp_ln128_fu_800_p2 = ((zext_ln84_fu_706_p1 == mid_lo_reg_1531) ? 1'b1 : 1'b0);

assign icmp_ln131_fu_805_p2 = ((zext_ln84_fu_706_p1 == mid_hi_reg_1548) ? 1'b1 : 1'b0);

assign icmp_ln137_1_fu_1057_p2 = ((out_5_fu_1029_p3 < rail_high) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_1052_p2 = ((rail_low < out_5_fu_1029_p3) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_366_p2 = (($signed(window_size) > $signed(16'd64)) ? 1'b1 : 1'b0);

assign icmp_ln166_fu_1312_p2 = ((remainder_1_fu_1298_p3 < sext_ln160_reg_1687) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_406_p2 = ((select_ln10_1_fu_386_p3 == lastWindowSize) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_492_p2 = (($signed(add_ln48_fu_486_p2) < $signed(zext_ln39_reg_1416)) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_599_p2 = (($signed(zext_ln57_fu_595_p1) < $signed(sext_ln57_reg_1503)) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_690_p2 = ((ap_phi_mux_i_phi_fu_255_p4 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_747_p2 = (($signed(zext_ln84_fu_706_p1) < $signed(n_out_reg_1493)) ? 1'b1 : 1'b0);

assign inserted_2_fu_1007_p2 = (select_ln104_fu_1001_p3 | inserted_fu_148);

assign kept_count_fu_1149_p2 = (last_index_reg_1542 - first_index_reg_1536);

assign last_index_fu_654_p2 = ($signed(n_out_reg_1493) - $signed(first_index_fu_646_p3));

assign le_b_fu_825_p2 = (icmp_ln100_fu_820_p2 ^ 1'd1);

assign le_c_fu_836_p2 = (icmp_ln101_fu_831_p2 ^ 1'd1);

assign lshr_ln160_1_fu_1179_p4 = {{sub_ln160_fu_1173_p2[16:1]}};

assign lshr_ln165_fu_1261_p2 = numerator_reg_1697 >> zext_ln161_fu_1257_p1;

assign med_hi_2_fu_1045_p3 = ((icmp_ln131_reg_1613_pp0_iter1_reg[0:0] === 1'b1) ? out_5_fu_1029_p3 : med_hi_fu_136);

assign med_lo_3_fu_1038_p3 = ((icmp_ln128_reg_1608_pp0_iter1_reg[0:0] === 1'b1) ? out_5_fu_1029_p3 : med_lo_fu_128);

assign mid_hi_fu_683_p3 = ((tmp_3_reg_1515[0:0] === 1'b1) ? sub_ln64_1_fu_677_p2 : sext_ln64_fu_674_p1);

assign mid_lo_fu_638_p3 = ((tmp_2_fu_615_p3[0:0] === 1'b1) ? sub_ln63_1_fu_623_p2 : trunc_ln63_2_fu_628_p4);

assign n_out_fu_523_p3 = ((removal_fu_472_p2[0:0] === 1'b1) ? n_old_reg_228 : add_ln51_fu_517_p2);

assign newSel31_fu_985_p3 = ((or_ln104_fu_913_p2[0:0] === 1'b1) ? skip_done_fu_144 : skip_done_1_fu_942_p2);

assign newSel_fu_978_p3 = ((sel_tmp6_fu_972_p2[0:0] === 1'b1) ? skip_done_fu_144 : skip_now_2_reg_1645);

assign numerator_fu_1228_p2 = ($signed(trunc_ln82_fu_1153_p1) + $signed(sext_ln160_4_fu_1224_p1));

assign or_ln104_fu_913_p2 = (skip_done_fu_144 | inserted_fu_148);

assign or_ln10_fu_380_p2 = (icmp_ln13_fu_366_p2 | icmp_ln10_fu_360_p2);

assign or_ln137_fu_1119_p2 = (xor_ln137_fu_1109_p2 | xor_ln137_1_fu_1114_p2);

assign or_ln166_fu_1339_p2 = (trunc_ln166_fu_1335_p1 | select_ln166_fu_1327_p3);

assign or_ln_fu_1305_p3 = {{trunc_ln165_fu_1294_p1}, {trunc_ln165_1_reg_1712}};

assign out_1_fu_947_p3 = ((skip_now_2_reg_1645[0:0] === 1'b1) ? b_3_reg_273 : a_reg_284);

assign out_2_fu_1013_p3 = ((or_ln104_fu_913_p2[0:0] === 1'b1) ? select_ln118_fu_954_p3 : out_fu_926_p3);

assign out_3_fu_1021_p3 = ((and_ln112_fu_966_p2[0:0] === 1'b1) ? out_1_fu_947_p3 : out_2_fu_1013_p3);

assign out_5_fu_1029_p3 = ((sel_tmp6_fu_972_p2[0:0] === 1'b1) ? b_3_reg_273 : out_3_fu_1021_p3);

assign out_fu_926_p3 = ((take_new_2_reg_1639[0:0] === 1'b1) ? newValue : select_ln109_fu_919_p3);

assign prefetch_idx_fu_734_p3 = ((tmp_4_fu_720_p3[0:0] === 1'b1) ? 6'd63 : add_ln84_1_fu_728_p2);

assign quotient_1_fu_1355_p3 = {{tmp_fu_1345_p4}, {or_ln166_fu_1339_p2}};

assign rail_hits_1_fu_1125_p2 = (rail_hits_fu_140 + 16'd1);

assign remainder_1_fu_1298_p3 = {{remainder_reg_308}, {trunc_ln165_1_reg_1712}};

assign remainder_2_fu_1317_p2 = ($signed(or_ln_fu_1305_p3) - $signed(sext_ln160_2_reg_1692));

assign remainder_3_fu_1363_p3 = ((icmp_ln166_fu_1312_p2[0:0] === 1'b1) ? or_ln_fu_1305_p3 : remainder_2_fu_1317_p2);

assign removal_fu_472_p2 = ((n_old_reg_228 == zext_ln24_reg_1411) ? 1'b1 : 1'b0);

assign sel_tmp6_fu_972_p2 = (skip_done_fu_144 & inserted_fu_148);

assign select_ln104_fu_1001_p3 = ((or_ln104_fu_913_p2[0:0] === 1'b1) ? take_new_reg_1651 : take_new_2_reg_1639);

assign select_ln108_fu_858_p3 = ((skip_now_fu_847_p2[0:0] === 1'b1) ? le_c_fu_836_p2 : le_b_fu_825_p2);

assign select_ln109_fu_919_p3 = ((skip_now_reg_1623[0:0] === 1'b1) ? c_3_reg_263 : b_3_reg_273);

assign select_ln10_1_fu_386_p3 = ((or_ln10_fu_380_p2[0:0] === 1'b1) ? select_ln10_fu_372_p3 : trunc_ln24_1_fu_356_p1);

assign select_ln10_fu_372_p3 = ((icmp_ln10_fu_360_p2[0:0] === 1'b1) ? 7'd1 : 7'd64);

assign select_ln118_fu_954_p3 = ((take_new_reg_1651[0:0] === 1'b1) ? newValue : c_3_reg_263);

assign select_ln137_fu_1131_p3 = ((or_ln137_fu_1119_p2[0:0] === 1'b1) ? rail_hits_1_fu_1125_p2 : rail_hits_fu_140);

assign select_ln160_fu_1216_p3 = ((tmp_5_fu_1166_p3[0:0] === 1'b1) ? sub_ln160_1_fu_1193_p2 : zext_ln160_1_fu_1212_p1);

assign select_ln166_fu_1327_p3 = ((icmp_ln166_fu_1312_p2[0:0] === 1'b1) ? 23'd0 : shl_ln168_fu_1322_p2);

assign select_ln48_fu_509_p3 = ((xor_ln48_fu_497_p2[0:0] === 1'b1) ? 16'd0 : add_ln48_1_fu_503_p2);

assign select_ln54_fu_434_p3 = ((tmp_1_fu_426_p3[0:0] === 1'b1) ? 15'd0 : trunc_ln24_fu_352_p1);

assign sext_ln160_1_fu_1163_p1 = kept_count_reg_1678;

assign sext_ln160_2_fu_1160_p1 = kept_count_reg_1678;

assign sext_ln160_3_fu_1208_p1 = $signed(trunc_ln160_1_fu_1199_p4);

assign sext_ln160_4_fu_1224_p1 = $signed(select_ln160_fu_1216_p3);

assign sext_ln160_fu_1157_p1 = kept_count_reg_1678;

assign sext_ln48_fu_482_p1 = bufferIndex_loc_0_reg_240;

assign sext_ln57_fu_535_p1 = n_out_fu_523_p3;

assign sext_ln64_fu_674_p1 = $signed(trunc_ln64_2_reg_1520);

assign sext_ln94_fu_758_p1 = $signed(add_ln94_fu_752_p2);

assign shl_ln168_fu_1322_p2 = 23'd1 << zext_ln161_reg_1707;

assign shl_ln_fu_588_p3 = {{select_ln54_reg_1476}, {1'd0}};

assign skip_done_1_fu_942_p2 = (cand_valid_reg_1629 & and_ln111_fu_937_p2);

assign skip_done_3_fu_993_p3 = ((inserted_fu_148[0:0] === 1'b1) ? newSel_fu_978_p3 : newSel31_fu_985_p3);

assign skip_now_2_fu_883_p2 = (valid_m1_reg_1581 & and_ln113_fu_878_p2);

assign skip_now_fu_847_p2 = (valid_0_reg_1586 & and_ln106_fu_842_p2);

assign sub_ln160_1_fu_1193_p2 = (17'd0 - zext_ln160_fu_1189_p1);

assign sub_ln160_fu_1173_p2 = ($signed(17'd0) - $signed(sext_ln160_1_fu_1163_p1));

assign sub_ln63_1_fu_623_p2 = (16'd0 - trunc_ln63_1_reg_1510);

assign sub_ln63_fu_539_p2 = ($signed(17'd1) - $signed(sext_ln57_fu_535_p1));

assign sub_ln64_1_fu_677_p2 = (16'd0 - trunc_ln64_1_fu_664_p4);

assign sub_ln64_fu_659_p2 = ($signed(17'd0) - $signed(sext_ln57_reg_1503));

assign sum_1_fu_1095_p2 = (sum_fu_132 + zext_ln126_fu_1092_p1);

assign sum_2_fu_1101_p3 = ((and_ln125_fu_1087_p2[0:0] === 1'b1) ? sum_1_fu_1095_p2 : sum_fu_132);

assign take_new_2_fu_872_p2 = (xor_ln108_fu_866_p2 | select_ln108_fu_858_p3);

assign take_new_fu_893_p2 = (xor_ln117_fu_888_p2 | le_c_fu_836_p2);

assign tmp_1_fu_426_p3 = trim_count[32'd15];

assign tmp_2_fu_615_p3 = add_ln63_fu_610_p2[32'd16];

assign tmp_4_fu_720_p3 = add_ln84_fu_714_p2[32'd6];

assign tmp_5_fu_1166_p3 = kept_count_reg_1678[32'd15];

assign tmp_6_fu_1280_p3 = bit_1_fu_1274_p2[32'd5];

assign tmp_fu_1345_p4 = {{quotient_reg_319[31:23]}};

assign trunc_ln160_1_fu_1199_p4 = {{kept_count_reg_1678[15:1]}};

assign trunc_ln165_1_fu_1266_p1 = lshr_ln165_fu_1261_p2[0:0];

assign trunc_ln165_fu_1294_p1 = remainder_reg_308[29:0];

assign trunc_ln166_fu_1335_p1 = quotient_reg_319[22:0];

assign trunc_ln171_fu_1371_p1 = or_ln166_reg_1727[15:0];

assign trunc_ln24_1_fu_356_p1 = window_size[6:0];

assign trunc_ln24_fu_352_p1 = trim_count[14:0];

assign trunc_ln57_fu_531_p1 = n_out_fu_523_p3[0:0];

assign trunc_ln63_2_fu_628_p4 = {{add_ln63_fu_610_p2[16:1]}};

assign trunc_ln64_1_fu_664_p4 = {{sub_ln64_fu_659_p2[16:1]}};

assign trunc_ln82_fu_1153_p1 = sum_fu_132[22:0];

assign trunc_ln84_fu_702_p1 = ap_phi_mux_i_phi_fu_255_p4[5:0];

assign valid_0_fu_768_p2 = (($signed(zext_ln84_fu_706_p1) < $signed(n_old_reg_228)) ? 1'b1 : 1'b0);

assign valid_m1_fu_762_p2 = (($signed(sext_ln94_fu_758_p1) < $signed(n_old_reg_228)) ? 1'b1 : 1'b0);

assign valid_p1_fu_784_p2 = (($signed(zext_ln96_fu_780_p1) < $signed(n_old_reg_228)) ? 1'b1 : 1'b0);

assign xor_ln108_fu_866_p2 = (cand_valid_fu_852_p3 ^ 1'd1);

assign xor_ln111_fu_932_p2 = (select_ln108_reg_1634 ^ 1'd1);

assign xor_ln112_fu_960_p2 = (skip_done_fu_144 ^ 1'd1);

assign xor_ln117_fu_888_p2 = (valid_p1_reg_1592 ^ 1'd1);

assign xor_ln125_fu_1082_p2 = (icmp_ln125_reg_1598_pp0_iter2_reg ^ 1'd1);

assign xor_ln137_1_fu_1114_p2 = (icmp_ln137_1_reg_1673 ^ 1'd1);

assign xor_ln137_fu_1109_p2 = (icmp_ln137_reg_1668 ^ 1'd1);

assign xor_ln48_fu_497_p2 = (icmp_ln48_fu_492_p2 ^ 1'd1);

assign xor_ln57_fu_604_p2 = (icmp_ln57_fu_599_p2 ^ 1'd1);

assign zext_ln126_fu_1092_p1 = out_5_reg_1663;

assign zext_ln153_1_fu_1237_p1 = med_hi_fu_136;

assign zext_ln153_fu_1234_p1 = med_lo_2_reg_1657;

assign zext_ln160_1_fu_1212_p1 = $unsigned(sext_ln160_3_fu_1208_p1);

assign zext_ln160_fu_1189_p1 = lshr_ln160_1_fu_1179_p4;

assign zext_ln161_fu_1257_p1 = ap_phi_mux_bit_phi_fu_301_p4;

assign zext_ln163_fu_1270_p1 = ap_phi_mux_bit_phi_fu_301_p4;

assign zext_ln24_1_fu_585_p1 = select_ln54_reg_1476;

assign zext_ln24_fu_394_p1 = select_ln10_1_fu_386_p3;

assign zext_ln39_fu_398_p1 = select_ln10_1_fu_386_p3;

assign zext_ln46_fu_477_p1 = $unsigned(bufferIndex_loc_0_reg_240);

assign zext_ln57_fu_595_p1 = shl_ln_fu_588_p3;

assign zext_ln82_fu_902_p1 = i_reg_251_pp0_iter1_reg;

assign zext_ln84_1_fu_710_p1 = trunc_ln84_fu_702_p1;

assign zext_ln84_fu_706_p1 = trunc_ln84_fu_702_p1;

assign zext_ln85_fu_742_p1 = prefetch_idx_fu_734_p3;

assign zext_ln96_fu_780_p1 = add_ln96_fu_774_p2;

always @ (posedge ap_clk) begin
    zext_ln24_reg_1411[15:7] <= 9'b000000000;
    zext_ln39_reg_1416[16:7] <= 10'b0000000000;
    zext_ln161_reg_1707[22:5] <= 18'b000000000000000000;
end

endmodule //median_filter_get_filtered_value
