board: 'digilentinc.com:zybo-z7-20:part0:1.0'
part: 'XC7Z020'
path_to_hls_installation: '/tools/Xilinx/Vivado/2020.1/bin'


path_to_models: './SI_Toolkit_ASF/Experiments/'
net_name: 'Dense-7IN-16H1-16H2-1OUT-0'
batch_size: 1

PRECISION:
  input_and_output: 'ap_fixed<12,2>'
  activations: 'ap_fixed<12,1>'
  weights_and_biases: 'ap_fixed<12,4>'
  intermediate_results: 'ap_fixed<18,6>'  # Also set as "Model precision" and used for all quantizations not included above

Strategy: 'Resources'  # Resources or Latency
ReuseFactor: 64

backend: 'Vivado'  # VivadoAccelerator or Vivado
#backend: 'VivadoAccelerator'  # VivadoAccelerator or Vivado

with_brunton_testing: true

output_dir: '../../m1/xxx' # Must be a very short path neer to the root filesystem. Otherwise it crashes silently