predictors_specifications_testing: ['ODE_TF']

# predictors_specifications may be a names from the list of predictors in config_predictors.yml (assuming specification make sense)
# It can be a names of networks or GPs e.g. 'GRU-6IN-32H1-32H2-5OUT-0' to be used for test
# For multiple network they must be in the same folder specified in predictors:neural_default:path_to_model
# One can also specify full path to each model as name,
# in this case the path from predictors:neural_default:path_to_model get overwritten
# Where multiple ODE models are available, one can specify the name after colon e.g. ["ODE_TF:simple", "ODE:st"]
# In this case name from predictor_config is getting overwritten

test_file: 'CP_neural-imitator_2023-04-20_18-41-54.csv'

path_to_testfile: './ExperimentRecordings/'

test_len: 'max'
test_max_horizon: 20  # Indicates prediction horizon for testing
test_start_idx: 0  # Indicates starting point from which data from test file should be taken

decimation: 1  # If your dataset has sampling frequency being multiple of your network's sampling frequency

test_hls: false