ANGLE_KP_FIRMWARE_DEFAULT = 400
ANGLE_KI_FIRMWARE_DEFAULT = 0
ANGLE_KD_FIRMWARE_DEFAULT = 400

POSITION_TARGET_FIRMWARE_DEFAULT = 0
POSITION_SMOOTHING_FIRMWARE_DEFAULT = 1

POSITION_KP_FIRMWARE_DEFAULT = 20
POSITION_KI_FIRMWARE_DEFAULT = 0
POSITION_KD_FIRMWARE_DEFAULT = 300


def set_firmware_parameters(InterfaceInstance):
    """
    This function sets the firmware parameters, It requires CartPoleInstance and accepts optionally ANGLE_AVG_LENGTH
    If provided ANGLE_AVG_LENGTH is set from provided value, otherwise from the default list on top of this file.
    Other parameters are now set only from the list on top of this file.
    """

    ANGLE_KP_FIRMWARE, ANGLE_KI_FIRMWARE, ANGLE_KD_FIRMWARE = \
        ANGLE_KP_FIRMWARE_DEFAULT, ANGLE_KI_FIRMWARE_DEFAULT, ANGLE_KD_FIRMWARE_DEFAULT

    POSITION_TARGET_FIRMWARE, POSITION_SMOOTHING_FIRMWARE, POSITION_KP_FIRMWARE, POSITION_KI_FIRMWARE, POSITION_KD_FIRMWARE = \
        POSITION_TARGET_FIRMWARE_DEFAULT, POSITION_SMOOTHING_FIRMWARE_DEFAULT, POSITION_KP_FIRMWARE_DEFAULT, POSITION_KI_FIRMWARE_DEFAULT, POSITION_KD_FIRMWARE_DEFAULT

    InterfaceInstance.set_config_PID(
        POSITION_KP_FIRMWARE,
        POSITION_KI_FIRMWARE,
        POSITION_KD_FIRMWARE,
        ANGLE_KP_FIRMWARE,
        ANGLE_KI_FIRMWARE,
        ANGLE_KD_FIRMWARE,
    )
