#ifndef __ENCODER_ZYNQ_H_
#define __ENCODER_ZYNQ_H_

#include "xquadrature_encoder.h"
#include "param_pkg.h"

#define ENCODER_ID XPAR_QUADRATURE_ENCODER_0_DEVICE_ID
#define ENCODER_BASEADDR XPAR_QUADRATURE_ENCODER_0_S_AXI_ENCODER_AXI_BASEADDR
#define ENCODER_COUNT_OFFSET XQUADRATURE_ENCODER_ENCODER_AXI_ADDR_COUNT_DATA
#define ENCODER_RESET_OFFSET XQUADRATURE_ENCODER_ENCODER_AXI_ADDR_RESET_DATA

#define ENCODER_COUNT_ADDR ENCODER_BASEADDR+ENCODER_COUNT_OFFSET
#define ENCODER_RESET_ADDR ENCODER_BASEADDR+ENCODER_RESET_OFFSET

#define SENSOR_EDGES_PER_REV 64
#define GEARBOX_RATIO        18.75
#define ENCODER_FULL_TRACK 4690

short EncoderValue;

void  Encoder_Init(void);
short Encoder_Read(void);
void Encoder_Set_Direction(short new_direction);

#endif /*__ENCODER_ZYNQ_H_*/
