#!/usr/bin/env bash
# Network swap rebuild: re-synthesize nn_marshal for the deployed network folder,
# refresh the Vivado IP catalog, upgrade the marshal instance, and rebuild the
# bitstream. VHDL network sources must already be in the Vivado project (via
# hls4ml conversion or manual fileset update).
#
# Usage (from repo root):
#   FPGA/VivadoProjects/swap_nn_and_build.sh
#   FPGA/VivadoProjects/swap_nn_and_build.sh FPGA/NeuralNetworks/<network_folder>
#
# Prerequisite: nn_marshal_config.h present in the network folder (generated by
# Convert_Network_With_hls4ml.py / generate_nn_marshal_config.py).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Development currently deploys the IROS short-pole network. An explicit
# argument is still required when intentionally restoring another network.
NETWORK_DIR="${1:-${ROOT}/FPGA/NeuralNetworks/hls4ml_short_pole}"
NETWORK_DIR="$(cd "${NETWORK_DIR}" && pwd)"

if [[ ! -f "${NETWORK_DIR}/nn_marshal_config.h" ]]; then
    echo "ERROR: ${NETWORK_DIR}/nn_marshal_config.h not found." >&2
    echo "Run hls4ml conversion (post_hls4ml_marshal_config.py) first." >&2
    exit 1
fi

export SECLOC_NN_NETWORK_DIR="${NETWORK_DIR}"
VITIS_HLS="${VITIS_HLS:-/media/santiago/Data/tools/Xilinx/Vitis/2020.1/bin/vitis_hls}"

echo "=== nn_marshal HLS (network: ${NETWORK_DIR}) ==="
(cd "${ROOT}/FPGA/CustomIPs/nn_marshal_hls" && "${VITIS_HLS}" -f run_hls.tcl)

echo "=== Vivado: upgrade nn_marshal + bitstream ==="
(cd "${ROOT}/FPGA/VivadoProjects" && vivado -mode batch -source swap_nn_and_build.tcl)

BUILT_BIT="${ROOT}/FPGA/VivadoProjects/CartpoleDriverZynq_AXIS_secloc/CartpoleDriverZynq_AXIS_secloc.runs/impl_1/cartpole_driver_design_wrapper.bit"
DEPLOY_BIT="${ROOT}/FPGA/bitstreams/cartpole_short_pole_secloc.bit"
if [[ ! -f "${BUILT_BIT}" ]]; then
    echo "ERROR: rebuilt bitstream not found at ${BUILT_BIT}" >&2
    exit 1
fi
cp "${BUILT_BIT}" "${DEPLOY_BIT}"
echo "Deployed BIT: ${DEPLOY_BIT}"
