#!/usr/bin/env bash
# Network swap rebuild: re-synthesize nn_marshal for the deployed network folder,
# refresh the Vivado IP catalog, upgrade the marshal instance, and rebuild the
# bitstream. VHDL network sources must already be in the Vivado project (via
# hls4ml conversion or manual fileset update).
#
# Usage (from repo root):
#   FPGA/VivadoProjects/swap_nn_and_build.sh
#   FPGA/VivadoProjects/swap_nn_and_build.sh FPGA/NeuralNetworks/<network_folder>
#
# Prerequisite: nn_marshal_config.h present in the network folder (generated by
# Convert_Network_With_hls4ml.py / generate_nn_marshal_config.py).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
NETWORK_DIR="${1:-${ROOT}/FPGA/NeuralNetworks/hls4ml_dense_1out_8_07_07_2026}"
NETWORK_DIR="$(cd "${NETWORK_DIR}" && pwd)"

if [[ ! -f "${NETWORK_DIR}/nn_marshal_config.h" ]]; then
    echo "ERROR: ${NETWORK_DIR}/nn_marshal_config.h not found." >&2
    echo "Run hls4ml conversion (post_hls4ml_marshal_config.py) first." >&2
    exit 1
fi

export SECLOC_NN_NETWORK_DIR="${NETWORK_DIR}"
VITIS_HLS="${VITIS_HLS:-/media/santiago/Data/tools/Xilinx/Vitis/2020.1/bin/vitis_hls}"

echo "=== nn_marshal HLS (network: ${NETWORK_DIR}) ==="
(cd "${ROOT}/FPGA/CustomIPs/nn_marshal_hls" && "${VITIS_HLS}" -f run_hls.tcl)

echo "=== Vivado: upgrade nn_marshal + bitstream ==="
(cd "${ROOT}/FPGA/VivadoProjects" && vivado -mode batch -source swap_nn_and_build.tcl)
